import { District } from '@prisma/client';
import { ELang } from '../../../src/common/enum/base';

const items = [
  {
    name: 'Ba Đình District',
    code: 1,
    division_type: 'district',
    codename: 'quan_ba_dinh',
    province_code: 1,
  },
  {
    name: 'Hoàn Kiếm District',
    code: 2,
    division_type: 'district',
    codename: 'quan_hoan_kiem',
    province_code: 1,
  },
  {
    name: 'Tây Hồ District',
    code: 3,
    division_type: 'district',
    codename: 'quan_tay_ho',
    province_code: 1,
  },
  {
    name: 'Long Biên District',
    code: 4,
    division_type: 'district',
    codename: 'quan_long_bien',
    province_code: 1,
  },
  {
    name: 'Cầu Giấy District',
    code: 5,
    division_type: 'district',
    codename: 'quan_cau_giay',
    province_code: 1,
  },
  {
    name: 'Đống Đa District',
    code: 6,
    division_type: 'district',
    codename: 'quan_dong_da',
    province_code: 1,
  },
  {
    name: 'Hai Bà District',
    code: 7,
    division_type: 'district',
    codename: 'quan_hai_ba_trung',
    province_code: 1,
  },
  {
    name: 'Hoàng Mai District',
    code: 8,
    division_type: 'district',
    codename: 'quan_hoang_mai',
    province_code: 1,
  },
  {
    name: 'Thanh Xuân District',
    code: 9,
    division_type: 'district',
    codename: 'quan_thanh_xuan',
    province_code: 1,
  },
  {
    name: 'Sóc Sơn District',
    code: 16,
    division_type: 'district',
    codename: 'huyen_soc_son',
    province_code: 1,
  },
  {
    name: 'Đông Anh District',
    code: 17,
    division_type: 'district',
    codename: 'huyen_dong_anh',
    province_code: 1,
  },
  {
    name: 'Gia Lâm District',
    code: 18,
    division_type: 'district',
    codename: 'huyen_gia_lam',
    province_code: 1,
  },
  {
    name: 'Nam Từ District',
    code: 19,
    division_type: 'district',
    codename: 'quan_nam_tu_liem',
    province_code: 1,
  },
  {
    name: 'Thanh Trì District',
    code: 20,
    division_type: 'district',
    codename: 'huyen_thanh_tri',
    province_code: 1,
  },
  {
    name: 'Bắc Từ District',
    code: 21,
    division_type: 'district',
    codename: 'quan_bac_tu_liem',
    province_code: 1,
  },
  {
    name: 'Mê Linh District',
    code: 250,
    division_type: 'district',
    codename: 'huyen_me_linh',
    province_code: 1,
  },
  {
    name: 'Hà Đông District',
    code: 268,
    division_type: 'district',
    codename: 'quan_ha_dong',
    province_code: 1,
  },
  {
    name: 'Sơn Tây Town',
    code: 269,
    division_type: 'town',
    codename: 'thi_xa_son_tay',
    province_code: 1,
  },
  {
    name: 'Ba Vì District',
    code: 271,
    division_type: 'district',
    codename: 'huyen_ba_vi',
    province_code: 1,
  },
  {
    name: 'Phúc Thọ District',
    code: 272,
    division_type: 'district',
    codename: 'huyen_phuc_tho',
    province_code: 1,
  },
  {
    name: 'Đan Phượng District',
    code: 273,
    division_type: 'district',
    codename: 'huyen_dan_phuong',
    province_code: 1,
  },
  {
    name: 'Hoài Đức District',
    code: 274,
    division_type: 'district',
    codename: 'huyen_hoai_duc',
    province_code: 1,
  },
  {
    name: 'Quốc Oai District',
    code: 275,
    division_type: 'district',
    codename: 'huyen_quoc_oai',
    province_code: 1,
  },
  {
    name: 'Thạch Thất District',
    code: 276,
    division_type: 'district',
    codename: 'huyen_thach_that',
    province_code: 1,
  },
  {
    name: 'Chương Mỹ District',
    code: 277,
    division_type: 'district',
    codename: 'huyen_chuong_my',
    province_code: 1,
  },
  {
    name: 'Thanh Oai District',
    code: 278,
    division_type: 'district',
    codename: 'huyen_thanh_oai',
    province_code: 1,
  },
  {
    name: 'Thường Tín District',
    code: 279,
    division_type: 'district',
    codename: 'huyen_thuong_tin',
    province_code: 1,
  },
  {
    name: 'Phú Xuyên District',
    code: 280,
    division_type: 'district',
    codename: 'huyen_phu_xuyen',
    province_code: 1,
  },
  {
    name: 'Ứng Hòa District',
    code: 281,
    division_type: 'district',
    codename: 'huyen_ung_hoa',
    province_code: 1,
  },
  {
    name: 'Mỹ Đức District',
    code: 282,
    division_type: 'district',
    codename: 'huyen_my_duc',
    province_code: 1,
  },
  {
    name: 'Hà Giang City',
    code: 24,
    division_type: 'city',
    codename: 'thanh_pho_ha_giang',
    province_code: 2,
  },
  {
    name: 'Đồng Văn District',
    code: 26,
    division_type: 'district',
    codename: 'huyen_dong_van',
    province_code: 2,
  },
  {
    name: 'Mèo Vạc District',
    code: 27,
    division_type: 'district',
    codename: 'huyen_meo_vac',
    province_code: 2,
  },
  {
    name: 'Yên Minh District',
    code: 28,
    division_type: 'district',
    codename: 'huyen_yen_minh',
    province_code: 2,
  },
  {
    name: 'Quản Bạ District',
    code: 29,
    division_type: 'district',
    codename: 'huyen_quan_ba',
    province_code: 2,
  },
  {
    name: 'Vị Xuyên District',
    code: 30,
    division_type: 'district',
    codename: 'huyen_vi_xuyen',
    province_code: 2,
  },
  {
    name: 'Bắc Mê District',
    code: 31,
    division_type: 'district',
    codename: 'huyen_bac_me',
    province_code: 2,
  },
  {
    name: 'Hoàng Su District',
    code: 32,
    division_type: 'district',
    codename: 'huyen_hoang_su_phi',
    province_code: 2,
  },
  {
    name: 'Xín Mần District',
    code: 33,
    division_type: 'district',
    codename: 'huyen_xin_man',
    province_code: 2,
  },
  {
    name: 'Bắc Quang District',
    code: 34,
    division_type: 'district',
    codename: 'huyen_bac_quang',
    province_code: 2,
  },
  {
    name: 'Quang Bình District',
    code: 35,
    division_type: 'district',
    codename: 'huyen_quang_binh',
    province_code: 2,
  },
  {
    name: 'Cao Bằng City',
    code: 40,
    division_type: 'city',
    codename: 'thanh_pho_cao_bang',
    province_code: 4,
  },
  {
    name: 'Bảo Lâm District',
    code: 42,
    division_type: 'district',
    codename: 'huyen_bao_lam',
    province_code: 4,
  },
  {
    name: 'Bảo Lạc District',
    code: 43,
    division_type: 'district',
    codename: 'huyen_bao_lac',
    province_code: 4,
  },
  {
    name: 'Hà Quảng District',
    code: 45,
    division_type: 'district',
    codename: 'huyen_ha_quang',
    province_code: 4,
  },
  {
    name: 'Trùng Khánh District',
    code: 47,
    division_type: 'district',
    codename: 'huyen_trung_khanh',
    province_code: 4,
  },
  {
    name: 'Hạ Lang District',
    code: 48,
    division_type: 'district',
    codename: 'huyen_ha_lang',
    province_code: 4,
  },
  {
    name: 'Quảng Hòa District',
    code: 49,
    division_type: 'district',
    codename: 'huyen_quang_hoa',
    province_code: 4,
  },
  {
    name: 'Hoà An District',
    code: 51,
    division_type: 'district',
    codename: 'huyen_hoa_an',
    province_code: 4,
  },
  {
    name: 'Nguyên Bình District',
    code: 52,
    division_type: 'district',
    codename: 'huyen_nguyen_binh',
    province_code: 4,
  },
  {
    name: 'Thạch An District',
    code: 53,
    division_type: 'district',
    codename: 'huyen_thach_an',
    province_code: 4,
  },
  {
    name: 'Bắc Kạn City',
    code: 58,
    division_type: 'city',
    codename: 'thanh_pho_bac_kan',
    province_code: 6,
  },
  {
    name: 'Pác Nặm District',
    code: 60,
    division_type: 'district',
    codename: 'huyen_pac_nam',
    province_code: 6,
  },
  {
    name: 'Ba Bể District',
    code: 61,
    division_type: 'district',
    codename: 'huyen_ba_be',
    province_code: 6,
  },
  {
    name: 'Ngân Sơn District',
    code: 62,
    division_type: 'district',
    codename: 'huyen_ngan_son',
    province_code: 6,
  },
  {
    name: 'Bạch Thông District',
    code: 63,
    division_type: 'district',
    codename: 'huyen_bach_thong',
    province_code: 6,
  },
  {
    name: 'Chợ Đồn District',
    code: 64,
    division_type: 'district',
    codename: 'huyen_cho_don',
    province_code: 6,
  },
  {
    name: 'Chợ Mới District',
    code: 65,
    division_type: 'district',
    codename: 'huyen_cho_moi',
    province_code: 6,
  },
  {
    name: 'Na Rì District',
    code: 66,
    division_type: 'district',
    codename: 'huyen_na_ri',
    province_code: 6,
  },
  {
    name: 'Tuyên Quang City',
    code: 70,
    division_type: 'city',
    codename: 'thanh_pho_tuyen_quang',
    province_code: 8,
  },
  {
    name: 'Lâm Bình District',
    code: 71,
    division_type: 'district',
    codename: 'huyen_lam_binh',
    province_code: 8,
  },
  {
    name: 'Na Hang District',
    code: 72,
    division_type: 'district',
    codename: 'huyen_na_hang',
    province_code: 8,
  },
  {
    name: 'Chiêm Hóa District',
    code: 73,
    division_type: 'district',
    codename: 'huyen_chiem_hoa',
    province_code: 8,
  },
  {
    name: 'Hàm Yên District',
    code: 74,
    division_type: 'district',
    codename: 'huyen_ham_yen',
    province_code: 8,
  },
  {
    name: 'Yên Sơn District',
    code: 75,
    division_type: 'district',
    codename: 'huyen_yen_son',
    province_code: 8,
  },
  {
    name: 'Sơn Dương District',
    code: 76,
    division_type: 'district',
    codename: 'huyen_son_duong',
    province_code: 8,
  },
  {
    name: 'Lào Cai City',
    code: 80,
    division_type: 'city',
    codename: 'thanh_pho_lao_cai',
    province_code: 10,
  },
  {
    name: 'Bát Xát District',
    code: 82,
    division_type: 'district',
    codename: 'huyen_bat_xat',
    province_code: 10,
  },
  {
    name: 'Mường Khương District',
    code: 83,
    division_type: 'district',
    codename: 'huyen_muong_khuong',
    province_code: 10,
  },
  {
    name: 'Si Ma District',
    code: 84,
    division_type: 'district',
    codename: 'huyen_si_ma_cai',
    province_code: 10,
  },
  {
    name: 'Bắc Hà District',
    code: 85,
    division_type: 'district',
    codename: 'huyen_bac_ha',
    province_code: 10,
  },
  {
    name: 'Bảo Thắng District',
    code: 86,
    division_type: 'district',
    codename: 'huyen_bao_thang',
    province_code: 10,
  },
  {
    name: 'Bảo Yên District',
    code: 87,
    division_type: 'district',
    codename: 'huyen_bao_yen',
    province_code: 10,
  },
  {
    name: 'Sa Pa Town',
    code: 88,
    division_type: 'town',
    codename: 'thi_xa_sa_pa',
    province_code: 10,
  },
  {
    name: 'Văn Bàn District',
    code: 89,
    division_type: 'district',
    codename: 'huyen_van_ban',
    province_code: 10,
  },
  {
    name: 'Điện Biên City',
    code: 94,
    division_type: 'city',
    codename: 'thanh_pho_dien_bien_phu',
    province_code: 11,
  },
  {
    name: 'Mường Lay Town',
    code: 95,
    division_type: 'town',
    codename: 'thi_xa_muong_lay',
    province_code: 11,
  },
  {
    name: 'Mường Nhé District',
    code: 96,
    division_type: 'district',
    codename: 'huyen_muong_nhe',
    province_code: 11,
  },
  {
    name: 'Mường Chà District',
    code: 97,
    division_type: 'district',
    codename: 'huyen_muong_cha',
    province_code: 11,
  },
  {
    name: 'Tủa Chùa District',
    code: 98,
    division_type: 'district',
    codename: 'huyen_tua_chua',
    province_code: 11,
  },
  {
    name: 'Tuần Giáo District',
    code: 99,
    division_type: 'district',
    codename: 'huyen_tuan_giao',
    province_code: 11,
  },
  {
    name: 'Điện Biên District',
    code: 100,
    division_type: 'district',
    codename: 'huyen_dien_bien',
    province_code: 11,
  },
  {
    name: 'Điện Biên District',
    code: 101,
    division_type: 'district',
    codename: 'huyen_dien_bien_dong',
    province_code: 11,
  },
  {
    name: 'Mường Ảng District',
    code: 102,
    division_type: 'district',
    codename: 'huyen_muong_ang',
    province_code: 11,
  },
  {
    name: 'Nậm Pồ District',
    code: 103,
    division_type: 'district',
    codename: 'huyen_nam_po',
    province_code: 11,
  },
  {
    name: 'Lai Châu City',
    code: 105,
    division_type: 'city',
    codename: 'thanh_pho_lai_chau',
    province_code: 12,
  },
  {
    name: 'Tam Đường District',
    code: 106,
    division_type: 'district',
    codename: 'huyen_tam_duong',
    province_code: 12,
  },
  {
    name: 'Mường Tè District',
    code: 107,
    division_type: 'district',
    codename: 'huyen_muong_te',
    province_code: 12,
  },
  {
    name: 'Sìn Hồ District',
    code: 108,
    division_type: 'district',
    codename: 'huyen_sin_ho',
    province_code: 12,
  },
  {
    name: 'Phong Thổ District',
    code: 109,
    division_type: 'district',
    codename: 'huyen_phong_tho',
    province_code: 12,
  },
  {
    name: 'Than Uyên District',
    code: 110,
    division_type: 'district',
    codename: 'huyen_than_uyen',
    province_code: 12,
  },
  {
    name: 'Tân Uyên District',
    code: 111,
    division_type: 'district',
    codename: 'huyen_tan_uyen',
    province_code: 12,
  },
  {
    name: 'Nậm Nhùn District',
    code: 112,
    division_type: 'district',
    codename: 'huyen_nam_nhun',
    province_code: 12,
  },
  {
    name: 'Sơn La City',
    code: 116,
    division_type: 'city',
    codename: 'thanh_pho_son_la',
    province_code: 14,
  },
  {
    name: 'Quỳnh Nhai District',
    code: 118,
    division_type: 'district',
    codename: 'huyen_quynh_nhai',
    province_code: 14,
  },
  {
    name: 'Thuận Châu District',
    code: 119,
    division_type: 'district',
    codename: 'huyen_thuan_chau',
    province_code: 14,
  },
  {
    name: 'Mường La District',
    code: 120,
    division_type: 'district',
    codename: 'huyen_muong_la',
    province_code: 14,
  },
  {
    name: 'Bắc Yên District',
    code: 121,
    division_type: 'district',
    codename: 'huyen_bac_yen',
    province_code: 14,
  },
  {
    name: 'Phù Yên District',
    code: 122,
    division_type: 'district',
    codename: 'huyen_phu_yen',
    province_code: 14,
  },
  {
    name: 'Mộc Châu District',
    code: 123,
    division_type: 'district',
    codename: 'huyen_moc_chau',
    province_code: 14,
  },
  {
    name: 'Yên Châu District',
    code: 124,
    division_type: 'district',
    codename: 'huyen_yen_chau',
    province_code: 14,
  },
  {
    name: 'Mai Sơn District',
    code: 125,
    division_type: 'district',
    codename: 'huyen_mai_son',
    province_code: 14,
  },
  {
    name: 'Sông Mã District',
    code: 126,
    division_type: 'district',
    codename: 'huyen_song_ma',
    province_code: 14,
  },
  {
    name: 'Sốp Cộp District',
    code: 127,
    division_type: 'district',
    codename: 'huyen_sop_cop',
    province_code: 14,
  },
  {
    name: 'Vân Hồ District',
    code: 128,
    division_type: 'district',
    codename: 'huyen_van_ho',
    province_code: 14,
  },
  {
    name: 'Yên Bái City',
    code: 132,
    division_type: 'city',
    codename: 'thanh_pho_yen_bai',
    province_code: 15,
  },
  {
    name: 'Nghĩa Lộ Town',
    code: 133,
    division_type: 'town',
    codename: 'thi_xa_nghia_lo',
    province_code: 15,
  },
  {
    name: 'Lục Yên District',
    code: 135,
    division_type: 'district',
    codename: 'huyen_luc_yen',
    province_code: 15,
  },
  {
    name: 'Văn Yên District',
    code: 136,
    division_type: 'district',
    codename: 'huyen_van_yen',
    province_code: 15,
  },
  {
    name: 'Mù Căng District',
    code: 137,
    division_type: 'district',
    codename: 'huyen_mu_cang_chai',
    province_code: 15,
  },
  {
    name: 'Trấn Yên District',
    code: 138,
    division_type: 'district',
    codename: 'huyen_tran_yen',
    province_code: 15,
  },
  {
    name: 'Trạm Tấu District',
    code: 139,
    division_type: 'district',
    codename: 'huyen_tram_tau',
    province_code: 15,
  },
  {
    name: 'Văn Chấn District',
    code: 140,
    division_type: 'district',
    codename: 'huyen_van_chan',
    province_code: 15,
  },
  {
    name: 'Yên Bình District',
    code: 141,
    division_type: 'district',
    codename: 'huyen_yen_binh',
    province_code: 15,
  },
  {
    name: 'Hòa Bình City',
    code: 148,
    division_type: 'city',
    codename: 'thanh_pho_hoa_binh',
    province_code: 17,
  },
  {
    name: 'Đà Bắc District',
    code: 150,
    division_type: 'district',
    codename: 'huyen_da_bac',
    province_code: 17,
  },
  {
    name: 'Lương Sơn District',
    code: 152,
    division_type: 'district',
    codename: 'huyen_luong_son',
    province_code: 17,
  },
  {
    name: 'Kim Bôi District',
    code: 153,
    division_type: 'district',
    codename: 'huyen_kim_boi',
    province_code: 17,
  },
  {
    name: 'Cao Phong District',
    code: 154,
    division_type: 'district',
    codename: 'huyen_cao_phong',
    province_code: 17,
  },
  {
    name: 'Tân Lạc District',
    code: 155,
    division_type: 'district',
    codename: 'huyen_tan_lac',
    province_code: 17,
  },
  {
    name: 'Mai Châu District',
    code: 156,
    division_type: 'district',
    codename: 'huyen_mai_chau',
    province_code: 17,
  },
  {
    name: 'Lạc Sơn District',
    code: 157,
    division_type: 'district',
    codename: 'huyen_lac_son',
    province_code: 17,
  },
  {
    name: 'Yên Thủy District',
    code: 158,
    division_type: 'district',
    codename: 'huyen_yen_thuy',
    province_code: 17,
  },
  {
    name: 'Lạc Thủy District',
    code: 159,
    division_type: 'district',
    codename: 'huyen_lac_thuy',
    province_code: 17,
  },
  {
    name: 'Thái Nguyên City',
    code: 164,
    division_type: 'city',
    codename: 'thanh_pho_thai_nguyen',
    province_code: 19,
  },
  {
    name: 'Sông Công City',
    code: 165,
    division_type: 'city',
    codename: 'thanh_pho_song_cong',
    province_code: 19,
  },
  {
    name: 'Định Hóa District',
    code: 167,
    division_type: 'district',
    codename: 'huyen_dinh_hoa',
    province_code: 19,
  },
  {
    name: 'Phú Lương District',
    code: 168,
    division_type: 'district',
    codename: 'huyen_phu_luong',
    province_code: 19,
  },
  {
    name: 'Đồng Hỷ District',
    code: 169,
    division_type: 'district',
    codename: 'huyen_dong_hy',
    province_code: 19,
  },
  {
    name: 'Võ Nhai District',
    code: 170,
    division_type: 'district',
    codename: 'huyen_vo_nhai',
    province_code: 19,
  },
  {
    name: 'Đại Từ District',
    code: 171,
    division_type: 'district',
    codename: 'huyen_dai_tu',
    province_code: 19,
  },
  {
    name: 'Phổ Yên City',
    code: 172,
    division_type: 'city',
    codename: 'thanh_pho_pho_yen',
    province_code: 19,
  },
  {
    name: 'Phú Bình District',
    code: 173,
    division_type: 'district',
    codename: 'huyen_phu_binh',
    province_code: 19,
  },
  {
    name: 'Lạng Sơn City',
    code: 178,
    division_type: 'city',
    codename: 'thanh_pho_lang_son',
    province_code: 20,
  },
  {
    name: 'Tràng Định District',
    code: 180,
    division_type: 'district',
    codename: 'huyen_trang_dinh',
    province_code: 20,
  },
  {
    name: 'Bình Gia District',
    code: 181,
    division_type: 'district',
    codename: 'huyen_binh_gia',
    province_code: 20,
  },
  {
    name: 'Văn Lãng District',
    code: 182,
    division_type: 'district',
    codename: 'huyen_van_lang',
    province_code: 20,
  },
  {
    name: 'Cao Lộc District',
    code: 183,
    division_type: 'district',
    codename: 'huyen_cao_loc',
    province_code: 20,
  },
  {
    name: 'Văn Quan District',
    code: 184,
    division_type: 'district',
    codename: 'huyen_van_quan',
    province_code: 20,
  },
  {
    name: 'Bắc Sơn District',
    code: 185,
    division_type: 'district',
    codename: 'huyen_bac_son',
    province_code: 20,
  },
  {
    name: 'Hữu Lũng District',
    code: 186,
    division_type: 'district',
    codename: 'huyen_huu_lung',
    province_code: 20,
  },
  {
    name: 'Chi Lăng District',
    code: 187,
    division_type: 'district',
    codename: 'huyen_chi_lang',
    province_code: 20,
  },
  {
    name: 'Lộc Bình District',
    code: 188,
    division_type: 'district',
    codename: 'huyen_loc_binh',
    province_code: 20,
  },
  {
    name: 'Đình Lập District',
    code: 189,
    division_type: 'district',
    codename: 'huyen_dinh_lap',
    province_code: 20,
  },
  {
    name: 'Hạ Long City',
    code: 193,
    division_type: 'city',
    codename: 'thanh_pho_ha_long',
    province_code: 22,
  },
  {
    name: 'Móng Cái City',
    code: 194,
    division_type: 'city',
    codename: 'thanh_pho_mong_cai',
    province_code: 22,
  },
  {
    name: 'Cẩm Phả City',
    code: 195,
    division_type: 'city',
    codename: 'thanh_pho_cam_pha',
    province_code: 22,
  },
  {
    name: 'Uông Bí City',
    code: 196,
    division_type: 'city',
    codename: 'thanh_pho_uong_bi',
    province_code: 22,
  },
  {
    name: 'Bình Liêu District',
    code: 198,
    division_type: 'district',
    codename: 'huyen_binh_lieu',
    province_code: 22,
  },
  {
    name: 'Tiên Yên District',
    code: 199,
    division_type: 'district',
    codename: 'huyen_tien_yen',
    province_code: 22,
  },
  {
    name: 'Đầm Hà District',
    code: 200,
    division_type: 'district',
    codename: 'huyen_dam_ha',
    province_code: 22,
  },
  {
    name: 'Hải Hà District',
    code: 201,
    division_type: 'district',
    codename: 'huyen_hai_ha',
    province_code: 22,
  },
  {
    name: 'Ba Chẽ District',
    code: 202,
    division_type: 'district',
    codename: 'huyen_ba_che',
    province_code: 22,
  },
  {
    name: 'Vân Đồn District',
    code: 203,
    division_type: 'district',
    codename: 'huyen_van_don',
    province_code: 22,
  },
  {
    name: 'Đông Triều Town',
    code: 205,
    division_type: 'town',
    codename: 'thi_xa_dong_trieu',
    province_code: 22,
  },
  {
    name: 'Quảng Yên Town',
    code: 206,
    division_type: 'town',
    codename: 'thi_xa_quang_yen',
    province_code: 22,
  },
  {
    name: 'Cô Tô District',
    code: 207,
    division_type: 'district',
    codename: 'huyen_co_to',
    province_code: 22,
  },
  {
    name: 'Bắc Giang City',
    code: 213,
    division_type: 'city',
    codename: 'thanh_pho_bac_giang',
    province_code: 24,
  },
  {
    name: 'Yên Thế District',
    code: 215,
    division_type: 'district',
    codename: 'huyen_yen_the',
    province_code: 24,
  },
  {
    name: 'Tân Yên District',
    code: 216,
    division_type: 'district',
    codename: 'huyen_tan_yen',
    province_code: 24,
  },
  {
    name: 'Lạng Giang District',
    code: 217,
    division_type: 'district',
    codename: 'huyen_lang_giang',
    province_code: 24,
  },
  {
    name: 'Lục Nam District',
    code: 218,
    division_type: 'district',
    codename: 'huyen_luc_nam',
    province_code: 24,
  },
  {
    name: 'Lục Ngạn District',
    code: 219,
    division_type: 'district',
    codename: 'huyen_luc_ngan',
    province_code: 24,
  },
  {
    name: 'Sơn Động District',
    code: 220,
    division_type: 'district',
    codename: 'huyen_son_dong',
    province_code: 24,
  },
  {
    name: 'Yên Dũng District',
    code: 221,
    division_type: 'district',
    codename: 'huyen_yen_dung',
    province_code: 24,
  },
  {
    name: 'Việt Yên District',
    code: 222,
    division_type: 'district',
    codename: 'huyen_viet_yen',
    province_code: 24,
  },
  {
    name: 'Hiệp Hòa District',
    code: 223,
    division_type: 'district',
    codename: 'huyen_hiep_hoa',
    province_code: 24,
  },
  {
    name: 'Việt Trì City',
    code: 227,
    division_type: 'city',
    codename: 'thanh_pho_viet_tri',
    province_code: 25,
  },
  {
    name: 'Phú Thọ Town',
    code: 228,
    division_type: 'town',
    codename: 'thi_xa_phu_tho',
    province_code: 25,
  },
  {
    name: 'Đoan Hùng District',
    code: 230,
    division_type: 'district',
    codename: 'huyen_doan_hung',
    province_code: 25,
  },
  {
    name: 'Hạ Hoà District',
    code: 231,
    division_type: 'district',
    codename: 'huyen_ha_hoa',
    province_code: 25,
  },
  {
    name: 'Thanh Ba District',
    code: 232,
    division_type: 'district',
    codename: 'huyen_thanh_ba',
    province_code: 25,
  },
  {
    name: 'Phù Ninh District',
    code: 233,
    division_type: 'district',
    codename: 'huyen_phu_ninh',
    province_code: 25,
  },
  {
    name: 'Yên Lập District',
    code: 234,
    division_type: 'district',
    codename: 'huyen_yen_lap',
    province_code: 25,
  },
  {
    name: 'Cẩm Khê District',
    code: 235,
    division_type: 'district',
    codename: 'huyen_cam_khe',
    province_code: 25,
  },
  {
    name: 'Tam Nông District',
    code: 236,
    division_type: 'district',
    codename: 'huyen_tam_nong',
    province_code: 25,
  },
  {
    name: 'Lâm Thao District',
    code: 237,
    division_type: 'district',
    codename: 'huyen_lam_thao',
    province_code: 25,
  },
  {
    name: 'Thanh Sơn District',
    code: 238,
    division_type: 'district',
    codename: 'huyen_thanh_son',
    province_code: 25,
  },
  {
    name: 'Thanh Thuỷ District',
    code: 239,
    division_type: 'district',
    codename: 'huyen_thanh_thuy',
    province_code: 25,
  },
  {
    name: 'Tân Sơn District',
    code: 240,
    division_type: 'district',
    codename: 'huyen_tan_son',
    province_code: 25,
  },
  {
    name: 'Vĩnh Yên City',
    code: 243,
    division_type: 'city',
    codename: 'thanh_pho_vinh_yen',
    province_code: 26,
  },
  {
    name: 'Phúc Yên City',
    code: 244,
    division_type: 'city',
    codename: 'thanh_pho_phuc_yen',
    province_code: 26,
  },
  {
    name: 'Lập Thạch District',
    code: 246,
    division_type: 'district',
    codename: 'huyen_lap_thach',
    province_code: 26,
  },
  {
    name: 'Tam Dương District',
    code: 247,
    division_type: 'district',
    codename: 'huyen_tam_duong',
    province_code: 26,
  },
  {
    name: 'Tam Đảo District',
    code: 248,
    division_type: 'district',
    codename: 'huyen_tam_dao',
    province_code: 26,
  },
  {
    name: 'Bình Xuyên District',
    code: 249,
    division_type: 'district',
    codename: 'huyen_binh_xuyen',
    province_code: 26,
  },
  {
    name: 'Yên Lạc District',
    code: 251,
    division_type: 'district',
    codename: 'huyen_yen_lac',
    province_code: 26,
  },
  {
    name: 'Vĩnh Tường District',
    code: 252,
    division_type: 'district',
    codename: 'huyen_vinh_tuong',
    province_code: 26,
  },
  {
    name: 'Sông Lô District',
    code: 253,
    division_type: 'district',
    codename: 'huyen_song_lo',
    province_code: 26,
  },
  {
    name: 'Bắc Ninh City',
    code: 256,
    division_type: 'city',
    codename: 'thanh_pho_bac_ninh',
    province_code: 27,
  },
  {
    name: 'Yên Phong District',
    code: 258,
    division_type: 'district',
    codename: 'huyen_yen_phong',
    province_code: 27,
  },
  {
    name: 'Quế Võ Town',
    code: 259,
    division_type: 'town',
    codename: 'thi_xa_que_vo',
    province_code: 27,
  },
  {
    name: 'Tiên Du District',
    code: 260,
    division_type: 'district',
    codename: 'huyen_tien_du',
    province_code: 27,
  },
  {
    name: 'Từ Sơn City',
    code: 261,
    division_type: 'city',
    codename: 'thanh_pho_tu_son',
    province_code: 27,
  },
  {
    name: 'Thuận Thành Town',
    code: 262,
    division_type: 'town',
    codename: 'thi_xa_thuan_thanh',
    province_code: 27,
  },
  {
    name: 'Gia Bình District',
    code: 263,
    division_type: 'district',
    codename: 'huyen_gia_binh',
    province_code: 27,
  },
  {
    name: 'Lương Tài District',
    code: 264,
    division_type: 'district',
    codename: 'huyen_luong_tai',
    province_code: 27,
  },
  {
    name: 'Hải Dương City',
    code: 288,
    division_type: 'city',
    codename: 'thanh_pho_hai_duong',
    province_code: 30,
  },
  {
    name: 'Chí Linh City',
    code: 290,
    division_type: 'city',
    codename: 'thanh_pho_chi_linh',
    province_code: 30,
  },
  {
    name: 'Nam Sách District',
    code: 291,
    division_type: 'district',
    codename: 'huyen_nam_sach',
    province_code: 30,
  },
  {
    name: 'Kinh Môn Town',
    code: 292,
    division_type: 'town',
    codename: 'thi_xa_kinh_mon',
    province_code: 30,
  },
  {
    name: 'Kim Thành District',
    code: 293,
    division_type: 'district',
    codename: 'huyen_kim_thanh',
    province_code: 30,
  },
  {
    name: 'Thanh Hà District',
    code: 294,
    division_type: 'district',
    codename: 'huyen_thanh_ha',
    province_code: 30,
  },
  {
    name: 'Cẩm Giàng District',
    code: 295,
    division_type: 'district',
    codename: 'huyen_cam_giang',
    province_code: 30,
  },
  {
    name: 'Bình Giang District',
    code: 296,
    division_type: 'district',
    codename: 'huyen_binh_giang',
    province_code: 30,
  },
  {
    name: 'Gia Lộc District',
    code: 297,
    division_type: 'district',
    codename: 'huyen_gia_loc',
    province_code: 30,
  },
  {
    name: 'Tứ Kỳ District',
    code: 298,
    division_type: 'district',
    codename: 'huyen_tu_ky',
    province_code: 30,
  },
  {
    name: 'Ninh Giang District',
    code: 299,
    division_type: 'district',
    codename: 'huyen_ninh_giang',
    province_code: 30,
  },
  {
    name: 'Thanh Miện District',
    code: 300,
    division_type: 'district',
    codename: 'huyen_thanh_mien',
    province_code: 30,
  },
  {
    name: 'Hồng Bàng District',
    code: 303,
    division_type: 'district',
    codename: 'quan_hong_bang',
    province_code: 31,
  },
  {
    name: 'Ngô Quyền District',
    code: 304,
    division_type: 'district',
    codename: 'quan_ngo_quyen',
    province_code: 31,
  },
  {
    name: 'Lê Chân District',
    code: 305,
    division_type: 'district',
    codename: 'quan_le_chan',
    province_code: 31,
  },
  {
    name: 'Hải An District',
    code: 306,
    division_type: 'district',
    codename: 'quan_hai_an',
    province_code: 31,
  },
  {
    name: 'Kiến An District',
    code: 307,
    division_type: 'district',
    codename: 'quan_kien_an',
    province_code: 31,
  },
  {
    name: 'Đồ Sơn District',
    code: 308,
    division_type: 'district',
    codename: 'quan_do_son',
    province_code: 31,
  },
  {
    name: 'Dương Kinh District',
    code: 309,
    division_type: 'district',
    codename: 'quan_duong_kinh',
    province_code: 31,
  },
  {
    name: 'Thuỷ Nguyên District',
    code: 311,
    division_type: 'district',
    codename: 'huyen_thuy_nguyen',
    province_code: 31,
  },
  {
    name: 'An Dương District',
    code: 312,
    division_type: 'district',
    codename: 'huyen_an_duong',
    province_code: 31,
  },
  {
    name: 'An Lão District',
    code: 313,
    division_type: 'district',
    codename: 'huyen_an_lao',
    province_code: 31,
  },
  {
    name: 'Kiến Thuỵ District',
    code: 314,
    division_type: 'district',
    codename: 'huyen_kien_thuy',
    province_code: 31,
  },
  {
    name: 'Tiên Lãng District',
    code: 315,
    division_type: 'district',
    codename: 'huyen_tien_lang',
    province_code: 31,
  },
  {
    name: 'Vĩnh Bảo District',
    code: 316,
    division_type: 'district',
    codename: 'huyen_vinh_bao',
    province_code: 31,
  },
  {
    name: 'Cát Hải District',
    code: 317,
    division_type: 'district',
    codename: 'huyen_cat_hai',
    province_code: 31,
  },
  {
    name: 'Bạch Long District',
    code: 318,
    division_type: 'district',
    codename: 'huyen_bach_long_vi',
    province_code: 31,
  },
  {
    name: 'Hưng Yên City',
    code: 323,
    division_type: 'city',
    codename: 'thanh_pho_hung_yen',
    province_code: 33,
  },
  {
    name: 'Văn Lâm District',
    code: 325,
    division_type: 'district',
    codename: 'huyen_van_lam',
    province_code: 33,
  },
  {
    name: 'Văn Giang District',
    code: 326,
    division_type: 'district',
    codename: 'huyen_van_giang',
    province_code: 33,
  },
  {
    name: 'Yên Mỹ District',
    code: 327,
    division_type: 'district',
    codename: 'huyen_yen_my',
    province_code: 33,
  },
  {
    name: 'Mỹ Hào Town',
    code: 328,
    division_type: 'town',
    codename: 'thi_xa_my_hao',
    province_code: 33,
  },
  {
    name: 'Ân Thi District',
    code: 329,
    division_type: 'district',
    codename: 'huyen_an_thi',
    province_code: 33,
  },
  {
    name: 'Khoái Châu District',
    code: 330,
    division_type: 'district',
    codename: 'huyen_khoai_chau',
    province_code: 33,
  },
  {
    name: 'Kim Động District',
    code: 331,
    division_type: 'district',
    codename: 'huyen_kim_dong',
    province_code: 33,
  },
  {
    name: 'Tiên Lữ District',
    code: 332,
    division_type: 'district',
    codename: 'huyen_tien_lu',
    province_code: 33,
  },
  {
    name: 'Phù Cừ District',
    code: 333,
    division_type: 'district',
    codename: 'huyen_phu_cu',
    province_code: 33,
  },
  {
    name: 'Thái Bình City',
    code: 336,
    division_type: 'city',
    codename: 'thanh_pho_thai_binh',
    province_code: 34,
  },
  {
    name: 'Quỳnh Phụ District',
    code: 338,
    division_type: 'district',
    codename: 'huyen_quynh_phu',
    province_code: 34,
  },
  {
    name: 'Hưng Hà District',
    code: 339,
    division_type: 'district',
    codename: 'huyen_hung_ha',
    province_code: 34,
  },
  {
    name: 'Đông Hưng District',
    code: 340,
    division_type: 'district',
    codename: 'huyen_dong_hung',
    province_code: 34,
  },
  {
    name: 'Thái Thụy District',
    code: 341,
    division_type: 'district',
    codename: 'huyen_thai_thuy',
    province_code: 34,
  },
  {
    name: 'Tiền Hải District',
    code: 342,
    division_type: 'district',
    codename: 'huyen_tien_hai',
    province_code: 34,
  },
  {
    name: 'Kiến Xương District',
    code: 343,
    division_type: 'district',
    codename: 'huyen_kien_xuong',
    province_code: 34,
  },
  {
    name: 'Vũ Thư District',
    code: 344,
    division_type: 'district',
    codename: 'huyen_vu_thu',
    province_code: 34,
  },
  {
    name: 'Phủ Lý City',
    code: 347,
    division_type: 'city',
    codename: 'thanh_pho_phu_ly',
    province_code: 35,
  },
  {
    name: 'Duy Tiên Town',
    code: 349,
    division_type: 'town',
    codename: 'thi_xa_duy_tien',
    province_code: 35,
  },
  {
    name: 'Kim Bảng District',
    code: 350,
    division_type: 'district',
    codename: 'huyen_kim_bang',
    province_code: 35,
  },
  {
    name: 'Thanh Liêm District',
    code: 351,
    division_type: 'district',
    codename: 'huyen_thanh_liem',
    province_code: 35,
  },
  {
    name: 'Bình Lục District',
    code: 352,
    division_type: 'district',
    codename: 'huyen_binh_luc',
    province_code: 35,
  },
  {
    name: 'Lý Nhân District',
    code: 353,
    division_type: 'district',
    codename: 'huyen_ly_nhan',
    province_code: 35,
  },
  {
    name: 'Nam Định City',
    code: 356,
    division_type: 'city',
    codename: 'thanh_pho_nam_dinh',
    province_code: 36,
  },
  {
    name: 'Mỹ Lộc District',
    code: 358,
    division_type: 'district',
    codename: 'huyen_my_loc',
    province_code: 36,
  },
  {
    name: 'Vụ Bản District',
    code: 359,
    division_type: 'district',
    codename: 'huyen_vu_ban',
    province_code: 36,
  },
  {
    name: 'Ý Yên District',
    code: 360,
    division_type: 'district',
    codename: 'huyen_y_yen',
    province_code: 36,
  },
  {
    name: 'Nghĩa Hưng District',
    code: 361,
    division_type: 'district',
    codename: 'huyen_nghia_hung',
    province_code: 36,
  },
  {
    name: 'Nam Trực District',
    code: 362,
    division_type: 'district',
    codename: 'huyen_nam_truc',
    province_code: 36,
  },
  {
    name: 'Trực Ninh District',
    code: 363,
    division_type: 'district',
    codename: 'huyen_truc_ninh',
    province_code: 36,
  },
  {
    name: 'Xuân Trường District',
    code: 364,
    division_type: 'district',
    codename: 'huyen_xuan_truong',
    province_code: 36,
  },
  {
    name: 'Giao Thủy District',
    code: 365,
    division_type: 'district',
    codename: 'huyen_giao_thuy',
    province_code: 36,
  },
  {
    name: 'Hải Hậu District',
    code: 366,
    division_type: 'district',
    codename: 'huyen_hai_hau',
    province_code: 36,
  },
  {
    name: 'Ninh Bình City',
    code: 369,
    division_type: 'city',
    codename: 'thanh_pho_ninh_binh',
    province_code: 37,
  },
  {
    name: 'Tam Điệp City',
    code: 370,
    division_type: 'city',
    codename: 'thanh_pho_tam_diep',
    province_code: 37,
  },
  {
    name: 'Nho Quan District',
    code: 372,
    division_type: 'district',
    codename: 'huyen_nho_quan',
    province_code: 37,
  },
  {
    name: 'Gia Viễn District',
    code: 373,
    division_type: 'district',
    codename: 'huyen_gia_vien',
    province_code: 37,
  },
  {
    name: 'Hoa Lư District',
    code: 374,
    division_type: 'district',
    codename: 'huyen_hoa_lu',
    province_code: 37,
  },
  {
    name: 'Yên Khánh District',
    code: 375,
    division_type: 'district',
    codename: 'huyen_yen_khanh',
    province_code: 37,
  },
  {
    name: 'Kim Sơn District',
    code: 376,
    division_type: 'district',
    codename: 'huyen_kim_son',
    province_code: 37,
  },
  {
    name: 'Yên Mô District',
    code: 377,
    division_type: 'district',
    codename: 'huyen_yen_mo',
    province_code: 37,
  },
  {
    name: 'Thanh Hóa City',
    code: 380,
    division_type: 'city',
    codename: 'thanh_pho_thanh_hoa',
    province_code: 38,
  },
  {
    name: 'Bỉm Sơn Town',
    code: 381,
    division_type: 'town',
    codename: 'thi_xa_bim_son',
    province_code: 38,
  },
  {
    name: 'Sầm Sơn City',
    code: 382,
    division_type: 'city',
    codename: 'thanh_pho_sam_son',
    province_code: 38,
  },
  {
    name: 'Mường Lát District',
    code: 384,
    division_type: 'district',
    codename: 'huyen_muong_lat',
    province_code: 38,
  },
  {
    name: 'Quan Hóa District',
    code: 385,
    division_type: 'district',
    codename: 'huyen_quan_hoa',
    province_code: 38,
  },
  {
    name: 'Bá Thước District',
    code: 386,
    division_type: 'district',
    codename: 'huyen_ba_thuoc',
    province_code: 38,
  },
  {
    name: 'Quan Sơn District',
    code: 387,
    division_type: 'district',
    codename: 'huyen_quan_son',
    province_code: 38,
  },
  {
    name: 'Lang Chánh District',
    code: 388,
    division_type: 'district',
    codename: 'huyen_lang_chanh',
    province_code: 38,
  },
  {
    name: 'Ngọc Lặc District',
    code: 389,
    division_type: 'district',
    codename: 'huyen_ngoc_lac',
    province_code: 38,
  },
  {
    name: 'Cẩm Thủy District',
    code: 390,
    division_type: 'district',
    codename: 'huyen_cam_thuy',
    province_code: 38,
  },
  {
    name: 'Thạch Thành District',
    code: 391,
    division_type: 'district',
    codename: 'huyen_thach_thanh',
    province_code: 38,
  },
  {
    name: 'Hà Trung District',
    code: 392,
    division_type: 'district',
    codename: 'huyen_ha_trung',
    province_code: 38,
  },
  {
    name: 'Vĩnh Lộc District',
    code: 393,
    division_type: 'district',
    codename: 'huyen_vinh_loc',
    province_code: 38,
  },
  {
    name: 'Yên Định District',
    code: 394,
    division_type: 'district',
    codename: 'huyen_yen_dinh',
    province_code: 38,
  },
  {
    name: 'Thọ Xuân District',
    code: 395,
    division_type: 'district',
    codename: 'huyen_tho_xuan',
    province_code: 38,
  },
  {
    name: 'Thường Xuân District',
    code: 396,
    division_type: 'district',
    codename: 'huyen_thuong_xuan',
    province_code: 38,
  },
  {
    name: 'Triệu Sơn District',
    code: 397,
    division_type: 'district',
    codename: 'huyen_trieu_son',
    province_code: 38,
  },
  {
    name: 'Thiệu Hóa District',
    code: 398,
    division_type: 'district',
    codename: 'huyen_thieu_hoa',
    province_code: 38,
  },
  {
    name: 'Hoằng Hóa District',
    code: 399,
    division_type: 'district',
    codename: 'huyen_hoang_hoa',
    province_code: 38,
  },
  {
    name: 'Hậu Lộc District',
    code: 400,
    division_type: 'district',
    codename: 'huyen_hau_loc',
    province_code: 38,
  },
  {
    name: 'Nga Sơn District',
    code: 401,
    division_type: 'district',
    codename: 'huyen_nga_son',
    province_code: 38,
  },
  {
    name: 'Như Xuân District',
    code: 402,
    division_type: 'district',
    codename: 'huyen_nhu_xuan',
    province_code: 38,
  },
  {
    name: 'Như Thanh District',
    code: 403,
    division_type: 'district',
    codename: 'huyen_nhu_thanh',
    province_code: 38,
  },
  {
    name: 'Nông Cống District',
    code: 404,
    division_type: 'district',
    codename: 'huyen_nong_cong',
    province_code: 38,
  },
  {
    name: 'Đông Sơn District',
    code: 405,
    division_type: 'district',
    codename: 'huyen_dong_son',
    province_code: 38,
  },
  {
    name: 'Quảng Xương District',
    code: 406,
    division_type: 'district',
    codename: 'huyen_quang_xuong',
    province_code: 38,
  },
  {
    name: 'Nghi Sơn Town',
    code: 407,
    division_type: 'town',
    codename: 'thi_xa_nghi_son',
    province_code: 38,
  },
  {
    name: 'Vinh  City',
    code: 412,
    division_type: 'city',
    codename: 'thanh_pho_vinh',
    province_code: 40,
  },
  {
    name: 'Cửa Lò Town',
    code: 413,
    division_type: 'town',
    codename: 'thi_xa_cua_lo',
    province_code: 40,
  },
  {
    name: 'Thái Hoà Town',
    code: 414,
    division_type: 'town',
    codename: 'thi_xa_thai_hoa',
    province_code: 40,
  },
  {
    name: 'Quế Phong District',
    code: 415,
    division_type: 'district',
    codename: 'huyen_que_phong',
    province_code: 40,
  },
  {
    name: 'Quỳ Châu District',
    code: 416,
    division_type: 'district',
    codename: 'huyen_quy_chau',
    province_code: 40,
  },
  {
    name: 'Kỳ Sơn District',
    code: 417,
    division_type: 'district',
    codename: 'huyen_ky_son',
    province_code: 40,
  },
  {
    name: 'Tương Dương District',
    code: 418,
    division_type: 'district',
    codename: 'huyen_tuong_duong',
    province_code: 40,
  },
  {
    name: 'Nghĩa Đàn District',
    code: 419,
    division_type: 'district',
    codename: 'huyen_nghia_dan',
    province_code: 40,
  },
  {
    name: 'Quỳ Hợp District',
    code: 420,
    division_type: 'district',
    codename: 'huyen_quy_hop',
    province_code: 40,
  },
  {
    name: 'Quỳnh Lưu District',
    code: 421,
    division_type: 'district',
    codename: 'huyen_quynh_luu',
    province_code: 40,
  },
  {
    name: 'Con Cuông District',
    code: 422,
    division_type: 'district',
    codename: 'huyen_con_cuong',
    province_code: 40,
  },
  {
    name: 'Tân Kỳ District',
    code: 423,
    division_type: 'district',
    codename: 'huyen_tan_ky',
    province_code: 40,
  },
  {
    name: 'Anh Sơn District',
    code: 424,
    division_type: 'district',
    codename: 'huyen_anh_son',
    province_code: 40,
  },
  {
    name: 'Diễn Châu District',
    code: 425,
    division_type: 'district',
    codename: 'huyen_dien_chau',
    province_code: 40,
  },
  {
    name: 'Yên Thành District',
    code: 426,
    division_type: 'district',
    codename: 'huyen_yen_thanh',
    province_code: 40,
  },
  {
    name: 'Đô Lương District',
    code: 427,
    division_type: 'district',
    codename: 'huyen_do_luong',
    province_code: 40,
  },
  {
    name: 'Thanh Chương District',
    code: 428,
    division_type: 'district',
    codename: 'huyen_thanh_chuong',
    province_code: 40,
  },
  {
    name: 'Nghi Lộc District',
    code: 429,
    division_type: 'district',
    codename: 'huyen_nghi_loc',
    province_code: 40,
  },
  {
    name: 'Nam Đàn District',
    code: 430,
    division_type: 'district',
    codename: 'huyen_nam_dan',
    province_code: 40,
  },
  {
    name: 'Hưng Nguyên District',
    code: 431,
    division_type: 'district',
    codename: 'huyen_hung_nguyen',
    province_code: 40,
  },
  {
    name: 'Hoàng Mai Town',
    code: 432,
    division_type: 'town',
    codename: 'thi_xa_hoang_mai',
    province_code: 40,
  },
  {
    name: 'Hà Tĩnh City',
    code: 436,
    division_type: 'city',
    codename: 'thanh_pho_ha_tinh',
    province_code: 42,
  },
  {
    name: 'Hồng Lĩnh Town',
    code: 437,
    division_type: 'town',
    codename: 'thi_xa_hong_linh',
    province_code: 42,
  },
  {
    name: 'Hương Sơn District',
    code: 439,
    division_type: 'district',
    codename: 'huyen_huong_son',
    province_code: 42,
  },
  {
    name: 'Đức Thọ District',
    code: 440,
    division_type: 'district',
    codename: 'huyen_duc_tho',
    province_code: 42,
  },
  {
    name: 'Vũ Quang District',
    code: 441,
    division_type: 'district',
    codename: 'huyen_vu_quang',
    province_code: 42,
  },
  {
    name: 'Nghi Xuân District',
    code: 442,
    division_type: 'district',
    codename: 'huyen_nghi_xuan',
    province_code: 42,
  },
  {
    name: 'Can Lộc District',
    code: 443,
    division_type: 'district',
    codename: 'huyen_can_loc',
    province_code: 42,
  },
  {
    name: 'Hương Khê District',
    code: 444,
    division_type: 'district',
    codename: 'huyen_huong_khe',
    province_code: 42,
  },
  {
    name: 'Thạch Hà District',
    code: 445,
    division_type: 'district',
    codename: 'huyen_thach_ha',
    province_code: 42,
  },
  {
    name: 'Cẩm Xuyên District',
    code: 446,
    division_type: 'district',
    codename: 'huyen_cam_xuyen',
    province_code: 42,
  },
  {
    name: 'Kỳ Anh District',
    code: 447,
    division_type: 'district',
    codename: 'huyen_ky_anh',
    province_code: 42,
  },
  {
    name: 'Lộc Hà District',
    code: 448,
    division_type: 'district',
    codename: 'huyen_loc_ha',
    province_code: 42,
  },
  {
    name: 'Kỳ Anh Town',
    code: 449,
    division_type: 'town',
    codename: 'thi_xa_ky_anh',
    province_code: 42,
  },
  {
    name: 'Đồng Hới City',
    code: 450,
    division_type: 'city',
    codename: 'thanh_pho_dong_hoi',
    province_code: 44,
  },
  {
    name: 'Minh Hóa District',
    code: 452,
    division_type: 'district',
    codename: 'huyen_minh_hoa',
    province_code: 44,
  },
  {
    name: 'Tuyên Hóa District',
    code: 453,
    division_type: 'district',
    codename: 'huyen_tuyen_hoa',
    province_code: 44,
  },
  {
    name: 'Quảng Trạch District',
    code: 454,
    division_type: 'district',
    codename: 'huyen_quang_trach',
    province_code: 44,
  },
  {
    name: 'Bố Trạch District',
    code: 455,
    division_type: 'district',
    codename: 'huyen_bo_trach',
    province_code: 44,
  },
  {
    name: 'Quảng Ninh District',
    code: 456,
    division_type: 'district',
    codename: 'huyen_quang_ninh',
    province_code: 44,
  },
  {
    name: 'Lệ Thủy District',
    code: 457,
    division_type: 'district',
    codename: 'huyen_le_thuy',
    province_code: 44,
  },
  {
    name: 'Ba Đồn Town',
    code: 458,
    division_type: 'town',
    codename: 'thi_xa_ba_don',
    province_code: 44,
  },
  {
    name: 'Đông Hà City',
    code: 461,
    division_type: 'city',
    codename: 'thanh_pho_dong_ha',
    province_code: 45,
  },
  {
    name: 'Quảng Trị Town',
    code: 462,
    division_type: 'town',
    codename: 'thi_xa_quang_tri',
    province_code: 45,
  },
  {
    name: 'Vĩnh Linh District',
    code: 464,
    division_type: 'district',
    codename: 'huyen_vinh_linh',
    province_code: 45,
  },
  {
    name: 'Hướng Hóa District',
    code: 465,
    division_type: 'district',
    codename: 'huyen_huong_hoa',
    province_code: 45,
  },
  {
    name: 'Gio Linh District',
    code: 466,
    division_type: 'district',
    codename: 'huyen_gio_linh',
    province_code: 45,
  },
  {
    name: 'Đa Krông District',
    code: 467,
    division_type: 'district',
    codename: 'huyen_da_krong',
    province_code: 45,
  },
  {
    name: 'Cam Lộ District',
    code: 468,
    division_type: 'district',
    codename: 'huyen_cam_lo',
    province_code: 45,
  },
  {
    name: 'Triệu Phong District',
    code: 469,
    division_type: 'district',
    codename: 'huyen_trieu_phong',
    province_code: 45,
  },
  {
    name: 'Hải Lăng District',
    code: 470,
    division_type: 'district',
    codename: 'huyen_hai_lang',
    province_code: 45,
  },
  {
    name: 'Cồn Cỏ District',
    code: 471,
    division_type: 'district',
    codename: 'huyen_con_co',
    province_code: 45,
  },
  {
    name: 'Huế  City',
    code: 474,
    division_type: 'city',
    codename: 'thanh_pho_hue',
    province_code: 46,
  },
  {
    name: 'Phong Điền District',
    code: 476,
    division_type: 'district',
    codename: 'huyen_phong_dien',
    province_code: 46,
  },
  {
    name: 'Quảng Điền District',
    code: 477,
    division_type: 'district',
    codename: 'huyen_quang_dien',
    province_code: 46,
  },
  {
    name: 'Phú Vang District',
    code: 478,
    division_type: 'district',
    codename: 'huyen_phu_vang',
    province_code: 46,
  },
  {
    name: 'Hương Thủy Town',
    code: 479,
    division_type: 'town',
    codename: 'thi_xa_huong_thuy',
    province_code: 46,
  },
  {
    name: 'Hương Trà Town',
    code: 480,
    division_type: 'town',
    codename: 'thi_xa_huong_tra',
    province_code: 46,
  },
  {
    name: 'A Lưới District',
    code: 481,
    division_type: 'district',
    codename: 'huyen_a_luoi',
    province_code: 46,
  },
  {
    name: 'Phú Lộc District',
    code: 482,
    division_type: 'district',
    codename: 'huyen_phu_loc',
    province_code: 46,
  },
  {
    name: 'Nam Đông District',
    code: 483,
    division_type: 'district',
    codename: 'huyen_nam_dong',
    province_code: 46,
  },
  {
    name: 'Liên Chiểu District',
    code: 490,
    division_type: 'district',
    codename: 'quan_lien_chieu',
    province_code: 48,
  },
  {
    name: 'Thanh Khê District',
    code: 491,
    division_type: 'district',
    codename: 'quan_thanh_khe',
    province_code: 48,
  },
  {
    name: 'Hải Châu District',
    code: 492,
    division_type: 'district',
    codename: 'quan_hai_chau',
    province_code: 48,
  },
  {
    name: 'Sơn Trà District',
    code: 493,
    division_type: 'district',
    codename: 'quan_son_tra',
    province_code: 48,
  },
  {
    name: 'Ngũ Hành District',
    code: 494,
    division_type: 'district',
    codename: 'quan_ngu_hanh_son',
    province_code: 48,
  },
  {
    name: 'Cẩm Lệ District',
    code: 495,
    division_type: 'district',
    codename: 'quan_cam_le',
    province_code: 48,
  },
  {
    name: 'Hòa Vang District',
    code: 497,
    division_type: 'district',
    codename: 'huyen_hoa_vang',
    province_code: 48,
  },
  {
    name: 'Hoàng Sa District',
    code: 498,
    division_type: 'district',
    codename: 'huyen_hoang_sa',
    province_code: 48,
  },
  {
    name: 'Tam Kỳ City',
    code: 502,
    division_type: 'city',
    codename: 'thanh_pho_tam_ky',
    province_code: 49,
  },
  {
    name: 'Hội An City',
    code: 503,
    division_type: 'city',
    codename: 'thanh_pho_hoi_an',
    province_code: 49,
  },
  {
    name: 'Tây Giang District',
    code: 504,
    division_type: 'district',
    codename: 'huyen_tay_giang',
    province_code: 49,
  },
  {
    name: 'Đông Giang District',
    code: 505,
    division_type: 'district',
    codename: 'huyen_dong_giang',
    province_code: 49,
  },
  {
    name: 'Đại Lộc District',
    code: 506,
    division_type: 'district',
    codename: 'huyen_dai_loc',
    province_code: 49,
  },
  {
    name: 'Điện Bàn Town',
    code: 507,
    division_type: 'town',
    codename: 'thi_xa_dien_ban',
    province_code: 49,
  },
  {
    name: 'Duy Xuyên District',
    code: 508,
    division_type: 'district',
    codename: 'huyen_duy_xuyen',
    province_code: 49,
  },
  {
    name: 'Quế Sơn District',
    code: 509,
    division_type: 'district',
    codename: 'huyen_que_son',
    province_code: 49,
  },
  {
    name: 'Nam Giang District',
    code: 510,
    division_type: 'district',
    codename: 'huyen_nam_giang',
    province_code: 49,
  },
  {
    name: 'Phước Sơn District',
    code: 511,
    division_type: 'district',
    codename: 'huyen_phuoc_son',
    province_code: 49,
  },
  {
    name: 'Hiệp Đức District',
    code: 512,
    division_type: 'district',
    codename: 'huyen_hiep_duc',
    province_code: 49,
  },
  {
    name: 'Thăng Bình District',
    code: 513,
    division_type: 'district',
    codename: 'huyen_thang_binh',
    province_code: 49,
  },
  {
    name: 'Tiên Phước District',
    code: 514,
    division_type: 'district',
    codename: 'huyen_tien_phuoc',
    province_code: 49,
  },
  {
    name: 'Bắc Trà District',
    code: 515,
    division_type: 'district',
    codename: 'huyen_bac_tra_my',
    province_code: 49,
  },
  {
    name: 'Nam Trà District',
    code: 516,
    division_type: 'district',
    codename: 'huyen_nam_tra_my',
    province_code: 49,
  },
  {
    name: 'Núi Thành District',
    code: 517,
    division_type: 'district',
    codename: 'huyen_nui_thanh',
    province_code: 49,
  },
  {
    name: 'Phú Ninh District',
    code: 518,
    division_type: 'district',
    codename: 'huyen_phu_ninh',
    province_code: 49,
  },
  {
    name: 'Nông Sơn District',
    code: 519,
    division_type: 'district',
    codename: 'huyen_nong_son',
    province_code: 49,
  },
  {
    name: 'Quảng Ngãi City',
    code: 522,
    division_type: 'city',
    codename: 'thanh_pho_quang_ngai',
    province_code: 51,
  },
  {
    name: 'Bình Sơn District',
    code: 524,
    division_type: 'district',
    codename: 'huyen_binh_son',
    province_code: 51,
  },
  {
    name: 'Trà Bồng District',
    code: 525,
    division_type: 'district',
    codename: 'huyen_tra_bong',
    province_code: 51,
  },
  {
    name: 'Sơn Tịnh District',
    code: 527,
    division_type: 'district',
    codename: 'huyen_son_tinh',
    province_code: 51,
  },
  {
    name: 'Tư Nghĩa District',
    code: 528,
    division_type: 'district',
    codename: 'huyen_tu_nghia',
    province_code: 51,
  },
  {
    name: 'Sơn Hà District',
    code: 529,
    division_type: 'district',
    codename: 'huyen_son_ha',
    province_code: 51,
  },
  {
    name: 'Sơn Tây District',
    code: 530,
    division_type: 'district',
    codename: 'huyen_son_tay',
    province_code: 51,
  },
  {
    name: 'Minh Long District',
    code: 531,
    division_type: 'district',
    codename: 'huyen_minh_long',
    province_code: 51,
  },
  {
    name: 'Nghĩa Hành District',
    code: 532,
    division_type: 'district',
    codename: 'huyen_nghia_hanh',
    province_code: 51,
  },
  {
    name: 'Mộ Đức District',
    code: 533,
    division_type: 'district',
    codename: 'huyen_mo_duc',
    province_code: 51,
  },
  {
    name: 'Đức Phổ Town',
    code: 534,
    division_type: 'town',
    codename: 'thi_xa_duc_pho',
    province_code: 51,
  },
  {
    name: 'Ba Tơ District',
    code: 535,
    division_type: 'district',
    codename: 'huyen_ba_to',
    province_code: 51,
  },
  {
    name: 'Lý Sơn District',
    code: 536,
    division_type: 'district',
    codename: 'huyen_ly_son',
    province_code: 51,
  },
  {
    name: 'Quy Nhơn City',
    code: 540,
    division_type: 'city',
    codename: 'thanh_pho_quy_nhon',
    province_code: 52,
  },
  {
    name: 'An Lão District',
    code: 542,
    division_type: 'district',
    codename: 'huyen_an_lao',
    province_code: 52,
  },
  {
    name: 'Hoài Nhơn Town',
    code: 543,
    division_type: 'town',
    codename: 'thi_xa_hoai_nhon',
    province_code: 52,
  },
  {
    name: 'Hoài Ân District',
    code: 544,
    division_type: 'district',
    codename: 'huyen_hoai_an',
    province_code: 52,
  },
  {
    name: 'Phù Mỹ District',
    code: 545,
    division_type: 'district',
    codename: 'huyen_phu_my',
    province_code: 52,
  },
  {
    name: 'Vĩnh Thạnh District',
    code: 546,
    division_type: 'district',
    codename: 'huyen_vinh_thanh',
    province_code: 52,
  },
  {
    name: 'Tây Sơn District',
    code: 547,
    division_type: 'district',
    codename: 'huyen_tay_son',
    province_code: 52,
  },
  {
    name: 'Phù Cát District',
    code: 548,
    division_type: 'district',
    codename: 'huyen_phu_cat',
    province_code: 52,
  },
  {
    name: 'An Nhơn Town',
    code: 549,
    division_type: 'town',
    codename: 'thi_xa_an_nhon',
    province_code: 52,
  },
  {
    name: 'Tuy Phước District',
    code: 550,
    division_type: 'district',
    codename: 'huyen_tuy_phuoc',
    province_code: 52,
  },
  {
    name: 'Vân Canh District',
    code: 551,
    division_type: 'district',
    codename: 'huyen_van_canh',
    province_code: 52,
  },
  {
    name: 'Tuy Hoà City',
    code: 555,
    division_type: 'city',
    codename: 'thanh_pho_tuy_hoa',
    province_code: 54,
  },
  {
    name: 'Sông Cầu Town',
    code: 557,
    division_type: 'town',
    codename: 'thi_xa_song_cau',
    province_code: 54,
  },
  {
    name: 'Đồng Xuân District',
    code: 558,
    division_type: 'district',
    codename: 'huyen_dong_xuan',
    province_code: 54,
  },
  {
    name: 'Tuy An District',
    code: 559,
    division_type: 'district',
    codename: 'huyen_tuy_an',
    province_code: 54,
  },
  {
    name: 'Sơn Hòa District',
    code: 560,
    division_type: 'district',
    codename: 'huyen_son_hoa',
    province_code: 54,
  },
  {
    name: 'Sông Hinh District',
    code: 561,
    division_type: 'district',
    codename: 'huyen_song_hinh',
    province_code: 54,
  },
  {
    name: 'Tây Hoà District',
    code: 562,
    division_type: 'district',
    codename: 'huyen_tay_hoa',
    province_code: 54,
  },
  {
    name: 'Phú Hoà District',
    code: 563,
    division_type: 'district',
    codename: 'huyen_phu_hoa',
    province_code: 54,
  },
  {
    name: 'Đông Hòa Town',
    code: 564,
    division_type: 'town',
    codename: 'thi_xa_dong_hoa',
    province_code: 54,
  },
  {
    name: 'Nha Trang City',
    code: 568,
    division_type: 'city',
    codename: 'thanh_pho_nha_trang',
    province_code: 56,
  },
  {
    name: 'Cam Ranh City',
    code: 569,
    division_type: 'city',
    codename: 'thanh_pho_cam_ranh',
    province_code: 56,
  },
  {
    name: 'Cam Lâm District',
    code: 570,
    division_type: 'district',
    codename: 'huyen_cam_lam',
    province_code: 56,
  },
  {
    name: 'Vạn Ninh District',
    code: 571,
    division_type: 'district',
    codename: 'huyen_van_ninh',
    province_code: 56,
  },
  {
    name: 'Ninh Hòa Town',
    code: 572,
    division_type: 'town',
    codename: 'thi_xa_ninh_hoa',
    province_code: 56,
  },
  {
    name: 'Khánh Vĩnh District',
    code: 573,
    division_type: 'district',
    codename: 'huyen_khanh_vinh',
    province_code: 56,
  },
  {
    name: 'Diên Khánh District',
    code: 574,
    division_type: 'district',
    codename: 'huyen_dien_khanh',
    province_code: 56,
  },
  {
    name: 'Khánh Sơn District',
    code: 575,
    division_type: 'district',
    codename: 'huyen_khanh_son',
    province_code: 56,
  },
  {
    name: 'Trường Sa District',
    code: 576,
    division_type: 'district',
    codename: 'huyen_truong_sa',
    province_code: 56,
  },
  {
    name: 'Phan Rang-Tháp City',
    code: 582,
    division_type: 'city',
    codename: 'thanh_pho_phan_rang_thap_cham',
    province_code: 58,
  },
  {
    name: 'Bác Ái District',
    code: 584,
    division_type: 'district',
    codename: 'huyen_bac_ai',
    province_code: 58,
  },
  {
    name: 'Ninh Sơn District',
    code: 585,
    division_type: 'district',
    codename: 'huyen_ninh_son',
    province_code: 58,
  },
  {
    name: 'Ninh Hải District',
    code: 586,
    division_type: 'district',
    codename: 'huyen_ninh_hai',
    province_code: 58,
  },
  {
    name: 'Ninh Phước District',
    code: 587,
    division_type: 'district',
    codename: 'huyen_ninh_phuoc',
    province_code: 58,
  },
  {
    name: 'Thuận Bắc District',
    code: 588,
    division_type: 'district',
    codename: 'huyen_thuan_bac',
    province_code: 58,
  },
  {
    name: 'Thuận Nam District',
    code: 589,
    division_type: 'district',
    codename: 'huyen_thuan_nam',
    province_code: 58,
  },
  {
    name: 'Phan Thiết City',
    code: 593,
    division_type: 'city',
    codename: 'thanh_pho_phan_thiet',
    province_code: 60,
  },
  {
    name: 'La Gi Town',
    code: 594,
    division_type: 'town',
    codename: 'thi_xa_la_gi',
    province_code: 60,
  },
  {
    name: 'Tuy Phong District',
    code: 595,
    division_type: 'district',
    codename: 'huyen_tuy_phong',
    province_code: 60,
  },
  {
    name: 'Bắc Bình District',
    code: 596,
    division_type: 'district',
    codename: 'huyen_bac_binh',
    province_code: 60,
  },
  {
    name: 'Hàm Thuận District',
    code: 597,
    division_type: 'district',
    codename: 'huyen_ham_thuan_bac',
    province_code: 60,
  },
  {
    name: 'Hàm Thuận District',
    code: 598,
    division_type: 'district',
    codename: 'huyen_ham_thuan_nam',
    province_code: 60,
  },
  {
    name: 'Tánh Linh District',
    code: 599,
    division_type: 'district',
    codename: 'huyen_tanh_linh',
    province_code: 60,
  },
  {
    name: 'Đức Linh District',
    code: 600,
    division_type: 'district',
    codename: 'huyen_duc_linh',
    province_code: 60,
  },
  {
    name: 'Hàm Tân District',
    code: 601,
    division_type: 'district',
    codename: 'huyen_ham_tan',
    province_code: 60,
  },
  {
    name: 'Phú Quí District',
    code: 602,
    division_type: 'district',
    codename: 'huyen_phu_qui',
    province_code: 60,
  },
  {
    name: 'Kon Tum City',
    code: 608,
    division_type: 'city',
    codename: 'thanh_pho_kon_tum',
    province_code: 62,
  },
  {
    name: 'Đắk Glei District',
    code: 610,
    division_type: 'district',
    codename: 'huyen_dak_glei',
    province_code: 62,
  },
  {
    name: 'Ngọc Hồi District',
    code: 611,
    division_type: 'district',
    codename: 'huyen_ngoc_hoi',
    province_code: 62,
  },
  {
    name: 'Đắk Tô District',
    code: 612,
    division_type: 'district',
    codename: 'huyen_dak_to',
    province_code: 62,
  },
  {
    name: 'Kon Plông District',
    code: 613,
    division_type: 'district',
    codename: 'huyen_kon_plong',
    province_code: 62,
  },
  {
    name: 'Kon Rẫy District',
    code: 614,
    division_type: 'district',
    codename: 'huyen_kon_ray',
    province_code: 62,
  },
  {
    name: 'Đắk Hà District',
    code: 615,
    division_type: 'district',
    codename: 'huyen_dak_ha',
    province_code: 62,
  },
  {
    name: 'Sa Thầy District',
    code: 616,
    division_type: 'district',
    codename: 'huyen_sa_thay',
    province_code: 62,
  },
  {
    name: 'Tu Mơ District',
    code: 617,
    division_type: 'district',
    codename: 'huyen_tu_mo_rong',
    province_code: 62,
  },
  {
    name: "Ia H' District",
    code: 618,
    division_type: 'district',
    codename: 'huyen_ia_h_drai',
    province_code: 62,
  },
  {
    name: 'Pleiku  City',
    code: 622,
    division_type: 'city',
    codename: 'thanh_pho_pleiku',
    province_code: 64,
  },
  {
    name: 'An Khê Town',
    code: 623,
    division_type: 'town',
    codename: 'thi_xa_an_khe',
    province_code: 64,
  },
  {
    name: 'Ayun Pa Town',
    code: 624,
    division_type: 'town',
    codename: 'thi_xa_ayun_pa',
    province_code: 64,
  },
  {
    name: 'KBang  District',
    code: 625,
    division_type: 'district',
    codename: 'huyen_kbang',
    province_code: 64,
  },
  {
    name: 'Đăk Đoa District',
    code: 626,
    division_type: 'district',
    codename: 'huyen_dak_doa',
    province_code: 64,
  },
  {
    name: 'Chư Păh District',
    code: 627,
    division_type: 'district',
    codename: 'huyen_chu_pah',
    province_code: 64,
  },
  {
    name: 'Ia Grai District',
    code: 628,
    division_type: 'district',
    codename: 'huyen_ia_grai',
    province_code: 64,
  },
  {
    name: 'Mang Yang District',
    code: 629,
    division_type: 'district',
    codename: 'huyen_mang_yang',
    province_code: 64,
  },
  {
    name: 'Kông Chro District',
    code: 630,
    division_type: 'district',
    codename: 'huyen_kong_chro',
    province_code: 64,
  },
  {
    name: 'Đức Cơ District',
    code: 631,
    division_type: 'district',
    codename: 'huyen_duc_co',
    province_code: 64,
  },
  {
    name: 'Chư Prông District',
    code: 632,
    division_type: 'district',
    codename: 'huyen_chu_prong',
    province_code: 64,
  },
  {
    name: 'Chư Sê District',
    code: 633,
    division_type: 'district',
    codename: 'huyen_chu_se',
    province_code: 64,
  },
  {
    name: 'Đăk Pơ District',
    code: 634,
    division_type: 'district',
    codename: 'huyen_dak_po',
    province_code: 64,
  },
  {
    name: 'Ia Pa District',
    code: 635,
    division_type: 'district',
    codename: 'huyen_ia_pa',
    province_code: 64,
  },
  {
    name: 'Krông Pa District',
    code: 637,
    division_type: 'district',
    codename: 'huyen_krong_pa',
    province_code: 64,
  },
  {
    name: 'Phú Thiện District',
    code: 638,
    division_type: 'district',
    codename: 'huyen_phu_thien',
    province_code: 64,
  },
  {
    name: 'Chư Pưh District',
    code: 639,
    division_type: 'district',
    codename: 'huyen_chu_puh',
    province_code: 64,
  },
  {
    name: 'Buôn Ma City',
    code: 643,
    division_type: 'city',
    codename: 'thanh_pho_buon_ma_thuot',
    province_code: 66,
  },
  {
    name: 'Buôn Hồ Town',
    code: 644,
    division_type: 'town',
    codename: 'thi_xa_buon_ho',
    province_code: 66,
  },
  {
    name: "Ea H'leo District",
    code: 645,
    division_type: 'district',
    codename: 'huyen_ea_hleo',
    province_code: 66,
  },
  {
    name: 'Ea Súp District',
    code: 646,
    division_type: 'district',
    codename: 'huyen_ea_sup',
    province_code: 66,
  },
  {
    name: 'Buôn Đôn District',
    code: 647,
    division_type: 'district',
    codename: 'huyen_buon_don',
    province_code: 66,
  },
  {
    name: "Cư M'gar District",
    code: 648,
    division_type: 'district',
    codename: 'huyen_cu_mgar',
    province_code: 66,
  },
  {
    name: 'Krông Búk District',
    code: 649,
    division_type: 'district',
    codename: 'huyen_krong_buk',
    province_code: 66,
  },
  {
    name: 'Krông Năng District',
    code: 650,
    division_type: 'district',
    codename: 'huyen_krong_nang',
    province_code: 66,
  },
  {
    name: 'Ea Kar District',
    code: 651,
    division_type: 'district',
    codename: 'huyen_ea_kar',
    province_code: 66,
  },
  {
    name: "M'Đrắk  District",
    code: 652,
    division_type: 'district',
    codename: 'huyen_mdrak',
    province_code: 66,
  },
  {
    name: 'Krông Bông District',
    code: 653,
    division_type: 'district',
    codename: 'huyen_krong_bong',
    province_code: 66,
  },
  {
    name: 'Krông Pắc District',
    code: 654,
    division_type: 'district',
    codename: 'huyen_krong_pac',
    province_code: 66,
  },
  {
    name: 'Krông A District',
    code: 655,
    division_type: 'district',
    codename: 'huyen_krong_a_na',
    province_code: 66,
  },
  {
    name: 'Lắk  District',
    code: 656,
    division_type: 'district',
    codename: 'huyen_lak',
    province_code: 66,
  },
  {
    name: 'Cư Kuin District',
    code: 657,
    division_type: 'district',
    codename: 'huyen_cu_kuin',
    province_code: 66,
  },
  {
    name: 'Gia Nghĩa City',
    code: 660,
    division_type: 'city',
    codename: 'thanh_pho_gia_nghia',
    province_code: 67,
  },
  {
    name: 'Đăk Glong District',
    code: 661,
    division_type: 'district',
    codename: 'huyen_dak_glong',
    province_code: 67,
  },
  {
    name: 'Cư Jút District',
    code: 662,
    division_type: 'district',
    codename: 'huyen_cu_jut',
    province_code: 67,
  },
  {
    name: 'Đắk Mil District',
    code: 663,
    division_type: 'district',
    codename: 'huyen_dak_mil',
    province_code: 67,
  },
  {
    name: 'Krông Nô District',
    code: 664,
    division_type: 'district',
    codename: 'huyen_krong_no',
    province_code: 67,
  },
  {
    name: 'Đắk Song District',
    code: 665,
    division_type: 'district',
    codename: 'huyen_dak_song',
    province_code: 67,
  },
  {
    name: "Đắk R'Lấp District",
    code: 666,
    division_type: 'district',
    codename: 'huyen_dak_rlap',
    province_code: 67,
  },
  {
    name: 'Tuy Đức District',
    code: 667,
    division_type: 'district',
    codename: 'huyen_tuy_duc',
    province_code: 67,
  },
  {
    name: 'Đà Lạt City',
    code: 672,
    division_type: 'city',
    codename: 'thanh_pho_da_lat',
    province_code: 68,
  },
  {
    name: 'Bảo Lộc City',
    code: 673,
    division_type: 'city',
    codename: 'thanh_pho_bao_loc',
    province_code: 68,
  },
  {
    name: 'Đam Rông District',
    code: 674,
    division_type: 'district',
    codename: 'huyen_dam_rong',
    province_code: 68,
  },
  {
    name: 'Lạc Dương District',
    code: 675,
    division_type: 'district',
    codename: 'huyen_lac_duong',
    province_code: 68,
  },
  {
    name: 'Lâm Hà District',
    code: 676,
    division_type: 'district',
    codename: 'huyen_lam_ha',
    province_code: 68,
  },
  {
    name: 'Đơn Dương District',
    code: 677,
    division_type: 'district',
    codename: 'huyen_don_duong',
    province_code: 68,
  },
  {
    name: 'Đức Trọng District',
    code: 678,
    division_type: 'district',
    codename: 'huyen_duc_trong',
    province_code: 68,
  },
  {
    name: 'Di Linh District',
    code: 679,
    division_type: 'district',
    codename: 'huyen_di_linh',
    province_code: 68,
  },
  {
    name: 'Bảo Lâm District',
    code: 680,
    division_type: 'district',
    codename: 'huyen_bao_lam',
    province_code: 68,
  },
  {
    name: 'Đạ Huoai District',
    code: 681,
    division_type: 'district',
    codename: 'huyen_da_huoai',
    province_code: 68,
  },
  {
    name: 'Đạ Tẻh District',
    code: 682,
    division_type: 'district',
    codename: 'huyen_da_teh',
    province_code: 68,
  },
  {
    name: 'Cát Tiên District',
    code: 683,
    division_type: 'district',
    codename: 'huyen_cat_tien',
    province_code: 68,
  },
  {
    name: 'Phước Long Town',
    code: 688,
    division_type: 'town',
    codename: 'thi_xa_phuoc_long',
    province_code: 70,
  },
  {
    name: 'Đồng Xoài City',
    code: 689,
    division_type: 'city',
    codename: 'thanh_pho_dong_xoai',
    province_code: 70,
  },
  {
    name: 'Bình Long Town',
    code: 690,
    division_type: 'town',
    codename: 'thi_xa_binh_long',
    province_code: 70,
  },
  {
    name: 'Bù Gia District',
    code: 691,
    division_type: 'district',
    codename: 'huyen_bu_gia_map',
    province_code: 70,
  },
  {
    name: 'Lộc Ninh District',
    code: 692,
    division_type: 'district',
    codename: 'huyen_loc_ninh',
    province_code: 70,
  },
  {
    name: 'Bù Đốp District',
    code: 693,
    division_type: 'district',
    codename: 'huyen_bu_dop',
    province_code: 70,
  },
  {
    name: 'Hớn Quản District',
    code: 694,
    division_type: 'district',
    codename: 'huyen_hon_quan',
    province_code: 70,
  },
  {
    name: 'Đồng Phú District',
    code: 695,
    division_type: 'district',
    codename: 'huyen_dong_phu',
    province_code: 70,
  },
  {
    name: 'Bù Đăng District',
    code: 696,
    division_type: 'district',
    codename: 'huyen_bu_dang',
    province_code: 70,
  },
  {
    name: 'Chơn Thành Town',
    code: 697,
    division_type: 'town',
    codename: 'thi_xa_chon_thanh',
    province_code: 70,
  },
  {
    name: 'Phú Riềng District',
    code: 698,
    division_type: 'district',
    codename: 'huyen_phu_rieng',
    province_code: 70,
  },
  {
    name: 'Tây Ninh City',
    code: 703,
    division_type: 'city',
    codename: 'thanh_pho_tay_ninh',
    province_code: 72,
  },
  {
    name: 'Tân Biên District',
    code: 705,
    division_type: 'district',
    codename: 'huyen_tan_bien',
    province_code: 72,
  },
  {
    name: 'Tân Châu District',
    code: 706,
    division_type: 'district',
    codename: 'huyen_tan_chau',
    province_code: 72,
  },
  {
    name: 'Dương Minh District',
    code: 707,
    division_type: 'district',
    codename: 'huyen_duong_minh_chau',
    province_code: 72,
  },
  {
    name: 'Châu Thành District',
    code: 708,
    division_type: 'district',
    codename: 'huyen_chau_thanh',
    province_code: 72,
  },
  {
    name: 'Hòa Thành Town',
    code: 709,
    division_type: 'town',
    codename: 'thi_xa_hoa_thanh',
    province_code: 72,
  },
  {
    name: 'Gò Dầu District',
    code: 710,
    division_type: 'district',
    codename: 'huyen_go_dau',
    province_code: 72,
  },
  {
    name: 'Bến Cầu District',
    code: 711,
    division_type: 'district',
    codename: 'huyen_ben_cau',
    province_code: 72,
  },
  {
    name: 'Trảng Bàng Town',
    code: 712,
    division_type: 'town',
    codename: 'thi_xa_trang_bang',
    province_code: 72,
  },
  {
    name: 'Thủ Dầu City',
    code: 718,
    division_type: 'city',
    codename: 'thanh_pho_thu_dau_mot',
    province_code: 74,
  },
  {
    name: 'Bàu Bàng District',
    code: 719,
    division_type: 'district',
    codename: 'huyen_bau_bang',
    province_code: 74,
  },
  {
    name: 'Dầu Tiếng District',
    code: 720,
    division_type: 'district',
    codename: 'huyen_dau_tieng',
    province_code: 74,
  },
  {
    name: 'Bến Cát Town',
    code: 721,
    division_type: 'town',
    codename: 'thi_xa_ben_cat',
    province_code: 74,
  },
  {
    name: 'Phú Giáo District',
    code: 722,
    division_type: 'district',
    codename: 'huyen_phu_giao',
    province_code: 74,
  },
  {
    name: 'Tân Uyên City',
    code: 723,
    division_type: 'city',
    codename: 'thanh_pho_tan_uyen',
    province_code: 74,
  },
  {
    name: 'Dĩ An City',
    code: 724,
    division_type: 'city',
    codename: 'thanh_pho_di_an',
    province_code: 74,
  },
  {
    name: 'Thuận An City',
    code: 725,
    division_type: 'city',
    codename: 'thanh_pho_thuan_an',
    province_code: 74,
  },
  {
    name: 'Bắc Tân District',
    code: 726,
    division_type: 'district',
    codename: 'huyen_bac_tan_uyen',
    province_code: 74,
  },
  {
    name: 'Biên Hòa City',
    code: 731,
    division_type: 'city',
    codename: 'thanh_pho_bien_hoa',
    province_code: 75,
  },
  {
    name: 'Long Khánh City',
    code: 732,
    division_type: 'city',
    codename: 'thanh_pho_long_khanh',
    province_code: 75,
  },
  {
    name: 'Tân Phú District',
    code: 734,
    division_type: 'district',
    codename: 'huyen_tan_phu',
    province_code: 75,
  },
  {
    name: 'Vĩnh Cửu District',
    code: 735,
    division_type: 'district',
    codename: 'huyen_vinh_cuu',
    province_code: 75,
  },
  {
    name: 'Định Quán District',
    code: 736,
    division_type: 'district',
    codename: 'huyen_dinh_quan',
    province_code: 75,
  },
  {
    name: 'Trảng Bom District',
    code: 737,
    division_type: 'district',
    codename: 'huyen_trang_bom',
    province_code: 75,
  },
  {
    name: 'Thống Nhất District',
    code: 738,
    division_type: 'district',
    codename: 'huyen_thong_nhat',
    province_code: 75,
  },
  {
    name: 'Cẩm Mỹ District',
    code: 739,
    division_type: 'district',
    codename: 'huyen_cam_my',
    province_code: 75,
  },
  {
    name: 'Long Thành District',
    code: 740,
    division_type: 'district',
    codename: 'huyen_long_thanh',
    province_code: 75,
  },
  {
    name: 'Xuân Lộc District',
    code: 741,
    division_type: 'district',
    codename: 'huyen_xuan_loc',
    province_code: 75,
  },
  {
    name: 'Nhơn Trạch District',
    code: 742,
    division_type: 'district',
    codename: 'huyen_nhon_trach',
    province_code: 75,
  },
  {
    name: 'Vũng Tàu City',
    code: 747,
    division_type: 'city',
    codename: 'thanh_pho_vung_tau',
    province_code: 77,
  },
  {
    name: 'Bà Rịa City',
    code: 748,
    division_type: 'city',
    codename: 'thanh_pho_ba_ria',
    province_code: 77,
  },
  {
    name: 'Châu Đức District',
    code: 750,
    division_type: 'district',
    codename: 'huyen_chau_duc',
    province_code: 77,
  },
  {
    name: 'Xuyên Mộc District',
    code: 751,
    division_type: 'district',
    codename: 'huyen_xuyen_moc',
    province_code: 77,
  },
  {
    name: 'Long Điền District',
    code: 752,
    division_type: 'district',
    codename: 'huyen_long_dien',
    province_code: 77,
  },
  {
    name: 'Đất Đỏ District',
    code: 753,
    division_type: 'district',
    codename: 'huyen_dat_do',
    province_code: 77,
  },
  {
    name: 'Phú Mỹ Town',
    code: 754,
    division_type: 'town',
    codename: 'thi_xa_phu_my',
    province_code: 77,
  },
  {
    name: 'Côn Đảo District',
    code: 755,
    division_type: 'district',
    codename: 'huyen_con_dao',
    province_code: 77,
  },
  {
    name: '1  District',
    code: 760,
    division_type: 'district',
    codename: 'quan_1',
    province_code: 79,
  },
  {
    name: '12  District',
    code: 761,
    division_type: 'district',
    codename: 'quan_12',
    province_code: 79,
  },
  {
    name: 'Gò Vấp District',
    code: 764,
    division_type: 'district',
    codename: 'quan_go_vap',
    province_code: 79,
  },
  {
    name: 'Bình Thạnh District',
    code: 765,
    division_type: 'district',
    codename: 'quan_binh_thanh',
    province_code: 79,
  },
  {
    name: 'Tân Bình District',
    code: 766,
    division_type: 'district',
    codename: 'quan_tan_binh',
    province_code: 79,
  },
  {
    name: 'Tân Phú District',
    code: 767,
    division_type: 'district',
    codename: 'quan_tan_phu',
    province_code: 79,
  },
  {
    name: 'Phú Nhuận District',
    code: 768,
    division_type: 'district',
    codename: 'quan_phu_nhuan',
    province_code: 79,
  },
  {
    name: 'Thủ Đức City',
    code: 769,
    division_type: 'city',
    codename: 'thanh_pho_thu_duc',
    province_code: 79,
  },
  {
    name: '3  District',
    code: 770,
    division_type: 'district',
    codename: 'quan_3',
    province_code: 79,
  },
  {
    name: '10  District',
    code: 771,
    division_type: 'district',
    codename: 'quan_10',
    province_code: 79,
  },
  {
    name: '11  District',
    code: 772,
    division_type: 'district',
    codename: 'quan_11',
    province_code: 79,
  },
  {
    name: '4  District',
    code: 773,
    division_type: 'district',
    codename: 'quan_4',
    province_code: 79,
  },
  {
    name: '5  District',
    code: 774,
    division_type: 'district',
    codename: 'quan_5',
    province_code: 79,
  },
  {
    name: '6  District',
    code: 775,
    division_type: 'district',
    codename: 'quan_6',
    province_code: 79,
  },
  {
    name: '8  District',
    code: 776,
    division_type: 'district',
    codename: 'quan_8',
    province_code: 79,
  },
  {
    name: 'Bình Tân District',
    code: 777,
    division_type: 'district',
    codename: 'quan_binh_tan',
    province_code: 79,
  },
  {
    name: '7  District',
    code: 778,
    division_type: 'district',
    codename: 'quan_7',
    province_code: 79,
  },
  {
    name: 'Củ Chi District',
    code: 783,
    division_type: 'district',
    codename: 'huyen_cu_chi',
    province_code: 79,
  },
  {
    name: 'Hóc Môn District',
    code: 784,
    division_type: 'district',
    codename: 'huyen_hoc_mon',
    province_code: 79,
  },
  {
    name: 'Bình Chánh District',
    code: 785,
    division_type: 'district',
    codename: 'huyen_binh_chanh',
    province_code: 79,
  },
  {
    name: 'Nhà Bè District',
    code: 786,
    division_type: 'district',
    codename: 'huyen_nha_be',
    province_code: 79,
  },
  {
    name: 'Cần Giờ District',
    code: 787,
    division_type: 'district',
    codename: 'huyen_can_gio',
    province_code: 79,
  },
  {
    name: 'Tân An City',
    code: 794,
    division_type: 'city',
    codename: 'thanh_pho_tan_an',
    province_code: 80,
  },
  {
    name: 'Kiến Tường Town',
    code: 795,
    division_type: 'town',
    codename: 'thi_xa_kien_tuong',
    province_code: 80,
  },
  {
    name: 'Tân Hưng District',
    code: 796,
    division_type: 'district',
    codename: 'huyen_tan_hung',
    province_code: 80,
  },
  {
    name: 'Vĩnh Hưng District',
    code: 797,
    division_type: 'district',
    codename: 'huyen_vinh_hung',
    province_code: 80,
  },
  {
    name: 'Mộc Hóa District',
    code: 798,
    division_type: 'district',
    codename: 'huyen_moc_hoa',
    province_code: 80,
  },
  {
    name: 'Tân Thạnh District',
    code: 799,
    division_type: 'district',
    codename: 'huyen_tan_thanh',
    province_code: 80,
  },
  {
    name: 'Thạnh Hóa District',
    code: 800,
    division_type: 'district',
    codename: 'huyen_thanh_hoa',
    province_code: 80,
  },
  {
    name: 'Đức Huệ District',
    code: 801,
    division_type: 'district',
    codename: 'huyen_duc_hue',
    province_code: 80,
  },
  {
    name: 'Đức Hòa District',
    code: 802,
    division_type: 'district',
    codename: 'huyen_duc_hoa',
    province_code: 80,
  },
  {
    name: 'Bến Lức District',
    code: 803,
    division_type: 'district',
    codename: 'huyen_ben_luc',
    province_code: 80,
  },
  {
    name: 'Thủ Thừa District',
    code: 804,
    division_type: 'district',
    codename: 'huyen_thu_thua',
    province_code: 80,
  },
  {
    name: 'Tân Trụ District',
    code: 805,
    division_type: 'district',
    codename: 'huyen_tan_tru',
    province_code: 80,
  },
  {
    name: 'Cần Đước District',
    code: 806,
    division_type: 'district',
    codename: 'huyen_can_duoc',
    province_code: 80,
  },
  {
    name: 'Cần Giuộc District',
    code: 807,
    division_type: 'district',
    codename: 'huyen_can_giuoc',
    province_code: 80,
  },
  {
    name: 'Châu Thành District',
    code: 808,
    division_type: 'district',
    codename: 'huyen_chau_thanh',
    province_code: 80,
  },
  {
    name: 'Mỹ Tho City',
    code: 815,
    division_type: 'city',
    codename: 'thanh_pho_my_tho',
    province_code: 82,
  },
  {
    name: 'Gò Công Town',
    code: 816,
    division_type: 'town',
    codename: 'thi_xa_go_cong',
    province_code: 82,
  },
  {
    name: 'Cai Lậy Town',
    code: 817,
    division_type: 'town',
    codename: 'thi_xa_cai_lay',
    province_code: 82,
  },
  {
    name: 'Tân Phước District',
    code: 818,
    division_type: 'district',
    codename: 'huyen_tan_phuoc',
    province_code: 82,
  },
  {
    name: 'Cái Bè District',
    code: 819,
    division_type: 'district',
    codename: 'huyen_cai_be',
    province_code: 82,
  },
  {
    name: 'Cai Lậy District',
    code: 820,
    division_type: 'district',
    codename: 'huyen_cai_lay',
    province_code: 82,
  },
  {
    name: 'Châu Thành District',
    code: 821,
    division_type: 'district',
    codename: 'huyen_chau_thanh',
    province_code: 82,
  },
  {
    name: 'Chợ Gạo District',
    code: 822,
    division_type: 'district',
    codename: 'huyen_cho_gao',
    province_code: 82,
  },
  {
    name: 'Gò Công District',
    code: 823,
    division_type: 'district',
    codename: 'huyen_go_cong_tay',
    province_code: 82,
  },
  {
    name: 'Gò Công District',
    code: 824,
    division_type: 'district',
    codename: 'huyen_go_cong_dong',
    province_code: 82,
  },
  {
    name: 'Tân Phú District',
    code: 825,
    division_type: 'district',
    codename: 'huyen_tan_phu_dong',
    province_code: 82,
  },
  {
    name: 'Bến Tre City',
    code: 829,
    division_type: 'city',
    codename: 'thanh_pho_ben_tre',
    province_code: 83,
  },
  {
    name: 'Châu Thành District',
    code: 831,
    division_type: 'district',
    codename: 'huyen_chau_thanh',
    province_code: 83,
  },
  {
    name: 'Chợ Lách District',
    code: 832,
    division_type: 'district',
    codename: 'huyen_cho_lach',
    province_code: 83,
  },
  {
    name: 'Mỏ Cày District',
    code: 833,
    division_type: 'district',
    codename: 'huyen_mo_cay_nam',
    province_code: 83,
  },
  {
    name: 'Giồng Trôm District',
    code: 834,
    division_type: 'district',
    codename: 'huyen_giong_trom',
    province_code: 83,
  },
  {
    name: 'Bình Đại District',
    code: 835,
    division_type: 'district',
    codename: 'huyen_binh_dai',
    province_code: 83,
  },
  {
    name: 'Ba Tri District',
    code: 836,
    division_type: 'district',
    codename: 'huyen_ba_tri',
    province_code: 83,
  },
  {
    name: 'Thạnh Phú District',
    code: 837,
    division_type: 'district',
    codename: 'huyen_thanh_phu',
    province_code: 83,
  },
  {
    name: 'Mỏ Cày District',
    code: 838,
    division_type: 'district',
    codename: 'huyen_mo_cay_bac',
    province_code: 83,
  },
  {
    name: 'Trà Vinh City',
    code: 842,
    division_type: 'city',
    codename: 'thanh_pho_tra_vinh',
    province_code: 84,
  },
  {
    name: 'Càng Long District',
    code: 844,
    division_type: 'district',
    codename: 'huyen_cang_long',
    province_code: 84,
  },
  {
    name: 'Cầu Kè District',
    code: 845,
    division_type: 'district',
    codename: 'huyen_cau_ke',
    province_code: 84,
  },
  {
    name: 'Tiểu Cần District',
    code: 846,
    division_type: 'district',
    codename: 'huyen_tieu_can',
    province_code: 84,
  },
  {
    name: 'Châu Thành District',
    code: 847,
    division_type: 'district',
    codename: 'huyen_chau_thanh',
    province_code: 84,
  },
  {
    name: 'Cầu Ngang District',
    code: 848,
    division_type: 'district',
    codename: 'huyen_cau_ngang',
    province_code: 84,
  },
  {
    name: 'Trà Cú District',
    code: 849,
    division_type: 'district',
    codename: 'huyen_tra_cu',
    province_code: 84,
  },
  {
    name: 'Duyên Hải District',
    code: 850,
    division_type: 'district',
    codename: 'huyen_duyen_hai',
    province_code: 84,
  },
  {
    name: 'Duyên Hải Town',
    code: 851,
    division_type: 'town',
    codename: 'thi_xa_duyen_hai',
    province_code: 84,
  },
  {
    name: 'Vĩnh Long City',
    code: 855,
    division_type: 'city',
    codename: 'thanh_pho_vinh_long',
    province_code: 86,
  },
  {
    name: 'Long Hồ District',
    code: 857,
    division_type: 'district',
    codename: 'huyen_long_ho',
    province_code: 86,
  },
  {
    name: 'Mang Thít District',
    code: 858,
    division_type: 'district',
    codename: 'huyen_mang_thit',
    province_code: 86,
  },
  {
    name: 'Vũng Liêm District',
    code: 859,
    division_type: 'district',
    codename: 'huyen_vung_liem',
    province_code: 86,
  },
  {
    name: 'Tam Bình District',
    code: 860,
    division_type: 'district',
    codename: 'huyen_tam_binh',
    province_code: 86,
  },
  {
    name: 'Bình Minh Town',
    code: 861,
    division_type: 'town',
    codename: 'thi_xa_binh_minh',
    province_code: 86,
  },
  {
    name: 'Trà Ôn District',
    code: 862,
    division_type: 'district',
    codename: 'huyen_tra_on',
    province_code: 86,
  },
  {
    name: 'Bình Tân District',
    code: 863,
    division_type: 'district',
    codename: 'huyen_binh_tan',
    province_code: 86,
  },
  {
    name: 'Cao Lãnh City',
    code: 866,
    division_type: 'city',
    codename: 'thanh_pho_cao_lanh',
    province_code: 87,
  },
  {
    name: 'Sa Đéc City',
    code: 867,
    division_type: 'city',
    codename: 'thanh_pho_sa_dec',
    province_code: 87,
  },
  {
    name: 'Hồng Ngự City',
    code: 868,
    division_type: 'city',
    codename: 'thanh_pho_hong_ngu',
    province_code: 87,
  },
  {
    name: 'Tân Hồng District',
    code: 869,
    division_type: 'district',
    codename: 'huyen_tan_hong',
    province_code: 87,
  },
  {
    name: 'Hồng Ngự District',
    code: 870,
    division_type: 'district',
    codename: 'huyen_hong_ngu',
    province_code: 87,
  },
  {
    name: 'Tam Nông District',
    code: 871,
    division_type: 'district',
    codename: 'huyen_tam_nong',
    province_code: 87,
  },
  {
    name: 'Tháp Mười District',
    code: 872,
    division_type: 'district',
    codename: 'huyen_thap_muoi',
    province_code: 87,
  },
  {
    name: 'Cao Lãnh District',
    code: 873,
    division_type: 'district',
    codename: 'huyen_cao_lanh',
    province_code: 87,
  },
  {
    name: 'Thanh Bình District',
    code: 874,
    division_type: 'district',
    codename: 'huyen_thanh_binh',
    province_code: 87,
  },
  {
    name: 'Lấp Vò District',
    code: 875,
    division_type: 'district',
    codename: 'huyen_lap_vo',
    province_code: 87,
  },
  {
    name: 'Lai Vung District',
    code: 876,
    division_type: 'district',
    codename: 'huyen_lai_vung',
    province_code: 87,
  },
  {
    name: 'Châu Thành District',
    code: 877,
    division_type: 'district',
    codename: 'huyen_chau_thanh',
    province_code: 87,
  },
  {
    name: 'Long Xuyên City',
    code: 883,
    division_type: 'city',
    codename: 'thanh_pho_long_xuyen',
    province_code: 89,
  },
  {
    name: 'Châu Đốc City',
    code: 884,
    division_type: 'city',
    codename: 'thanh_pho_chau_doc',
    province_code: 89,
  },
  {
    name: 'An Phú District',
    code: 886,
    division_type: 'district',
    codename: 'huyen_an_phu',
    province_code: 89,
  },
  {
    name: 'Tân Châu Town',
    code: 887,
    division_type: 'town',
    codename: 'thi_xa_tan_chau',
    province_code: 89,
  },
  {
    name: 'Phú Tân District',
    code: 888,
    division_type: 'district',
    codename: 'huyen_phu_tan',
    province_code: 89,
  },
  {
    name: 'Châu Phú District',
    code: 889,
    division_type: 'district',
    codename: 'huyen_chau_phu',
    province_code: 89,
  },
  {
    name: 'Tịnh Biên Town',
    code: 890,
    division_type: 'town',
    codename: 'thi_xa_tinh_bien',
    province_code: 89,
  },
  {
    name: 'Tri Tôn District',
    code: 891,
    division_type: 'district',
    codename: 'huyen_tri_ton',
    province_code: 89,
  },
  {
    name: 'Châu Thành District',
    code: 892,
    division_type: 'district',
    codename: 'huyen_chau_thanh',
    province_code: 89,
  },
  {
    name: 'Chợ Mới District',
    code: 893,
    division_type: 'district',
    codename: 'huyen_cho_moi',
    province_code: 89,
  },
  {
    name: 'Thoại Sơn District',
    code: 894,
    division_type: 'district',
    codename: 'huyen_thoai_son',
    province_code: 89,
  },
  {
    name: 'Rạch Giá City',
    code: 899,
    division_type: 'city',
    codename: 'thanh_pho_rach_gia',
    province_code: 91,
  },
  {
    name: 'Hà Tiên City',
    code: 900,
    division_type: 'city',
    codename: 'thanh_pho_ha_tien',
    province_code: 91,
  },
  {
    name: 'Kiên Lương District',
    code: 902,
    division_type: 'district',
    codename: 'huyen_kien_luong',
    province_code: 91,
  },
  {
    name: 'Hòn Đất District',
    code: 903,
    division_type: 'district',
    codename: 'huyen_hon_dat',
    province_code: 91,
  },
  {
    name: 'Tân Hiệp District',
    code: 904,
    division_type: 'district',
    codename: 'huyen_tan_hiep',
    province_code: 91,
  },
  {
    name: 'Châu Thành District',
    code: 905,
    division_type: 'district',
    codename: 'huyen_chau_thanh',
    province_code: 91,
  },
  {
    name: 'Giồng Riềng District',
    code: 906,
    division_type: 'district',
    codename: 'huyen_giong_rieng',
    province_code: 91,
  },
  {
    name: 'Gò Quao District',
    code: 907,
    division_type: 'district',
    codename: 'huyen_go_quao',
    province_code: 91,
  },
  {
    name: 'An Biên District',
    code: 908,
    division_type: 'district',
    codename: 'huyen_an_bien',
    province_code: 91,
  },
  {
    name: 'An Minh District',
    code: 909,
    division_type: 'district',
    codename: 'huyen_an_minh',
    province_code: 91,
  },
  {
    name: 'Vĩnh Thuận District',
    code: 910,
    division_type: 'district',
    codename: 'huyen_vinh_thuan',
    province_code: 91,
  },
  {
    name: 'Phú Quốc City',
    code: 911,
    division_type: 'city',
    codename: 'thanh_pho_phu_quoc',
    province_code: 91,
  },
  {
    name: 'Kiên Hải District',
    code: 912,
    division_type: 'district',
    codename: 'huyen_kien_hai',
    province_code: 91,
  },
  {
    name: 'U Minh District',
    code: 913,
    division_type: 'district',
    codename: 'huyen_u_minh_thuong',
    province_code: 91,
  },
  {
    name: 'Giang Thành District',
    code: 914,
    division_type: 'district',
    codename: 'huyen_giang_thanh',
    province_code: 91,
  },
  {
    name: 'Ninh Kiều District',
    code: 916,
    division_type: 'district',
    codename: 'quan_ninh_kieu',
    province_code: 92,
  },
  {
    name: 'Ô Môn District',
    code: 917,
    division_type: 'district',
    codename: 'quan_o_mon',
    province_code: 92,
  },
  {
    name: 'Bình Thuỷ District',
    code: 918,
    division_type: 'district',
    codename: 'quan_binh_thuy',
    province_code: 92,
  },
  {
    name: 'Cái Răng District',
    code: 919,
    division_type: 'district',
    codename: 'quan_cai_rang',
    province_code: 92,
  },
  {
    name: 'Thốt Nốt District',
    code: 923,
    division_type: 'district',
    codename: 'quan_thot_not',
    province_code: 92,
  },
  {
    name: 'Vĩnh Thạnh District',
    code: 924,
    division_type: 'district',
    codename: 'huyen_vinh_thanh',
    province_code: 92,
  },
  {
    name: 'Cờ Đỏ District',
    code: 925,
    division_type: 'district',
    codename: 'huyen_co_do',
    province_code: 92,
  },
  {
    name: 'Phong Điền District',
    code: 926,
    division_type: 'district',
    codename: 'huyen_phong_dien',
    province_code: 92,
  },
  {
    name: 'Thới Lai District',
    code: 927,
    division_type: 'district',
    codename: 'huyen_thoi_lai',
    province_code: 92,
  },
  {
    name: 'Vị Thanh City',
    code: 930,
    division_type: 'city',
    codename: 'thanh_pho_vi_thanh',
    province_code: 93,
  },
  {
    name: 'Ngã Bảy City',
    code: 931,
    division_type: 'city',
    codename: 'thanh_pho_nga_bay',
    province_code: 93,
  },
  {
    name: 'Châu Thành District',
    code: 932,
    division_type: 'district',
    codename: 'huyen_chau_thanh_a',
    province_code: 93,
  },
  {
    name: 'Châu Thành District',
    code: 933,
    division_type: 'district',
    codename: 'huyen_chau_thanh',
    province_code: 93,
  },
  {
    name: 'Phụng Hiệp District',
    code: 934,
    division_type: 'district',
    codename: 'huyen_phung_hiep',
    province_code: 93,
  },
  {
    name: 'Vị Thuỷ District',
    code: 935,
    division_type: 'district',
    codename: 'huyen_vi_thuy',
    province_code: 93,
  },
  {
    name: 'Long Mỹ District',
    code: 936,
    division_type: 'district',
    codename: 'huyen_long_my',
    province_code: 93,
  },
  {
    name: 'Long Mỹ Town',
    code: 937,
    division_type: 'town',
    codename: 'thi_xa_long_my',
    province_code: 93,
  },
  {
    name: 'Sóc Trăng City',
    code: 941,
    division_type: 'city',
    codename: 'thanh_pho_soc_trang',
    province_code: 94,
  },
  {
    name: 'Châu Thành District',
    code: 942,
    division_type: 'district',
    codename: 'huyen_chau_thanh',
    province_code: 94,
  },
  {
    name: 'Kế Sách District',
    code: 943,
    division_type: 'district',
    codename: 'huyen_ke_sach',
    province_code: 94,
  },
  {
    name: 'Mỹ Tú District',
    code: 944,
    division_type: 'district',
    codename: 'huyen_my_tu',
    province_code: 94,
  },
  {
    name: 'Cù Lao District',
    code: 945,
    division_type: 'district',
    codename: 'huyen_cu_lao_dung',
    province_code: 94,
  },
  {
    name: 'Long Phú District',
    code: 946,
    division_type: 'district',
    codename: 'huyen_long_phu',
    province_code: 94,
  },
  {
    name: 'Mỹ Xuyên District',
    code: 947,
    division_type: 'district',
    codename: 'huyen_my_xuyen',
    province_code: 94,
  },
  {
    name: 'Ngã Năm Town',
    code: 948,
    division_type: 'town',
    codename: 'thi_xa_nga_nam',
    province_code: 94,
  },
  {
    name: 'Thạnh Trị District',
    code: 949,
    division_type: 'district',
    codename: 'huyen_thanh_tri',
    province_code: 94,
  },
  {
    name: 'Vĩnh Châu Town',
    code: 950,
    division_type: 'town',
    codename: 'thi_xa_vinh_chau',
    province_code: 94,
  },
  {
    name: 'Trần Đề District',
    code: 951,
    division_type: 'district',
    codename: 'huyen_tran_de',
    province_code: 94,
  },
  {
    name: 'Bạc Liêu City',
    code: 954,
    division_type: 'city',
    codename: 'thanh_pho_bac_lieu',
    province_code: 95,
  },
  {
    name: 'Hồng Dân District',
    code: 956,
    division_type: 'district',
    codename: 'huyen_hong_dan',
    province_code: 95,
  },
  {
    name: 'Phước Long District',
    code: 957,
    division_type: 'district',
    codename: 'huyen_phuoc_long',
    province_code: 95,
  },
  {
    name: 'Vĩnh Lợi District',
    code: 958,
    division_type: 'district',
    codename: 'huyen_vinh_loi',
    province_code: 95,
  },
  {
    name: 'Giá Rai Town',
    code: 959,
    division_type: 'town',
    codename: 'thi_xa_gia_rai',
    province_code: 95,
  },
  {
    name: 'Đông Hải District',
    code: 960,
    division_type: 'district',
    codename: 'huyen_dong_hai',
    province_code: 95,
  },
  {
    name: 'Hoà Bình District',
    code: 961,
    division_type: 'district',
    codename: 'huyen_hoa_binh',
    province_code: 95,
  },
  {
    name: 'Cà Mau City',
    code: 964,
    division_type: 'city',
    codename: 'thanh_pho_ca_mau',
    province_code: 96,
  },
  {
    name: 'U Minh District',
    code: 966,
    division_type: 'district',
    codename: 'huyen_u_minh',
    province_code: 96,
  },
  {
    name: 'Thới Bình District',
    code: 967,
    division_type: 'district',
    codename: 'huyen_thoi_binh',
    province_code: 96,
  },
  {
    name: 'Trần Văn District',
    code: 968,
    division_type: 'district',
    codename: 'huyen_tran_van_thoi',
    province_code: 96,
  },
  {
    name: 'Cái Nước District',
    code: 969,
    division_type: 'district',
    codename: 'huyen_cai_nuoc',
    province_code: 96,
  },
  {
    name: 'Đầm Dơi District',
    code: 970,
    division_type: 'district',
    codename: 'huyen_dam_doi',
    province_code: 96,
  },
  {
    name: 'Năm Căn District',
    code: 971,
    division_type: 'district',
    codename: 'huyen_nam_can',
    province_code: 96,
  },
  {
    name: 'Phú Tân District',
    code: 972,
    division_type: 'district',
    codename: 'huyen_phu_tan',
    province_code: 96,
  },
  {
    name: 'Ngọc Hiển District',
    code: 973,
    division_type: 'district',
    codename: 'huyen_ngoc_hien',
    province_code: 96,
  },
];

const convertItems = [...items].map(({ name, code, province_code }) => ({
  name,
  code,
  cityCode: province_code,
}));

const districts_en = [...convertItems].map((item, idx) => ({
  id: `DISTRICT_EN_${idx}`,
  name: item.name,
  code: item.code,
  cityCode: item.cityCode,
  langCode: ELang.EN,
  createdAt: new Date(),
  updatedAt: new Date(),
}));

export default districts_en;
