import { District } from '@prisma/client';
import { ELang } from 'src/common/enum/base';

const items = [
  // 1
  {
    name: 'Ba Dinh District',
    code: 1,
    division_type: 'District',
    codename: 'quan_ba_dinh',
    province_code: 1,
  },
  {
    name: 'Hoan Kiem District',
    code: 2,
    division_type: 'District',
    codename: 'quan_hoan_kiem',
    province_code: 1,
  },
  {
    name: 'Tay Ho District',
    code: 3,
    division_type: 'District',
    codename: 'quan_tay_ho',
    province_code: 1,
  },
  {
    name: 'Long Bien District',
    code: 4,
    division_type: 'District',
    codename: 'quan_long_bien',
    province_code: 1,
  },
  {
    name: 'Cau Giay District',
    code: 5,
    division_type: 'District',
    codename: 'quan_cau_giay',
    province_code: 1,
  },
  {
    name: 'Dong Da District',
    code: 6,
    division_type: 'District',
    codename: 'quan_dong_da',
    province_code: 1,
  },
  {
    name: 'Hai Ba Trung District',
    code: 7,
    division_type: 'District',
    codename: 'quan_hai_ba_trung',
    province_code: 1,
  },
  {
    name: 'Hoang Mai District',
    code: 8,
    division_type: 'District',
    codename: 'quan_hoang_mai',
    province_code: 1,
  },
  {
    name: 'Thanh Xuan District',
    code: 9,
    division_type: 'District',
    codename: 'quan_thanh_xuan',
    province_code: 1,
  },
  {
    name: 'Soc Son District',
    code: 16,
    division_type: 'District',
    codename: 'huyen_soc_son',
    province_code: 1,
  },
  {
    name: 'Dong Anh District',
    code: 17,
    division_type: 'District',
    codename: 'huyen_dong_anh',
    province_code: 1,
  },
  {
    name: 'Gia Lam District',
    code: 18,
    division_type: 'District',
    codename: 'huyen_gia_lam',
    province_code: 1,
  },
  {
    name: 'Nam Tu Liem District',
    code: 19,
    division_type: 'District',
    codename: 'quan_nam_tu_liem',
    province_code: 1,
  },
  {
    name: 'Thanh Tri District',
    code: 20,
    division_type: 'District',
    codename: 'huyen_thanh_tri',
    province_code: 1,
  },
  {
    name: 'Bac Tu Liem District',
    code: 21,
    division_type: 'District',
    codename: 'quan_bac_tu_liem',
    province_code: 1,
  },
  {
    name: 'Me Linh District',
    code: 250,
    division_type: 'District',
    codename: 'huyen_me_linh',
    province_code: 1,
  },
  {
    name: 'Ha Dong District',
    code: 268,
    division_type: 'District',
    codename: 'quan_ha_dong',
    province_code: 1,
  },
  {
    name: 'Son Tay Town',
    code: 269,
    division_type: 'Town',
    codename: 'thi_xa_son_tay',
    province_code: 1,
  },
  {
    name: 'Ba Vi District',
    code: 271,
    division_type: 'District',
    codename: 'huyen_ba_vi',
    province_code: 1,
  },
  {
    name: 'Phuc Tho District',
    code: 272,
    division_type: 'District',
    codename: 'huyen_phuc_tho',
    province_code: 1,
  },
  {
    name: 'Dan Phuong District',
    code: 273,
    division_type: 'District',
    codename: 'huyen_dan_phuong',
    province_code: 1,
  },
  {
    name: 'Hoai Duc District',
    code: 274,
    division_type: 'District',
    codename: 'huyen_hoai_duc',
    province_code: 1,
  },
  {
    name: 'Quoc Oai District',
    code: 275,
    division_type: 'District',
    codename: 'huyen_quoc_oai',
    province_code: 1,
  },
  {
    name: 'Thach That District',
    code: 276,
    division_type: 'District',
    codename: 'huyen_thach_that',
    province_code: 1,
  },
  {
    name: 'Chuong My District',
    code: 277,
    division_type: 'District',
    codename: 'huyen_chuong_my',
    province_code: 1,
  },
  {
    name: 'Thanh Oai District',
    code: 278,
    division_type: 'District',
    codename: 'huyen_thanh_oai',
    province_code: 1,
  },
  {
    name: 'Thuong Tin District',
    code: 279,
    division_type: 'District',
    codename: 'huyen_thuong_tin',
    province_code: 1,
  },
  {
    name: 'Phu Xuyen District',
    code: 280,
    division_type: 'District',
    codename: 'huyen_phu_xuyen',
    province_code: 1,
  },
  {
    name: 'Ung Hoa District',
    code: 281,
    division_type: 'District',
    codename: 'huyen_ung_hoa',
    province_code: 1,
  },
  {
    name: 'My Duc District',
    code: 282,
    division_type: 'District',
    codename: 'huyen_my_duc',
    province_code: 1,
  },
  // 2
  {
    name: 'Ha Giang City',
    code: 24,
    division_type: 'City',
    codename: 'thanh_pho_ha_giang',
    province_code: 2,
  },
  {
    name: 'Dong Van District',
    code: 26,
    division_type: 'District',
    codename: 'huyen_dong_van',
    province_code: 2,
  },
  {
    name: 'Meo Vac District',
    code: 27,
    division_type: 'District',
    codename: 'huyen_meo_vac',
    province_code: 2,
  },
  {
    name: 'Yen Minh District',
    code: 28,
    division_type: 'District',
    codename: 'huyen_yen_minh',
    province_code: 2,
  },
  {
    name: 'Quan Ba District',
    code: 29,
    division_type: 'District',
    codename: 'huyen_quan_ba',
    province_code: 2,
  },
  {
    name: 'Vi Xuyen District',
    code: 30,
    division_type: 'District',
    codename: 'huyen_vi_xuyen',
    province_code: 2,
  },
  {
    name: 'Bac Me District',
    code: 31,
    division_type: 'District',
    codename: 'huyen_bac_me',
    province_code: 2,
  },
  {
    name: 'Hoang Su Phi District',
    code: 32,
    division_type: 'District',
    codename: 'huyen_hoang_su_phi',
    province_code: 2,
  },
  {
    name: 'Xin Man District',
    code: 33,
    division_type: 'District',
    codename: 'huyen_xin_man',
    province_code: 2,
  },
  {
    name: 'Bac Quang District',
    code: 34,
    division_type: 'District',
    codename: 'huyen_bac_quang',
    province_code: 2,
  },
  {
    name: 'Quang Binh District',
    code: 35,
    division_type: 'District',
    codename: 'huyen_quang_binh',
    province_code: 2,
  },
  // 4
  {
    name: 'Cao Bang City',
    code: 40,
    division_type: 'City',
    codename: 'thanh_pho_cao_bang',
    province_code: 4,
  },
  {
    name: 'Bao Lam District',
    code: 42,
    division_type: 'District',
    codename: 'huyen_bao_lam',
    province_code: 4,
  },
  {
    name: 'Bao Lac District',
    code: 43,
    division_type: 'District',
    codename: 'huyen_bao_lac',
    province_code: 4,
  },
  {
    name: 'Ha Quang District',
    code: 45,
    division_type: 'District',
    codename: 'huyen_ha_quang',
    province_code: 4,
  },
  {
    name: 'Trung Khanh District',
    code: 47,
    division_type: 'District',
    codename: 'huyen_trung_khanh',
    province_code: 4,
  },
  {
    name: 'Ha Lang District',
    code: 48,
    division_type: 'District',
    codename: 'huyen_ha_lang',
    province_code: 4,
  },
  {
    name: 'Quang Hoa District',
    code: 49,
    division_type: 'District',
    codename: 'huyen_quang_hoa',
    province_code: 4,
  },
  {
    name: 'Hoa An District',
    code: 51,
    division_type: 'District',
    codename: 'huyen_hoa_an',
    province_code: 4,
  },
  {
    name: 'Nguyen Binh District',
    code: 52,
    division_type: 'District',
    codename: 'huyen_nguyen_binh',
    province_code: 4,
  },
  {
    name: 'Thach An District',
    code: 53,
    division_type: 'District',
    codename: 'huyen_thach_an',
    province_code: 4,
  },
  // 6
  {
    name: 'Bac Kan City',
    code: 58,
    division_type: 'City',
    codename: 'thanh_pho_bac_kan',
    province_code: 6,
  },
  {
    name: 'Pac Nam District',
    code: 60,
    division_type: 'District',
    codename: 'huyen_pac_nam',
    province_code: 6,
  },
  {
    name: 'Ba Be District',
    code: 61,
    division_type: 'District',
    codename: 'huyen_ba_be',
    province_code: 6,
  },
  {
    name: 'Ngan Son District',
    code: 62,
    division_type: 'District',
    codename: 'huyen_ngan_son',
    province_code: 6,
  },
  {
    name: 'Bach Thong District',
    code: 63,
    division_type: 'District',
    codename: 'huyen_bach_thong',
    province_code: 6,
  },
  {
    name: 'Cho Don District',
    code: 64,
    division_type: 'District',
    codename: 'huyen_cho_don',
    province_code: 6,
  },
  {
    name: 'Cho Moi District',
    code: 65,
    division_type: 'District',
    codename: 'huyen_cho_moi',
    province_code: 6,
  },
  {
    name: 'Na Ri District',
    code: 66,
    division_type: 'District',
    codename: 'huyen_na_ri',
    province_code: 6,
  },
  // 8
  {
    name: 'Tuyen Quang City',
    code: 70,
    division_type: 'City',
    codename: 'thanh_pho_tuyen_quang',
    province_code: 8,
  },
  {
    name: 'Lam Binh District',
    code: 71,
    division_type: 'District',
    codename: 'huyen_lam_binh',
    province_code: 8,
  },
  {
    name: 'Na Hang District',
    code: 72,
    division_type: 'District',
    codename: 'huyen_na_hang',
    province_code: 8,
  },
  {
    name: 'Chiem Hoa District',
    code: 73,
    division_type: 'District',
    codename: 'huyen_chiem_hoa',
    province_code: 8,
  },
  {
    name: 'Ham Yen District',
    code: 74,
    division_type: 'District',
    codename: 'huyen_ham_yen',
    province_code: 8,
  },
  {
    name: 'Yen Son District',
    code: 75,
    division_type: 'District',
    codename: 'huyen_yen_son',
    province_code: 8,
  },
  {
    name: 'Son Duong District',
    code: 76,
    division_type: 'District',
    codename: 'huyen_son_duong',
    province_code: 8,
  },
  // 10
  {
    name: 'Lao Cai City',
    code: 80,
    division_type: 'City',
    codename: 'thanh_pho_lao_cai',
    province_code: 10,
  },
  {
    name: 'Bat Xat District',
    code: 82,
    division_type: 'District',
    codename: 'huyen_bat_xat',
    province_code: 10,
  },
  {
    name: 'Muong Khuong District',
    code: 83,
    division_type: 'District',
    codename: 'huyen_muong_khuong',
    province_code: 10,
  },
  {
    name: 'Si Ma Cai District',
    code: 84,
    division_type: 'District',
    codename: 'huyen_si_ma_cai',
    province_code: 10,
  },
  {
    name: 'Bac Ha District',
    code: 85,
    division_type: 'District',
    codename: 'huyen_bac_ha',
    province_code: 10,
  },
  {
    name: 'Bao Thang District',
    code: 86,
    division_type: 'District',
    codename: 'huyen_bao_thang',
    province_code: 10,
  },
  {
    name: 'Bao Yen District',
    code: 87,
    division_type: 'District',
    codename: 'huyen_bao_yen',
    province_code: 10,
  },
  {
    name: 'Sa Pa Town',
    code: 88,
    division_type: 'Town',
    codename: 'thi_xa_sa_pa',
    province_code: 10,
  },
  {
    name: 'Van Ban District',
    code: 89,
    division_type: 'District',
    codename: 'huyen_van_ban',
    province_code: 10,
  },
  // 11
  {
    name: 'Dien Bien Phu City',
    code: 94,
    division_type: 'City',
    codename: 'thanh_pho_dien_bien_phu',
    province_code: 11,
  },
  {
    name: 'Muong Lay Town',
    code: 95,
    division_type: 'Town',
    codename: 'thi_xa_muong_lay',
    province_code: 11,
  },
  {
    name: 'Muong Nhe District',
    code: 96,
    division_type: 'District',
    codename: 'huyen_muong_nhe',
    province_code: 11,
  },
  {
    name: 'Muong Cha District',
    code: 97,
    division_type: 'District',
    codename: 'huyen_muong_cha',
    province_code: 11,
  },
  {
    name: 'Tua Chua District',
    code: 98,
    division_type: 'District',
    codename: 'huyen_tua_chua',
    province_code: 11,
  },
  {
    name: 'Tuan Giao District',
    code: 99,
    division_type: 'District',
    codename: 'huyen_tuan_giao',
    province_code: 11,
  },
  {
    name: 'Dien Bien District',
    code: 100,
    division_type: 'District',
    codename: 'huyen_dien_bien',
    province_code: 11,
  },
  {
    name: 'Dien Bien Dong District',
    code: 101,
    division_type: 'District',
    codename: 'huyen_dien_bien_dong',
    province_code: 11,
  },
  {
    name: 'Muong Ang District',
    code: 102,
    division_type: 'District',
    codename: 'huyen_muong_ang',
    province_code: 11,
  },
  {
    name: 'Nam Po District',
    code: 103,
    division_type: 'District',
    codename: 'huyen_nam_po',
    province_code: 11,
  },
  // 12
  {
    name: 'Lai Chau City',
    code: 105,
    division_type: 'City',
    codename: 'thanh_pho_lai_chau',
    province_code: 12,
  },
  {
    name: 'Tam Duong District',
    code: 106,
    division_type: 'District',
    codename: 'huyen_tam_duong',
    province_code: 12,
  },
  {
    name: 'Muong Te District',
    code: 107,
    division_type: 'District',
    codename: 'huyen_muong_te',
    province_code: 12,
  },
  {
    name: 'Sin Ho District',
    code: 108,
    division_type: 'District',
    codename: 'huyen_sin_ho',
    province_code: 12,
  },
  {
    name: 'Phong Tho District',
    code: 109,
    division_type: 'District',
    codename: 'huyen_phong_tho',
    province_code: 12,
  },
  {
    name: 'Than Uyen District',
    code: 110,
    division_type: 'District',
    codename: 'huyen_than_uyen',
    province_code: 12,
  },
  {
    name: 'Tan Uyen District',
    code: 111,
    division_type: 'District',
    codename: 'huyen_tan_uyen',
    province_code: 12,
  },
  {
    name: 'Nam Nhun District',
    code: 112,
    division_type: 'District',
    codename: 'huyen_nam_nhun',
    province_code: 12,
  },
  // 14
  {
    name: 'Son La City',
    code: 116,
    division_type: 'City',
    codename: 'thanh_pho_son_la',
    province_code: 14,
  },
  {
    name: 'Quynh Nhai District',
    code: 118,
    division_type: 'District',
    codename: 'huyen_quynh_nhai',
    province_code: 14,
  },
  {
    name: 'Thuan Chau District',
    code: 119,
    division_type: 'District',
    codename: 'huyen_thuan_chau',
    province_code: 14,
  },
  {
    name: 'Muong La District',
    code: 120,
    division_type: 'District',
    codename: 'huyen_muong_la',
    province_code: 14,
  },
  {
    name: 'Bac Yen District',
    code: 121,
    division_type: 'District',
    codename: 'huyen_bac_yen',
    province_code: 14,
  },
  {
    name: 'Phu Yen District',
    code: 122,
    division_type: 'District',
    codename: 'huyen_phu_yen',
    province_code: 14,
  },
  {
    name: 'Moc Chau District',
    code: 123,
    division_type: 'District',
    codename: 'huyen_moc_chau',
    province_code: 14,
  },
  {
    name: 'Yen Chau District',
    code: 124,
    division_type: 'District',
    codename: 'huyen_yen_chau',
    province_code: 14,
  },
  {
    name: 'Mai Son District',
    code: 125,
    division_type: 'District',
    codename: 'huyen_mai_son',
    province_code: 14,
  },
  {
    name: 'Song Ma District',
    code: 126,
    division_type: 'District',
    codename: 'huyen_song_ma',
    province_code: 14,
  },
  {
    name: 'Sop Cop District',
    code: 127,
    division_type: 'District',
    codename: 'huyen_sop_cop',
    province_code: 14,
  },
  {
    name: 'Van Ho District',
    code: 128,
    division_type: 'District',
    codename: 'huyen_van_ho',
    province_code: 14,
  },
  // 15
  {
    name: 'Yen Bai City',
    code: 132,
    division_type: 'City',
    codename: 'thanh_pho_yen_bai',
    province_code: 15,
  },
  {
    name: 'Nghia Lo Town',
    code: 133,
    division_type: 'Town',
    codename: 'thi_xa_nghia_lo',
    province_code: 15,
  },
  {
    name: 'Luc Yen District',
    code: 135,
    division_type: 'District',
    codename: 'huyen_luc_yen',
    province_code: 15,
  },
  {
    name: 'Van Yen District',
    code: 136,
    division_type: 'District',
    codename: 'huyen_van_yen',
    province_code: 15,
  },
  {
    name: 'Mu Cang Chai District',
    code: 137,
    division_type: 'District',
    codename: 'huyen_mu_cang_chai',
    province_code: 15,
  },
  {
    name: 'Tran Yen District',
    code: 138,
    division_type: 'District',
    codename: 'huyen_tran_yen',
    province_code: 15,
  },
  {
    name: 'Tram Tau District',
    code: 139,
    division_type: 'District',
    codename: 'huyen_tram_tau',
    province_code: 15,
  },
  {
    name: 'Van Chan District',
    code: 140,
    division_type: 'District',
    codename: 'huyen_van_chan',
    province_code: 15,
  },
  {
    name: 'Yen Binh District',
    code: 141,
    division_type: 'District',
    codename: 'huyen_yen_binh',
    province_code: 15,
  },
  {
    name: 'Hoa Binh City',
    code: 148,
    division_type: 'City',
    codename: 'thanh_pho_hoa_binh',
    province_code: 17,
  },
  {
    name: 'Da Bac District',
    code: 150,
    division_type: 'District',
    codename: 'huyen_da_bac',
    province_code: 17,
  },
  {
    name: 'Luong Son District',
    code: 152,
    division_type: 'District',
    codename: 'huyen_luong_son',
    province_code: 17,
  },
  {
    name: 'Kim Boi District',
    code: 153,
    division_type: 'District',
    codename: 'huyen_kim_boi',
    province_code: 17,
  },
  {
    name: 'Cao Phong District',
    code: 154,
    division_type: 'District',
    codename: 'huyen_cao_phong',
    province_code: 17,
  },
  {
    name: 'Tan Lac District',
    code: 155,
    division_type: 'District',
    codename: 'huyen_tan_lac',
    province_code: 17,
  },
  {
    name: 'Mai Chau District',
    code: 156,
    division_type: 'District',
    codename: 'huyen_mai_chau',
    province_code: 17,
  },
  {
    name: 'Lac Son District',
    code: 157,
    division_type: 'District',
    codename: 'huyen_lac_son',
    province_code: 17,
  },
  {
    name: 'Yen Thuy District',
    code: 158,
    division_type: 'District',
    codename: 'huyen_yen_thuy',
    province_code: 17,
  },
  {
    name: 'Lac Thuy District',
    code: 159,
    division_type: 'District',
    codename: 'huyen_lac_thuy',
    province_code: 17,
  },
  {
    name: 'Thai Nguyen City',
    code: 164,
    division_type: 'City',
    codename: 'thanh_pho_thai_nguyen',
    province_code: 19,
  },
  {
    name: 'Song Cong City',
    code: 165,
    division_type: 'City',
    codename: 'thanh_pho_song_cong',
    province_code: 19,
  },
  {
    name: 'Dinh Hoa District',
    code: 167,
    division_type: 'District',
    codename: 'huyen_dinh_hoa',
    province_code: 19,
  },
  {
    name: 'Phu Luong District',
    code: 168,
    division_type: 'District',
    codename: 'huyen_phu_luong',
    province_code: 19,
  },
  {
    name: 'Dong Hy District',
    code: 169,
    division_type: 'District',
    codename: 'huyen_dong_hy',
    province_code: 19,
  },
  {
    name: 'Vo Nhai District',
    code: 170,
    division_type: 'District',
    codename: 'huyen_vo_nhai',
    province_code: 19,
  },
  {
    name: 'Dai Tu District',
    code: 171,
    division_type: 'District',
    codename: 'huyen_dai_tu',
    province_code: 19,
  },
  {
    name: 'Pho Yen City',
    code: 172,
    division_type: 'City',
    codename: 'thanh_pho_pho_yen',
    province_code: 19,
  },
  {
    name: 'Phu Binh District',
    code: 173,
    division_type: 'District',
    codename: 'huyen_phu_binh',
    province_code: 19,
  },
  {
    name: 'Lang Son City',
    code: 178,
    division_type: 'City',
    codename: 'thanh_pho_lang_son',
    province_code: 20,
  },
  {
    name: 'Trang Dinh District',
    code: 180,
    division_type: 'District',
    codename: 'huyen_trang_dinh',
    province_code: 20,
  },
  {
    name: 'Binh Gia District',
    code: 181,
    division_type: 'District',
    codename: 'huyen_binh_gia',
    province_code: 20,
  },
  {
    name: 'Van Lang District',
    code: 182,
    division_type: 'District',
    codename: 'huyen_van_lang',
    province_code: 20,
  },
  {
    name: 'Cao Loc District',
    code: 183,
    division_type: 'District',
    codename: 'huyen_cao_loc',
    province_code: 20,
  },
  {
    name: 'Van Quan District',
    code: 184,
    division_type: 'District',
    codename: 'huyen_van_quan',
    province_code: 20,
  },
  {
    name: 'Bac Son District',
    code: 185,
    division_type: 'District',
    codename: 'huyen_bac_son',
    province_code: 20,
  },
  {
    name: 'Huu Lung District',
    code: 186,
    division_type: 'District',
    codename: 'huyen_huu_lung',
    province_code: 20,
  },
  {
    name: 'Chi Lang District',
    code: 187,
    division_type: 'District',
    codename: 'huyen_chi_lang',
    province_code: 20,
  },
  {
    name: 'Loc Binh District',
    code: 188,
    division_type: 'District',
    codename: 'huyen_loc_binh',
    province_code: 20,
  },
  {
    name: 'Dinh Lap District',
    code: 189,
    division_type: 'District',
    codename: 'huyen_dinh_lap',
    province_code: 20,
  },
  {
    name: 'Hai Long City',
    code: 193,
    division_type: 'City',
    codename: 'thanh_pho_ha_long',
    province_code: 22,
  },
  {
    name: 'Mong Cai City',
    code: 194,
    division_type: 'City',
    codename: 'thanh_pho_mong_cai',
    province_code: 22,
  },
  {
    name: 'Cam Pha City',
    code: 195,
    division_type: 'City',
    codename: 'thanh_pho_cam_pha',
    province_code: 22,
  },
  {
    name: 'Uong Bi City',
    code: 196,
    division_type: 'City',
    codename: 'thanh_pho_uong_bi',
    province_code: 22,
  },
  {
    name: 'Binh Lieu District',
    code: 198,
    division_type: 'District',
    codename: 'huyen_binh_lieu',
    province_code: 22,
  },
  {
    name: 'Tien Yen District',
    code: 199,
    division_type: 'District',
    codename: 'huyen_tien_yen',
    province_code: 22,
  },
  {
    name: 'Dam Ha District',
    code: 200,
    division_type: 'District',
    codename: 'huyen_dam_ha',
    province_code: 22,
  },
  {
    name: 'Hai Ha District',
    code: 201,
    division_type: 'District',
    codename: 'huyen_hai_ha',
    province_code: 22,
  },
  {
    name: 'Ba Che District',
    code: 202,
    division_type: 'District',
    codename: 'huyen_ba_che',
    province_code: 22,
  },
  {
    name: 'Van Don District',
    code: 203,
    division_type: 'District',
    codename: 'huyen_van_don',
    province_code: 22,
  },
  {
    name: 'Dong Trieu Town',
    code: 205,
    division_type: 'Town',
    codename: 'thi_xa_dong_trieu',
    province_code: 22,
  },
  {
    name: 'Quang Yen Town',
    code: 206,
    division_type: 'Town',
    codename: 'thi_xa_quang_yen',
    province_code: 22,
  },
  {
    name: 'Co To District',
    code: 207,
    division_type: 'District',
    codename: 'huyen_co_to',
    province_code: 22,
  },
  {
    name: 'Bac Giang City',
    code: 213,
    division_type: 'City',
    codename: 'thanh_pho_bac_giang',
    province_code: 24,
  },
  {
    name: 'Yen The District',
    code: 215,
    division_type: 'District',
    codename: 'huyen_yen_the',
    province_code: 24,
  },
  {
    name: 'Tan Yen District',
    code: 216,
    division_type: 'District',
    codename: 'huyen_tan_yen',
    province_code: 24,
  },
  {
    name: 'Lang Giang District',
    code: 217,
    division_type: 'District',
    codename: 'huyen_lang_giang',
    province_code: 24,
  },
  {
    name: 'Luc Nam District',
    code: 218,
    division_type: 'District',
    codename: 'huyen_luc_nam',
    province_code: 24,
  },
  {
    name: 'Luc Ngan District',
    code: 219,
    division_type: 'District',
    codename: 'huyen_luc_ngan',
    province_code: 24,
  },
  {
    name: 'Son Dong District',
    code: 220,
    division_type: 'District',
    codename: 'huyen_son_dong',
    province_code: 24,
  },
  {
    name: 'Yen Dung District',
    code: 221,
    division_type: 'District',
    codename: 'huyen_yen_dung',
    province_code: 24,
  },
  {
    name: 'Viet Yen District',
    code: 222,
    division_type: 'District',
    codename: 'huyen_viet_yen',
    province_code: 24,
  },
  {
    name: 'Hiep Hoa District',
    code: 223,
    division_type: 'District',
    codename: 'huyen_hiep_hoa',
    province_code: 24,
  },
  {
    name: 'Viet Tri City',
    code: 227,
    division_type: 'City',
    codename: 'thanh_pho_viet_tri',
    province_code: 25,
  },
  {
    name: 'Phu Tho Town',
    code: 228,
    division_type: 'Town',
    codename: 'thi_xa_phu_tho',
    province_code: 25,
  },
  {
    name: 'Doan Hung District',
    code: 230,
    division_type: 'District',
    codename: 'huyen_doan_hung',
    province_code: 25,
  },
  {
    name: 'Ha Hoa District',
    code: 231,
    division_type: 'District',
    codename: 'huyen_ha_hoa',
    province_code: 25,
  },
  {
    name: 'Thanh Ba District',
    code: 232,
    division_type: 'District',
    codename: 'huyen_thanh_ba',
    province_code: 25,
  },
  {
    name: 'Phu Ninh District',
    code: 233,
    division_type: 'District',
    codename: 'huyen_phu_ninh',
    province_code: 25,
  },
  {
    name: 'Yen Lap District',
    code: 234,
    division_type: 'District',
    codename: 'huyen_yen_lap',
    province_code: 25,
  },
  {
    name: 'Cam Khe District',
    code: 235,
    division_type: 'District',
    codename: 'huyen_cam_khe',
    province_code: 25,
  },
  {
    name: 'Tam Nong District',
    code: 236,
    division_type: 'District',
    codename: 'huyen_tam_nong',
    province_code: 25,
  },
  {
    name: 'Lam Thao District',
    code: 237,
    division_type: 'District',
    codename: 'huyen_lam_thao',
    province_code: 25,
  },
  {
    name: 'Thanh Son District',
    code: 238,
    division_type: 'District',
    codename: 'huyen_thanh_son',
    province_code: 25,
  },
  {
    name: 'Thanh Thuy District',
    code: 239,
    division_type: 'District',
    codename: 'huyen_thanh_thuy',
    province_code: 25,
  },
  {
    name: 'Tan Son District',
    code: 240,
    division_type: 'District',
    codename: 'huyen_tan_son',
    province_code: 25,
  },
  {
    name: 'Vinh Yen City',
    code: 243,
    division_type: 'City',
    codename: 'thanh_pho_vinh_yen',
    province_code: 26,
  },
  {
    name: 'Phuc Yen City',
    code: 244,
    division_type: 'City',
    codename: 'thanh_pho_phuc_yen',
    province_code: 26,
  },
  {
    name: 'Lap Thach District',
    code: 246,
    division_type: 'District',
    codename: 'huyen_lap_thach',
    province_code: 26,
  },
  {
    name: 'Tam Duong District',
    code: 247,
    division_type: 'District',
    codename: 'huyen_tam_duong',
    province_code: 26,
  },
  {
    name: 'Tam Dao District',
    code: 248,
    division_type: 'District',
    codename: 'huyen_tam_dao',
    province_code: 26,
  },
  {
    name: 'Binh Xuyen District',
    code: 249,
    division_type: 'District',
    codename: 'huyen_binh_xuyen',
    province_code: 26,
  },
  {
    name: 'Yen Lac District',
    code: 251,
    division_type: 'District',
    codename: 'huyen_yen_lac',
    province_code: 26,
  },
  {
    name: 'Vinh Tuong District',
    code: 252,
    division_type: 'District',
    codename: 'huyen_vinh_tuong',
    province_code: 26,
  },
  {
    name: 'Song Lo District',
    code: 253,
    division_type: 'District',
    codename: 'huyen_song_lo',
    province_code: 26,
  },
  {
    name: 'Bac Ninh City',
    code: 256,
    division_type: 'City',
    codename: 'thanh_pho_bac_ninh',
    province_code: 27,
  },
  {
    name: 'Yen Phong District',
    code: 258,
    division_type: 'District',
    codename: 'huyen_yen_phong',
    province_code: 27,
  },
  {
    name: 'Que Vo Town',
    code: 259,
    division_type: 'Town',
    codename: 'thi_xa_que_vo',
    province_code: 27,
  },
  {
    name: 'Tien Du District',
    code: 260,
    division_type: 'District',
    codename: 'huyen_tien_du',
    province_code: 27,
  },
  {
    name: 'Tu Son City',
    code: 261,
    division_type: 'City',
    codename: 'thanh_pho_tu_son',
    province_code: 27,
  },
  {
    name: 'Thuan Thanh Town',
    code: 262,
    division_type: 'Town',
    codename: 'thi_xa_thuan_thanh',
    province_code: 27,
  },
  {
    name: 'Gia Binh District',
    code: 263,
    division_type: 'District',
    codename: 'huyen_gia_binh',
    province_code: 27,
  },
  {
    name: 'Luong Tai District',
    code: 264,
    division_type: 'District',
    codename: 'huyen_luong_tai',
    province_code: 27,
  },
  {
    name: 'Hai Duong City',
    code: 288,
    division_type: 'City',
    codename: 'thanh_pho_hai_duong',
    province_code: 30,
  },
  {
    name: 'Chi Linh City',
    code: 290,
    division_type: 'City',
    codename: 'thanh_pho_chi_linh',
    province_code: 30,
  },
  {
    name: 'Nam Sach District',
    code: 291,
    division_type: 'District',
    codename: 'huyen_nam_sach',
    province_code: 30,
  },
  {
    name: 'Kinh Mon Town',
    code: 292,
    division_type: 'Town',
    codename: 'thi_xa_kinh_mon',
    province_code: 30,
  },
  {
    name: 'Kim Thanh District',
    code: 293,
    division_type: 'District',
    codename: 'huyen_kim_thanh',
    province_code: 30,
  },
  {
    name: 'Thanh Ha District',
    code: 294,
    division_type: 'District',
    codename: 'huyen_thanh_ha',
    province_code: 30,
  },
  {
    name: 'Cam Giang District',
    code: 295,
    division_type: 'District',
    codename: 'huyen_cam_giang',
    province_code: 30,
  },
  {
    name: 'Binh Giang District',
    code: 296,
    division_type: 'District',
    codename: 'huyen_binh_giang',
    province_code: 30,
  },
  {
    name: 'Gia Loc District',
    code: 297,
    division_type: 'District',
    codename: 'huyen_gia_loc',
    province_code: 30,
  },
  {
    name: 'Tu Ky District',
    code: 298,
    division_type: 'District',
    codename: 'huyen_tu_ky',
    province_code: 30,
  },
  {
    name: 'Ninh Giang District',
    code: 299,
    division_type: 'District',
    codename: 'huyen_ninh_giang',
    province_code: 30,
  },
  {
    name: 'Thanh Mien District',
    code: 300,
    division_type: 'District',
    codename: 'huyen_thanh_mien',
    province_code: 30,
  },
  {
    name: 'Hong Bang District',
    code: 303,
    division_type: 'district',
    codename: 'quan_hong_bang',
    province_code: 31,
  },
  {
    name: 'Ngo Quyen District',
    code: 304,
    division_type: 'district',
    codename: 'quan_ngo_quyen',
    province_code: 31,
  },
  {
    name: 'Le Chan District',
    code: 305,
    division_type: 'district',
    codename: 'quan_le_chan',
    province_code: 31,
  },
  {
    name: 'Hai An District',
    code: 306,
    division_type: 'district',
    codename: 'quan_hai_an',
    province_code: 31,
  },
  {
    name: 'Kien An District',
    code: 307,
    division_type: 'district',
    codename: 'quan_kien_an',
    province_code: 31,
  },
  {
    name: 'Do Son District',
    code: 308,
    division_type: 'district',
    codename: 'quan_do_son',
    province_code: 31,
  },
  {
    name: 'Duong Kinh District',
    code: 309,
    division_type: 'district',
    codename: 'quan_duong_kinh',
    province_code: 31,
  },
  {
    name: 'Thuy Nguyen District',
    code: 311,
    division_type: 'district',
    codename: 'huyen_thuy_nguyen',
    province_code: 31,
  },
  {
    name: 'An Duong District',
    code: 312,
    division_type: 'district',
    codename: 'huyen_an_duong',
    province_code: 31,
  },
  {
    name: 'An Lao District',
    code: 313,
    division_type: 'district',
    codename: 'huyen_an_lao',
    province_code: 31,
  },
  {
    name: 'Kien Thuy District',
    code: 314,
    division_type: 'district',
    codename: 'huyen_kien_thuy',
    province_code: 31,
  },
  {
    name: 'Tien Lang District',
    code: 315,
    division_type: 'district',
    codename: 'huyen_tien_lang',
    province_code: 31,
  },
  {
    name: 'Vinh Bao District',
    code: 316,
    division_type: 'district',
    codename: 'huyen_vinh_bao',
    province_code: 31,
  },
  {
    name: 'Cat Hai District',
    code: 317,
    division_type: 'district',
    codename: 'huyen_cat_hai',
    province_code: 31,
  },
  {
    name: 'Bach Long Vi District',
    code: 318,
    division_type: 'district',
    codename: 'huyen_bach_long_vi',
    province_code: 31,
  },
  {
    name: 'Hung Yen City',
    code: 323,
    division_type: 'city',
    codename: 'thanh_pho_hung_yen',
    province_code: 33,
  },
  {
    name: 'Van Lam District',
    code: 325,
    division_type: 'district',
    codename: 'huyen_van_lam',
    province_code: 33,
  },
  {
    name: 'Van Giang District',
    code: 326,
    division_type: 'district',
    codename: 'huyen_van_giang',
    province_code: 33,
  },
  {
    name: 'Yen My District',
    code: 327,
    division_type: 'district',
    codename: 'huyen_yen_my',
    province_code: 33,
  },
  {
    name: 'My Hao Town',
    code: 328,
    division_type: 'town',
    codename: 'thi_xa_my_hao',
    province_code: 33,
  },
  {
    name: 'An Thi District',
    code: 329,
    division_type: 'district',
    codename: 'huyen_an_thi',
    province_code: 33,
  },
  {
    name: 'Khoai Chau District',
    code: 330,
    division_type: 'district',
    codename: 'huyen_khoai_chau',
    province_code: 33,
  },
  {
    name: 'Kim Dong District',
    code: 331,
    division_type: 'district',
    codename: 'huyen_kim_dong',
    province_code: 33,
  },
  {
    name: 'Tien Lu District',
    code: 332,
    division_type: 'district',
    codename: 'huyen_tien_lu',
    province_code: 33,
  },
  {
    name: 'Phu Cu District',
    code: 333,
    division_type: 'district',
    codename: 'huyen_phu_cu',
    province_code: 33,
  },
  {
    name: 'Thai Binh City',
    code: 336,
    division_type: 'city',
    codename: 'thanh_pho_thai_binh',
    province_code: 34,
  },
  {
    name: 'Quynh Phu District',
    code: 338,
    division_type: 'district',
    codename: 'huyen_quynh_phu',
    province_code: 34,
  },
  {
    name: 'Hung Ha District',
    code: 339,
    division_type: 'district',
    codename: 'huyen_hung_ha',
    province_code: 34,
  },
  {
    name: 'Dong Hung District',
    code: 340,
    division_type: 'district',
    codename: 'huyen_dong_hung',
    province_code: 34,
  },
  {
    name: 'Thai Thuy District',
    code: 341,
    division_type: 'district',
    codename: 'huyen_thai_thuy',
    province_code: 34,
  },
  {
    name: 'Tien Hai District',
    code: 342,
    division_type: 'district',
    codename: 'huyen_tien_hai',
    province_code: 34,
  },
  {
    name: 'Kien Xuong District',
    code: 343,
    division_type: 'district',
    codename: 'huyen_kien_xuong',
    province_code: 34,
  },
  {
    name: 'Vu Thu District',
    code: 344,
    division_type: 'district',
    codename: 'huyen_vu_thu',
    province_code: 34,
  },
  {
    name: 'Phu Ly City',
    code: 347,
    division_type: 'city',
    codename: 'thanh_pho_phu_ly',
    province_code: 35,
  },
  {
    name: 'Duy Tien Town',
    code: 349,
    division_type: 'town',
    codename: 'thi_xa_duy_tien',
    province_code: 35,
  },
  {
    name: 'Kim Bang District',
    code: 350,
    division_type: 'district',
    codename: 'huyen_kim_bang',
    province_code: 35,
  },
  {
    name: 'Thanh Liem District',
    code: 351,
    division_type: 'district',
    codename: 'huyen_thanh_liem',
    province_code: 35,
  },
  {
    name: 'Binh Luc District',
    code: 352,
    division_type: 'district',
    codename: 'huyen_binh_luc',
    province_code: 35,
  },
  {
    name: 'Ly Nhan District',
    code: 353,
    division_type: 'district',
    codename: 'huyen_ly_nhan',
    province_code: 35,
  },
  {
    name: 'Nam Dinh City',
    code: 356,
    division_type: 'city',
    codename: 'thanh_pho_nam_dinh',
    province_code: 36,
  },
  {
    name: 'My Loc District',
    code: 358,
    division_type: 'district',
    codename: 'huyen_my_loc',
    province_code: 36,
  },
  {
    name: 'Vu Ban District',
    code: 359,
    division_type: 'district',
    codename: 'huyen_vu_ban',
    province_code: 36,
  },
  {
    name: 'Y Yen District',
    code: 360,
    division_type: 'district',
    codename: 'huyen_y_yen',
    province_code: 36,
  },
  {
    name: 'Nghia Hung District',
    code: 361,
    division_type: 'district',
    codename: 'huyen_nghia_hung',
    province_code: 36,
  },
  {
    name: 'Nam Truc District',
    code: 362,
    division_type: 'district',
    codename: 'huyen_nam_truc',
    province_code: 36,
  },
  {
    name: 'Truc Ninh District',
    code: 363,
    division_type: 'district',
    codename: 'huyen_truc_ninh',
    province_code: 36,
  },
  {
    name: 'Xuan Truong District',
    code: 364,
    division_type: 'district',
    codename: 'huyen_xuan_truong',
    province_code: 36,
  },
  {
    name: 'Giao Thuy District',
    code: 365,
    division_type: 'district',
    codename: 'huyen_giao_thuy',
    province_code: 36,
  },
  {
    name: 'Hai Hau District',
    code: 366,
    division_type: 'district',
    codename: 'huyen_hai_hau',
    province_code: 36,
  },
  {
    name: 'Ninh Binh City',
    code: 369,
    division_type: 'city',
    codename: 'thanh_pho_ninh_binh',
    province_code: 37,
  },
  {
    name: 'Tam Diep City',
    code: 370,
    division_type: 'city',
    codename: 'thanh_pho_tam_diep',
    province_code: 37,
  },
  {
    name: 'Nho Quan District',
    code: 372,
    division_type: 'district',
    codename: 'huyen_nho_quan',
    province_code: 37,
  },
  {
    name: 'Gia Vien District',
    code: 373,
    division_type: 'district',
    codename: 'huyen_gia_vien',
    province_code: 37,
  },
  {
    name: 'Hoa Lu District',
    code: 374,
    division_type: 'district',
    codename: 'huyen_hoa_lu',
    province_code: 37,
  },
  {
    name: 'Yen Khanh District',
    code: 375,
    division_type: 'district',
    codename: 'huyen_yen_khanh',
    province_code: 37,
  },
  {
    name: 'Kim Son District',
    code: 376,
    division_type: 'district',
    codename: 'huyen_kim_son',
    province_code: 37,
  },
  {
    name: 'Yen Mo District',
    code: 377,
    division_type: 'district',
    codename: 'huyen_yen_mo',
    province_code: 37,
  },
  {
    name: 'Thanh Hoa City',
    code: 380,
    division_type: 'city',
    codename: 'thanh_pho_thanh_hoa',
    province_code: 38,
  },
  {
    name: 'Bim Son Town',
    code: 381,
    division_type: 'town',
    codename: 'thi_xa_bim_son',
    province_code: 38,
  },
  {
    name: 'Sam Son City',
    code: 382,
    division_type: 'city',
    codename: 'thanh_pho_sam_son',
    province_code: 38,
  },
  {
    name: 'Muong Lat District',
    code: 384,
    division_type: 'district',
    codename: 'huyen_muong_lat',
    province_code: 38,
  },
  {
    name: 'Quan Hoa District',
    code: 385,
    division_type: 'district',
    codename: 'huyen_quan_hoa',
    province_code: 38,
  },
  {
    name: 'Ba Thuoc District',
    code: 386,
    division_type: 'district',
    codename: 'huyen_ba_thuoc',
    province_code: 38,
  },
  {
    name: 'Quan Son District',
    code: 387,
    division_type: 'district',
    codename: 'huyen_quan_son',
    province_code: 38,
  },
  {
    name: 'Lang Chanh District',
    code: 388,
    division_type: 'district',
    codename: 'huyen_lang_chanh',
    province_code: 38,
  },
  {
    name: 'Ngoc Lac District',
    code: 389,
    division_type: 'district',
    codename: 'huyen_ngoc_lac',
    province_code: 38,
  },
  {
    name: 'Cam Thuy District',
    code: 390,
    division_type: 'district',
    codename: 'huyen_cam_thuy',
    province_code: 38,
  },
  {
    name: 'Thach Thanh District',
    code: 391,
    division_type: 'district',
    codename: 'huyen_thach_thanh',
    province_code: 38,
  },
  {
    name: 'Ha Trung District',
    code: 392,
    division_type: 'district',
    codename: 'huyen_ha_trung',
    province_code: 38,
  },
  {
    name: 'Vinh Loc District',
    code: 393,
    division_type: 'district',
    codename: 'huyen_vinh_loc',
    province_code: 38,
  },
  {
    name: 'Yen Dinh District',
    code: 394,
    division_type: 'district',
    codename: 'huyen_yen_dinh',
    province_code: 38,
  },
  {
    name: 'Tho Xuan District',
    code: 395,
    division_type: 'district',
    codename: 'huyen_tho_xuan',
    province_code: 38,
  },
  {
    name: 'Thuong Xuan District',
    code: 396,
    division_type: 'district',
    codename: 'huyen_thuong_xuan',
    province_code: 38,
  },
  {
    name: 'Trieu Son District',
    code: 397,
    division_type: 'district',
    codename: 'huyen_trieu_son',
    province_code: 38,
  },
  {
    name: 'Thieu Hoa District',
    code: 398,
    division_type: 'district',
    codename: 'huyen_thieu_hoa',
    province_code: 38,
  },
  {
    name: 'Hoang Hoa District',
    code: 399,
    division_type: 'district',
    codename: 'huyen_hoang_hoa',
    province_code: 38,
  },
  {
    name: 'Hau Loc District',
    code: 400,
    division_type: 'district',
    codename: 'huyen_hau_loc',
    province_code: 38,
  },
  {
    name: 'Nga Son District',
    code: 401,
    division_type: 'district',
    codename: 'huyen_nga_son',
    province_code: 38,
  },
  {
    name: 'Nhu Xuan District',
    code: 402,
    division_type: 'district',
    codename: 'huyen_nhu_xuan',
    province_code: 38,
  },
  {
    name: 'Nhu Thanh District',
    code: 403,
    division_type: 'district',
    codename: 'huyen_nhu_thanh',
    province_code: 38,
  },
  {
    name: 'Nong Cong District',
    code: 404,
    division_type: 'district',
    codename: 'huyen_nong_cong',
    province_code: 38,
  },
  {
    name: 'Dong Son District',
    code: 405,
    division_type: 'district',
    codename: 'huyen_dong_son',
    province_code: 38,
  },
  {
    name: 'Quang Xuong District',
    code: 406,
    division_type: 'district',
    codename: 'huyen_quang_xuong',
    province_code: 38,
  },
  {
    name: 'Nghi Son Town',
    code: 407,
    division_type: 'town',
    codename: 'thi_xa_nghi_son',
    province_code: 38,
  },
  {
    name: 'Vinh City',
    code: 412,
    division_type: 'city',
    codename: 'thanh_pho_vinh',
    province_code: 40,
  },
  {
    name: 'Cua Lo Town',
    code: 413,
    division_type: 'town',
    codename: 'thi_xa_cua_lo',
    province_code: 40,
  },
  {
    name: 'Thai Hoa Town',
    code: 414,
    division_type: 'town',
    codename: 'thi_xa_thai_hoa',
    province_code: 40,
  },
  {
    name: 'Que Phong District',
    code: 415,
    division_type: 'district',
    codename: 'huyen_que_phong',
    province_code: 40,
  },
  {
    name: 'Quy Chau District',
    code: 416,
    division_type: 'district',
    codename: 'huyen_quy_chau',
    province_code: 40,
  },
  {
    name: 'Ky Son District',
    code: 417,
    division_type: 'district',
    codename: 'huyen_ky_son',
    province_code: 40,
  },
  {
    name: 'Tuong Duong District',
    code: 418,
    division_type: 'district',
    codename: 'huyen_tuong_duong',
    province_code: 40,
  },
  {
    name: 'Nghia Dan District',
    code: 419,
    division_type: 'district',
    codename: 'huyen_nghia_dan',
    province_code: 40,
  },
  {
    name: 'Quy Hop District',
    code: 420,
    division_type: 'district',
    codename: 'huyen_quy_hop',
    province_code: 40,
  },
  {
    name: 'Quynh Luu District',
    code: 421,
    division_type: 'district',
    codename: 'huyen_quynh_luu',
    province_code: 40,
  },
  {
    name: 'Con Cuong District',
    code: 422,
    division_type: 'district',
    codename: 'huyen_con_cuong',
    province_code: 40,
  },
  {
    name: 'Tan Ky District',
    code: 423,
    division_type: 'district',
    codename: 'huyen_tan_ky',
    province_code: 40,
  },
  {
    name: 'Anh Son District',
    code: 424,
    division_type: 'district',
    codename: 'huyen_anh_son',
    province_code: 40,
  },
  {
    name: 'Dien Chau District',
    code: 425,
    division_type: 'district',
    codename: 'huyen_dien_chau',
    province_code: 40,
  },
  {
    name: 'Yen Thanh District',
    code: 426,
    division_type: 'district',
    codename: 'huyen_yen_thanh',
    province_code: 40,
  },
  {
    name: 'Do Luong District',
    code: 427,
    division_type: 'district',
    codename: 'huyen_do_luong',
    province_code: 40,
  },
  {
    name: 'Thanh Chuong District',
    code: 428,
    division_type: 'district',
    codename: 'huyen_thanh_chuong',
    province_code: 40,
  },
  {
    name: 'Nghi Loc District',
    code: 429,
    division_type: 'district',
    codename: 'huyen_nghi_loc',
    province_code: 40,
  },
  {
    name: 'Nam Dan District',
    code: 430,
    division_type: 'district',
    codename: 'huyen_nam_dan',
    province_code: 40,
  },
  {
    name: 'Hung Nguyen District',
    code: 431,
    division_type: 'district',
    codename: 'huyen_hung_nguyen',
    province_code: 40,
  },
  {
    name: 'Hoang Mai Town',
    code: 432,
    division_type: 'town',
    codename: 'thi_xa_hoang_mai',
    province_code: 40,
  },
  {
    name: 'Ha Tinh City',
    code: 436,
    division_type: 'City',
    codename: 'thanh_pho_ha_tinh',
    province_code: 42,
  },
  {
    name: 'Hong Linh Town',
    code: 437,
    division_type: 'Town',
    codename: 'thi_xa_hong_linh',
    province_code: 42,
  },
  {
    name: 'Huong Son District',
    code: 439,
    division_type: 'District',
    codename: 'huyen_huong_son',
    province_code: 42,
  },
  {
    name: 'Duc Tho District',
    code: 440,
    division_type: 'District',
    codename: 'huyen_duc_tho',
    province_code: 42,
  },
  {
    name: 'Vu Quang District',
    code: 441,
    division_type: 'District',
    codename: 'huyen_vu_quang',
    province_code: 42,
  },
  {
    name: 'Nghi Xuan District',
    code: 442,
    division_type: 'District',
    codename: 'huyen_nghi_xuan',
    province_code: 42,
  },
  {
    name: 'Can Loc District',
    code: 443,
    division_type: 'District',
    codename: 'huyen_can_loc',
    province_code: 42,
  },
  {
    name: 'Huong Khe District',
    code: 444,
    division_type: 'District',
    codename: 'huyen_huong_khe',
    province_code: 42,
  },
  {
    name: 'Thach Ha District',
    code: 445,
    division_type: 'District',
    codename: 'huyen_thach_ha',
    province_code: 42,
  },
  {
    name: 'Cam Xuyen District',
    code: 446,
    division_type: 'District',
    codename: 'huyen_cam_xuyen',
    province_code: 42,
  },
  {
    name: 'Ky Anh District',
    code: 447,
    division_type: 'District',
    codename: 'huyen_ky_anh',
    province_code: 42,
  },
  {
    name: 'Loc Ha District',
    code: 448,
    division_type: 'District',
    codename: 'huyen_loc_ha',
    province_code: 42,
  },
  {
    name: 'Ky Anh Town',
    code: 449,
    division_type: 'Town',
    codename: 'thi_xa_ky_anh',
    province_code: 42,
  },
  {
    name: 'Dong Hoi City',
    code: 450,
    division_type: 'City',
    codename: 'thanh_pho_dong_hoi',
    province_code: 44,
  },
  {
    name: 'Minh Hoa District',
    code: 452,
    division_type: 'District',
    codename: 'huyen_minh_hoa',
    province_code: 44,
  },
  {
    name: 'Tuyen Hoa District',
    code: 453,
    division_type: 'District',
    codename: 'huyen_tuyen_hoa',
    province_code: 44,
  },
  {
    name: 'Quang Trach District',
    code: 454,
    division_type: 'District',
    codename: 'huyen_quang_trach',
    province_code: 44,
  },
  {
    name: 'Bo Trach District',
    code: 455,
    division_type: 'District',
    codename: 'huyen_bo_trach',
    province_code: 44,
  },
  {
    name: 'Quang Ninh District',
    code: 456,
    division_type: 'District',
    codename: 'huyen_quang_ninh',
    province_code: 44,
  },
  {
    name: 'Le Thuy District',
    code: 457,
    division_type: 'District',
    codename: 'huyen_le_thuy',
    province_code: 44,
  },
  {
    name: 'Ba Don Town',
    code: 458,
    division_type: 'Town',
    codename: 'thi_xa_ba_don',
    province_code: 44,
  },
  {
    name: 'Dong Ha City',
    code: 461,
    division_type: 'City',
    codename: 'thanh_pho_dong_ha',
    province_code: 45,
  },
  {
    name: 'Quang Tri Town',
    code: 462,
    division_type: 'Town',
    codename: 'thi_xa_quang_tri',
    province_code: 45,
  },
  {
    name: 'Vinh Linh District',
    code: 464,
    division_type: 'District',
    codename: 'huyen_vinh_linh',
    province_code: 45,
  },
  {
    name: 'Huong Hoa District',
    code: 465,
    division_type: 'District',
    codename: 'huyen_huong_hoa',
    province_code: 45,
  },
  {
    name: 'Gio Linh District',
    code: 466,
    division_type: 'District',
    codename: 'huyen_gio_linh',
    province_code: 45,
  },
  {
    name: 'Da Krong District',
    code: 467,
    division_type: 'District',
    codename: 'huyen_da_krong',
    province_code: 45,
  },
  {
    name: 'Cam Lo District',
    code: 468,
    division_type: 'District',
    codename: 'huyen_cam_lo',
    province_code: 45,
  },
  {
    name: 'Trieu Phong District',
    code: 469,
    division_type: 'District',
    codename: 'huyen_trieu_phong',
    province_code: 45,
  },
  {
    name: 'Hai Lang District',
    code: 470,
    division_type: 'District',
    codename: 'huyen_hai_lang',
    province_code: 45,
  },
  {
    name: 'Con Co District',
    code: 471,
    division_type: 'District',
    codename: 'huyen_con_co',
    province_code: 45,
  },
  {
    name: 'Hue City',
    code: 474,
    division_type: 'City',
    codename: 'thanh_pho_hue',
    province_code: 46,
  },
  {
    name: 'Phong Dien District',
    code: 476,
    division_type: 'District',
    codename: 'huyen_phong_dien',
    province_code: 46,
  },
  {
    name: 'Quang Dien District',
    code: 477,
    division_type: 'District',
    codename: 'huyen_quang_dien',
    province_code: 46,
  },
  {
    name: 'Phu Vang District',
    code: 478,
    division_type: 'District',
    codename: 'huyen_phu_vang',
    province_code: 46,
  },
  {
    name: 'Huong Thuy Town',
    code: 479,
    division_type: 'Town',
    codename: 'thi_xa_huong_thuy',
    province_code: 46,
  },
  {
    name: 'Huong Tra Town',
    code: 480,
    division_type: 'Town',
    codename: 'thi_xa_huong_tra',
    province_code: 46,
  },
  {
    name: 'A Luoi District',
    code: 481,
    division_type: 'District',
    codename: 'huyen_a_luoi',
    province_code: 46,
  },
  {
    name: 'Phu Loc District',
    code: 482,
    division_type: 'District',
    codename: 'huyen_phu_loc',
    province_code: 46,
  },
  {
    name: 'Nam Dong District',
    code: 483,
    division_type: 'District',
    codename: 'huyen_nam_dong',
    province_code: 46,
  },
  {
    name: 'Lien Chieu District',
    code: 490,
    division_type: 'District',
    codename: 'quan_lien_chieu',
    province_code: 48,
  },
  {
    name: 'Thanh Khe District',
    code: 491,
    division_type: 'District',
    codename: 'quan_thanh_khe',
    province_code: 48,
  },
  {
    name: 'Hai Chau District',
    code: 492,
    division_type: 'District',
    codename: 'quan_hai_chau',
    province_code: 48,
  },
  {
    name: 'Son Tra District',
    code: 493,
    division_type: 'District',
    codename: 'quan_son_tra',
    province_code: 48,
  },
  {
    name: 'Ngu Hanh Son District',
    code: 494,
    division_type: 'District',
    codename: 'quan_ngu_hanh_son',
    province_code: 48,
  },
  {
    name: 'Cam Le District',
    code: 495,
    division_type: 'District',
    codename: 'quan_cam_le',
    province_code: 48,
  },
  {
    name: 'Hoa Vang District',
    code: 497,
    division_type: 'District',
    codename: 'huyen_hoa_vang',
    province_code: 48,
  },
  {
    name: 'Hoang Sa District',
    code: 498,
    division_type: 'District',
    codename: 'huyen_hoang_sa',
    province_code: 48,
  },
  {
    name: 'Tam Ky City',
    code: 502,
    division_type: 'City',
    codename: 'thanh_pho_tam_ky',
    province_code: 49,
  },
  {
    name: 'Hoi An City',
    code: 503,
    division_type: 'City',
    codename: 'thanh_pho_hoi_an',
    province_code: 49,
  },
  {
    name: 'Tay Giang District',
    code: 504,
    division_type: 'District',
    codename: 'huyen_tay_giang',
    province_code: 49,
  },
  {
    name: 'Dong Giang District',
    code: 505,
    division_type: 'District',
    codename: 'huyen_dong_giang',
    province_code: 49,
  },
  {
    name: 'Dai Loc District',
    code: 506,
    division_type: 'District',
    codename: 'huyen_dai_loc',
    province_code: 49,
  },
  {
    name: 'Dien Ban Town',
    code: 507,
    division_type: 'Town',
    codename: 'thi_xa_dien_ban',
    province_code: 49,
  },
  {
    name: 'Duy Xuyen District',
    code: 508,
    division_type: 'District',
    codename: 'huyen_duy_xuyen',
    province_code: 49,
  },
  {
    name: 'Que Son District',
    code: 509,
    division_type: 'District',
    codename: 'huyen_que_son',
    province_code: 49,
  },
  {
    name: 'Nam Giang District',
    code: 510,
    division_type: 'District',
    codename: 'huyen_nam_giang',
    province_code: 49,
  },
  {
    name: 'Phuoc Son District',
    code: 511,
    division_type: 'District',
    codename: 'huyen_phuoc_son',
    province_code: 49,
  },
  {
    name: 'Hiep Duc District',
    code: 512,
    division_type: 'District',
    codename: 'huyen_hiep_duc',
    province_code: 49,
  },
  {
    name: 'Thang Binh District',
    code: 513,
    division_type: 'District',
    codename: 'huyen_thang_binh',
    province_code: 49,
  },
  {
    name: 'Tien Phuoc District',
    code: 514,
    division_type: 'District',
    codename: 'huyen_tien_phuoc',
    province_code: 49,
  },
  {
    name: 'Bac Tra My District',
    code: 515,
    division_type: 'District',
    codename: 'huyen_bac_tra_my',
    province_code: 49,
  },
  {
    name: 'Nam Tra My District',
    code: 516,
    division_type: 'District',
    codename: 'huyen_nam_tra_my',
    province_code: 49,
  },
  {
    name: 'Nui Thanh District',
    code: 517,
    division_type: 'District',
    codename: 'huyen_nui_thanh',
    province_code: 49,
  },
  {
    name: 'Phu Ninh District',
    code: 518,
    division_type: 'District',
    codename: 'huyen_phu_ninh',
    province_code: 49,
  },
  {
    name: 'Nong Son District',
    code: 519,
    division_type: 'District',
    codename: 'huyen_nong_son',
    province_code: 49,
  },
  {
    name: 'Quang Ngai City',
    code: 522,
    division_type: 'City',
    codename: 'thanh_pho_quang_ngai',
    province_code: 51,
  },
  {
    name: 'Binh Son District',
    code: 524,
    division_type: 'District',
    codename: 'huyen_binh_son',
    province_code: 51,
  },
  {
    name: 'Tra Bong District',
    code: 525,
    division_type: 'District',
    codename: 'huyen_tra_bong',
    province_code: 51,
  },
  {
    name: 'Son Tinh District',
    code: 527,
    division_type: 'District',
    codename: 'huyen_son_tinh',
    province_code: 51,
  },
  {
    name: 'Tu Nghia District',
    code: 528,
    division_type: 'District',
    codename: 'huyen_tu_nghia',
    province_code: 51,
  },
  {
    name: 'Son Ha District',
    code: 529,
    division_type: 'District',
    codename: 'huyen_son_ha',
    province_code: 51,
  },
  {
    name: 'Son Tay District',
    code: 530,
    division_type: 'District',
    codename: 'huyen_son_tay',
    province_code: 51,
  },
  {
    name: 'Minh Long District',
    code: 531,
    division_type: 'District',
    codename: 'huyen_minh_long',
    province_code: 51,
  },
  {
    name: 'Nghia Hanh District',
    code: 532,
    division_type: 'District',
    codename: 'huyen_nghia_hanh',
    province_code: 51,
  },
  {
    name: 'Mo Duc District',
    code: 533,
    division_type: 'District',
    codename: 'huyen_mo_duc',
    province_code: 51,
  },
  {
    name: 'Duc Pho Town',
    code: 534,
    division_type: 'Town',
    codename: 'thi_xa_duc_pho',
    province_code: 51,
  },
  {
    name: 'Ba To District',
    code: 535,
    division_type: 'District',
    codename: 'huyen_ba_to',
    province_code: 51,
  },
  {
    name: 'Ly Son District',
    code: 536,
    division_type: 'District',
    codename: 'huyen_ly_son',
    province_code: 51,
  },
  {
    name: 'Quy Nhon City',
    code: 540,
    division_type: 'City',
    codename: 'thanh_pho_quy_nhon',
    province_code: 52,
  },
  {
    name: 'An Lao District',
    code: 542,
    division_type: 'District',
    codename: 'huyen_an_lao',
    province_code: 52,
  },
  {
    name: 'Hoai Nhon Town',
    code: 543,
    division_type: 'Town',
    codename: 'thi_xa_hoai_nhon',
    province_code: 52,
  },
  {
    name: 'Hoai An District',
    code: 544,
    division_type: 'District',
    codename: 'huyen_hoai_an',
    province_code: 52,
  },
  {
    name: 'Phu My District',
    code: 545,
    division_type: 'District',
    codename: 'huyen_phu_my',
    province_code: 52,
  },
  {
    name: 'Vinh Thanh District',
    code: 546,
    division_type: 'District',
    codename: 'huyen_vinh_thanh',
    province_code: 52,
  },
  {
    name: 'Tay Son District',
    code: 547,
    division_type: 'District',
    codename: 'huyen_tay_son',
    province_code: 52,
  },
  {
    name: 'Phu Cat District',
    code: 548,
    division_type: 'District',
    codename: 'huyen_phu_cat',
    province_code: 52,
  },
  {
    name: 'An Nhon Town',
    code: 549,
    division_type: 'Town',
    codename: 'thi_xa_an_nhon',
    province_code: 52,
  },
  {
    name: 'Tuy Phuoc District',
    code: 550,
    division_type: 'District',
    codename: 'huyen_tuy_phuoc',
    province_code: 52,
  },
  {
    name: 'Van Canh District',
    code: 551,
    division_type: 'District',
    codename: 'huyen_van_canh',
    province_code: 52,
  },
  {
    name: 'Tuy Hoa City',
    code: 555,
    division_type: 'City',
    codename: 'thanh_pho_tuy_hoa',
    province_code: 54,
  },
  {
    name: 'Song Cau Town',
    code: 557,
    division_type: 'Town',
    codename: 'thi_xa_song_cau',
    province_code: 54,
  },
  {
    name: 'Dong Xuan District',
    code: 558,
    division_type: 'District',
    codename: 'huyen_dong_xuan',
    province_code: 54,
  },
  {
    name: 'Tuy An District',
    code: 559,
    division_type: 'District',
    codename: 'huyen_tuy_an',
    province_code: 54,
  },
  {
    name: 'Son Hoa District',
    code: 560,
    division_type: 'District',
    codename: 'huyen_son_hoa',
    province_code: 54,
  },
  {
    name: 'Song Hinh District',
    code: 561,
    division_type: 'District',
    codename: 'huyen_song_hinh',
    province_code: 54,
  },
  {
    name: 'Tay Hoa District',
    code: 562,
    division_type: 'District',
    codename: 'huyen_tay_hoa',
    province_code: 54,
  },
  {
    name: 'Phu Hoa District',
    code: 563,
    division_type: 'District',
    codename: 'huyen_phu_hoa',
    province_code: 54,
  },
  {
    name: 'Dong Hoa Town',
    code: 564,
    division_type: 'Town',
    codename: 'thi_xa_dong_hoa',
    province_code: 54,
  },
  {
    name: 'Nha Trang City',
    code: 568,
    division_type: 'City',
    codename: 'thanh_pho_nha_trang',
    province_code: 56,
  },
  {
    name: 'Cam Ranh City',
    code: 569,
    division_type: 'City',
    codename: 'thanh_pho_cam_ranh',
    province_code: 56,
  },
  {
    name: 'Cam Lam District',
    code: 570,
    division_type: 'District',
    codename: 'huyen_cam_lam',
    province_code: 56,
  },
  {
    name: 'Van Ninh District',
    code: 571,
    division_type: 'District',
    codename: 'huyen_van_ninh',
    province_code: 56,
  },
  {
    name: 'Ninh Hoa Town',
    code: 572,
    division_type: 'Town',
    codename: 'thi_xa_ninh_hoa',
    province_code: 56,
  },
  {
    name: 'Khanh Vinh District',
    code: 573,
    division_type: 'District',
    codename: 'huyen_khanh_vinh',
    province_code: 56,
  },
  {
    name: 'Dien Khanh District',
    code: 574,
    division_type: 'District',
    codename: 'huyen_dien_khanh',
    province_code: 56,
  },
  {
    name: 'Khanh Son District',
    code: 575,
    division_type: 'District',
    codename: 'huyen_khanh_son',
    province_code: 56,
  },
  {
    name: 'Truong Sa District',
    code: 576,
    division_type: 'District',
    codename: 'huyen_truong_sa',
    province_code: 56,
  },
  {
    name: 'Phan Rang-Thap Cham City',
    code: 582,
    division_type: 'City',
    codename: 'thanh_pho_phan_rang_thap_cham',
    province_code: 58,
  },
  {
    name: 'Bac Ai District',
    code: 584,
    division_type: 'District',
    codename: 'huyen_bac_ai',
    province_code: 58,
  },
  {
    name: 'Ninh Son District',
    code: 585,
    division_type: 'District',
    codename: 'huyen_ninh_son',
    province_code: 58,
  },
  {
    name: 'Ninh Hai District',
    code: 586,
    division_type: 'District',
    codename: 'huyen_ninh_hai',
    province_code: 58,
  },
  {
    name: 'Ninh Phuoc District',
    code: 587,
    division_type: 'District',
    codename: 'huyen_ninh_phuoc',
    province_code: 58,
  },
  {
    name: 'Thuan Bac District',
    code: 588,
    division_type: 'District',
    codename: 'huyen_thuan_bac',
    province_code: 58,
  },
  {
    name: 'Thuan Nam District',
    code: 589,
    division_type: 'District',
    codename: 'huyen_thuan_nam',
    province_code: 58,
  },
  {
    name: 'Phan Thiet City',
    code: 593,
    division_type: 'City',
    codename: 'thanh_pho_phan_thiet',
    province_code: 60,
  },
  {
    name: 'La Gi Town',
    code: 594,
    division_type: 'Town',
    codename: 'thi_xa_la_gi',
    province_code: 60,
  },
  {
    name: 'Tuy Phong District',
    code: 595,
    division_type: 'District',
    codename: 'huyen_tuy_phong',
    province_code: 60,
  },
  {
    name: 'Bac Binh District',
    code: 596,
    division_type: 'District',
    codename: 'huyen_bac_binh',
    province_code: 60,
  },
  {
    name: 'Ham Thuan Bac District',
    code: 597,
    division_type: 'District',
    codename: 'huyen_ham_thuan_bac',
    province_code: 60,
  },
  {
    name: 'Ham Thuan Nam District',
    code: 598,
    division_type: 'District',
    codename: 'huyen_ham_thuan_nam',
    province_code: 60,
  },
  {
    name: 'Tanh Linh District',
    code: 599,
    division_type: 'District',
    codename: 'huyen_tanh_linh',
    province_code: 60,
  },
  {
    name: 'Duc Linh District',
    code: 600,
    division_type: 'District',
    codename: 'huyen_duc_linh',
    province_code: 60,
  },
  {
    name: 'Ham Tan District',
    code: 601,
    division_type: 'District',
    codename: 'huyen_ham_tan',
    province_code: 60,
  },
  {
    name: 'Phu Qui District',
    code: 602,
    division_type: 'District',
    codename: 'huyen_phu_qui',
    province_code: 60,
  },
  {
    name: 'Kon Tum City',
    code: 608,
    division_type: 'City',
    codename: 'thanh_pho_kon_tum',
    province_code: 62,
  },
  {
    name: 'Dak Glei District',
    code: 610,
    division_type: 'District',
    codename: 'huyen_dak_glei',
    province_code: 62,
  },
  {
    name: 'Ngoc Hoi District',
    code: 611,
    division_type: 'District',
    codename: 'huyen_ngoc_hoi',
    province_code: 62,
  },
  {
    name: 'Dak To District',
    code: 612,
    division_type: 'District',
    codename: 'huyen_dak_to',
    province_code: 62,
  },
  {
    name: 'Kon Plong District',
    code: 613,
    division_type: 'District',
    codename: 'huyen_kon_plong',
    province_code: 62,
  },
  {
    name: 'Kon Ray District',
    code: 614,
    division_type: 'District',
    codename: 'huyen_kon_ray',
    province_code: 62,
  },
  {
    name: 'Dak Ha District',
    code: 615,
    division_type: 'District',
    codename: 'huyen_dak_ha',
    province_code: 62,
  },
  {
    name: 'Sa Thay District',
    code: 616,
    division_type: 'District',
    codename: 'huyen_sa_thay',
    province_code: 62,
  },
  {
    name: 'Tu Mo Rong District',
    code: 617,
    division_type: 'District',
    codename: 'huyen_tu_mo_rong',
    province_code: 62,
  },
  {
    name: "Ia H' Drai District",
    code: 618,
    division_type: 'District',
    codename: 'huyen_ia_h_drai',
    province_code: 62,
  },
  {
    name: 'Pleiku City',
    code: 622,
    division_type: 'City',
    codename: 'thanh_pho_pleiku',
    province_code: 64,
  },
  {
    name: 'An Khe Town',
    code: 623,
    division_type: 'Town',
    codename: 'thi_xa_an_khe',
    province_code: 64,
  },
  {
    name: 'Ayun Pa Town',
    code: 624,
    division_type: 'Town',
    codename: 'thi_xa_ayun_pa',
    province_code: 64,
  },
  {
    name: 'KBang District',
    code: 625,
    division_type: 'District',
    codename: 'huyen_kbang',
    province_code: 64,
  },
  {
    name: 'Dak Doa District',
    code: 626,
    division_type: 'District',
    codename: 'huyen_dak_doa',
    province_code: 64,
  },
  {
    name: 'Chu Pah District',
    code: 627,
    division_type: 'District',
    codename: 'huyen_chu_pah',
    province_code: 64,
  },
  {
    name: 'Ia Grai District',
    code: 628,
    division_type: 'District',
    codename: 'huyen_ia_grai',
    province_code: 64,
  },
  {
    name: 'Mang Yang District',
    code: 629,
    division_type: 'District',
    codename: 'huyen_mang_yang',
    province_code: 64,
  },
  {
    name: 'Kong Chro District',
    code: 630,
    division_type: 'District',
    codename: 'huyen_kong_chro',
    province_code: 64,
  },
  {
    name: 'Duc Co District',
    code: 631,
    division_type: 'District',
    codename: 'huyen_duc_co',
    province_code: 64,
  },
  {
    name: 'Chu Prong District',
    code: 632,
    division_type: 'District',
    codename: 'huyen_chu_prong',
    province_code: 64,
  },
  {
    name: 'Chu Se District',
    code: 633,
    division_type: 'District',
    codename: 'huyen_chu_se',
    province_code: 64,
  },
  {
    name: 'Dak Po District',
    code: 634,
    division_type: 'District',
    codename: 'huyen_dak_po',
    province_code: 64,
  },
  {
    name: 'Ia Pa District',
    code: 635,
    division_type: 'District',
    codename: 'huyen_ia_pa',
    province_code: 64,
  },
  {
    name: 'Krong Pa District',
    code: 637,
    division_type: 'District',
    codename: 'huyen_krong_pa',
    province_code: 64,
  },
  {
    name: 'Phu Thien District',
    code: 638,
    division_type: 'District',
    codename: 'huyen_phu_thien',
    province_code: 64,
  },
  {
    name: 'Chu Puh District',
    code: 639,
    division_type: 'District',
    codename: 'huyen_chu_puh',
    province_code: 64,
  },
  {
    name: 'Buon Ma Thuot City',
    code: 643,
    division_type: 'City',
    codename: 'thanh_pho_buon_ma_thuot',
    province_code: 66,
  },
  {
    name: 'Buon Ho Town',
    code: 644,
    division_type: 'Town',
    codename: 'thi_xa_buon_ho',
    province_code: 66,
  },
  {
    name: "Ea H'leo District",
    code: 645,
    division_type: 'District',
    codename: 'huyen_ea_hleo',
    province_code: 66,
  },
  {
    name: 'Ea Sup District',
    code: 646,
    division_type: 'District',
    codename: 'huyen_ea_sup',
    province_code: 66,
  },
  {
    name: 'Buon Don District',
    code: 647,
    division_type: 'District',
    codename: 'huyen_buon_don',
    province_code: 66,
  },
  {
    name: "Cu M'gar District",
    code: 648,
    division_type: 'District',
    codename: 'huyen_cu_mgar',
    province_code: 66,
  },
  {
    name: 'Krong Buk District',
    code: 649,
    division_type: 'District',
    codename: 'huyen_krong_buk',
    province_code: 66,
  },
  {
    name: 'Krong Nang District',
    code: 650,
    division_type: 'District',
    codename: 'huyen_krong_nang',
    province_code: 66,
  },
  {
    name: 'Ea Kar District',
    code: 651,
    division_type: 'District',
    codename: 'huyen_ea_kar',
    province_code: 66,
  },
  {
    name: "M'Drak District",
    code: 652,
    division_type: 'District',
    codename: 'huyen_mdrak',
    province_code: 66,
  },
  {
    name: 'Krong Bong District',
    code: 653,
    division_type: 'District',
    codename: 'huyen_krong_bong',
    province_code: 66,
  },
  {
    name: 'Krong Pac District',
    code: 654,
    division_type: 'District',
    codename: 'huyen_krong_pac',
    province_code: 66,
  },
  {
    name: 'Krong A Na District',
    code: 655,
    division_type: 'District',
    codename: 'huyen_krong_a_na',
    province_code: 66,
  },
  {
    name: 'Lak District',
    code: 656,
    division_type: 'District',
    codename: 'huyen_lak',
    province_code: 66,
  },
  {
    name: 'Cu Kuin District',
    code: 657,
    division_type: 'District',
    codename: 'huyen_cu_kuin',
    province_code: 66,
  },
  {
    name: 'Gia Nghia City',
    code: 660,
    division_type: 'City',
    codename: 'thanh_pho_gia_nghia',
    province_code: 67,
  },
  {
    name: 'Dak Glong District',
    code: 661,
    division_type: 'District',
    codename: 'huyen_dak_glong',
    province_code: 67,
  },
  {
    name: 'Cu Jut District',
    code: 662,
    division_type: 'District',
    codename: 'huyen_cu_jut',
    province_code: 67,
  },
  {
    name: 'Dak Mil District',
    code: 663,
    division_type: 'District',
    codename: 'huyen_dak_mil',
    province_code: 67,
  },
  {
    name: 'Krong No District',
    code: 664,
    division_type: 'District',
    codename: 'huyen_krong_no',
    province_code: 67,
  },
  {
    name: 'Dak Song District',
    code: 665,
    division_type: 'District',
    codename: 'huyen_dak_song',
    province_code: 67,
  },
  {
    name: "Dak R'Lap District",
    code: 666,
    division_type: 'District',
    codename: 'huyen_dak_rlap',
    province_code: 67,
  },
  {
    name: 'Tuy Duc District',
    code: 667,
    division_type: 'District',
    codename: 'huyen_tuy_duc',
    province_code: 67,
  },
  {
    name: 'Da Lat City',
    code: 672,
    division_type: 'City',
    codename: 'thanh_pho_da_lat',
    province_code: 68,
  },
  {
    name: 'Bao Loc City',
    code: 673,
    division_type: 'City',
    codename: 'thanh_pho_bao_loc',
    province_code: 68,
  },
  {
    name: 'Dam Rong District',
    code: 674,
    division_type: 'District',
    codename: 'huyen_dam_rong',
    province_code: 68,
  },
  {
    name: 'Lac Duong District',
    code: 675,
    division_type: 'District',
    codename: 'huyen_lac_duong',
    province_code: 68,
  },
  {
    name: 'Lam Ha District',
    code: 676,
    division_type: 'District',
    codename: 'huyen_lam_ha',
    province_code: 68,
  },
  {
    name: 'Don Duong District',
    code: 677,
    division_type: 'District',
    codename: 'huyen_don_duong',
    province_code: 68,
  },
  {
    name: 'Duc Trong District',
    code: 678,
    division_type: 'District',
    codename: 'huyen_duc_trong',
    province_code: 68,
  },
  {
    name: 'Di Linh District',
    code: 679,
    division_type: 'District',
    codename: 'huyen_di_linh',
    province_code: 68,
  },
  {
    name: 'Bao Lam District',
    code: 680,
    division_type: 'District',
    codename: 'huyen_bao_lam',
    province_code: 68,
  },
  {
    name: 'Da Huoai District',
    code: 681,
    division_type: 'District',
    codename: 'huyen_da_huoai',
    province_code: 68,
  },
  {
    name: 'Da Teh District',
    code: 682,
    division_type: 'District',
    codename: 'huyen_da_teh',
    province_code: 68,
  },
  {
    name: 'Cat Tien District',
    code: 683,
    division_type: 'District',
    codename: 'huyen_cat_tien',
    province_code: 68,
  },
  {
    name: 'Phuoc Long Town',
    code: 688,
    division_type: 'Town',
    codename: 'thi_xa_phuoc_long',
    province_code: 70,
  },
  {
    name: 'Dong Xoai City',
    code: 689,
    division_type: 'City',
    codename: 'thanh_pho_dong_xoai',
    province_code: 70,
  },
  {
    name: 'Binh Long Town',
    code: 690,
    division_type: 'Town',
    codename: 'thi_xa_binh_long',
    province_code: 70,
  },
  {
    name: 'Bu Gia Map District',
    code: 691,
    division_type: 'District',
    codename: 'huyen_bu_gia_map',
    province_code: 70,
  },
  {
    name: 'Loc Ninh District',
    code: 692,
    division_type: 'District',
    codename: 'huyen_loc_ninh',
    province_code: 70,
  },
  {
    name: 'Bu Dop District',
    code: 693,
    division_type: 'District',
    codename: 'huyen_bu_dop',
    province_code: 70,
  },
  {
    name: 'Hon Quan District',
    code: 694,
    division_type: 'District',
    codename: 'huyen_hon_quan',
    province_code: 70,
  },
  {
    name: 'Dong Phu District',
    code: 695,
    division_type: 'District',
    codename: 'huyen_dong_phu',
    province_code: 70,
  },
  {
    name: 'Bu Dang District',
    code: 696,
    division_type: 'District',
    codename: 'huyen_bu_dang',
    province_code: 70,
  },
  {
    name: 'Chon Thanh Town',
    code: 697,
    division_type: 'Town',
    codename: 'thi_xa_chon_thanh',
    province_code: 70,
  },
  {
    name: 'Phu Rieng District',
    code: 698,
    division_type: 'District',
    codename: 'huyen_phu_rieng',
    province_code: 70,
  },
  {
    name: 'Tay Ninh City',
    code: 703,
    division_type: 'City',
    codename: 'thanh_pho_tay_ninh',
    province_code: 72,
  },
  {
    name: 'Tan Bien District',
    code: 705,
    division_type: 'District',
    codename: 'huyen_tan_bien',
    province_code: 72,
  },
  {
    name: 'Tan Chau District',
    code: 706,
    division_type: 'District',
    codename: 'huyen_tan_chau',
    province_code: 72,
  },
  {
    name: 'Duong Minh Chau District',
    code: 707,
    division_type: 'District',
    codename: 'huyen_duong_minh_chau',
    province_code: 72,
  },
  {
    name: 'Chau Thanh District',
    code: 708,
    division_type: 'District',
    codename: 'huyen_chau_thanh',
    province_code: 72,
  },
  {
    name: 'Hoa Thanh Town',
    code: 709,
    division_type: 'Town',
    codename: 'thi_xa_hoa_thanh',
    province_code: 72,
  },
  {
    name: 'Go Dau District',
    code: 710,
    division_type: 'District',
    codename: 'huyen_go_dau',
    province_code: 72,
  },
  {
    name: 'Ben Cau District',
    code: 711,
    division_type: 'District',
    codename: 'huyen_ben_cau',
    province_code: 72,
  },
  {
    name: 'Trang Bang Town',
    code: 712,
    division_type: 'Town',
    codename: 'thi_xa_trang_bang',
    province_code: 72,
  },
  {
    name: 'Thu Dau Mot City',
    code: 718,
    division_type: 'City',
    codename: 'thanh_pho_thu_dau_mot',
    province_code: 74,
  },
  {
    name: 'Bau Bang District',
    code: 719,
    division_type: 'District',
    codename: 'huyen_bau_bang',
    province_code: 74,
  },
  {
    name: 'Dau Tieng District',
    code: 720,
    division_type: 'District',
    codename: 'huyen_dau_tieng',
    province_code: 74,
  },
  {
    name: 'Ben Cat Town',
    code: 721,
    division_type: 'Town',
    codename: 'thi_xa_ben_cat',
    province_code: 74,
  },
  {
    name: 'Phu Giao District',
    code: 722,
    division_type: 'District',
    codename: 'huyen_phu_giao',
    province_code: 74,
  },
  {
    name: 'Tan Uyen City',
    code: 723,
    division_type: 'City',
    codename: 'thanh_pho_tan_uyen',
    province_code: 74,
  },
  {
    name: 'Di An City',
    code: 724,
    division_type: 'City',
    codename: 'thanh_pho_di_an',
    province_code: 74,
  },
  {
    name: 'Thuan An City',
    code: 725,
    division_type: 'City',
    codename: 'thanh_pho_thuan_an',
    province_code: 74,
  },
  {
    name: 'Bac Tan Uyen District',
    code: 726,
    division_type: 'District',
    codename: 'huyen_bac_tan_uyen',
    province_code: 74,
  },
  {
    name: 'Bien Hoa City',
    code: 731,
    division_type: 'City',
    codename: 'thanh_pho_bien_hoa',
    province_code: 75,
  },
  {
    name: 'Long Khanh City',
    code: 732,
    division_type: 'City',
    codename: 'thanh_pho_long_khanh',
    province_code: 75,
  },
  {
    name: 'Tan Phu District',
    code: 734,
    division_type: 'District',
    codename: 'huyen_tan_phu',
    province_code: 75,
  },
  {
    name: 'Vinh Cuu District',
    code: 735,
    division_type: 'District',
    codename: 'huyen_vinh_cuu',
    province_code: 75,
  },
  {
    name: 'Dinh Quan District',
    code: 736,
    division_type: 'District',
    codename: 'huyen_dinh_quan',
    province_code: 75,
  },
  {
    name: 'Trang Bom District',
    code: 737,
    division_type: 'District',
    codename: 'huyen_trang_bom',
    province_code: 75,
  },
  {
    name: 'Thong Nhat District',
    code: 738,
    division_type: 'District',
    codename: 'huyen_thong_nhat',
    province_code: 75,
  },
  {
    name: 'Cam My District',
    code: 739,
    division_type: 'District',
    codename: 'huyen_cam_my',
    province_code: 75,
  },
  {
    name: 'Long Thanh District',
    code: 740,
    division_type: 'District',
    codename: 'huyen_long_thanh',
    province_code: 75,
  },
  {
    name: 'Xuan Loc District',
    code: 741,
    division_type: 'District',
    codename: 'huyen_xuan_loc',
    province_code: 75,
  },
  {
    name: 'Nhon Trach District',
    code: 742,
    division_type: 'District',
    codename: 'huyen_nhon_trach',
    province_code: 75,
  },
  {
    name: 'Vung Tau City',
    code: 747,
    division_type: 'City',
    codename: 'thanh_pho_vung_tau',
    province_code: 77,
  },
  {
    name: 'Ba Ria City',
    code: 748,
    division_type: 'City',
    codename: 'thanh_pho_ba_ria',
    province_code: 77,
  },
  {
    name: 'Chau Duc District',
    code: 750,
    division_type: 'District',
    codename: 'huyen_chau_duc',
    province_code: 77,
  },
  {
    name: 'Xuyen Moc District',
    code: 751,
    division_type: 'District',
    codename: 'huyen_xuyen_moc',
    province_code: 77,
  },
  {
    name: 'Long Dien District',
    code: 752,
    division_type: 'District',
    codename: 'huyen_long_dien',
    province_code: 77,
  },
  {
    name: 'Dat Do District',
    code: 753,
    division_type: 'District',
    codename: 'huyen_dat_do',
    province_code: 77,
  },
  {
    name: 'Phu My Town',
    code: 754,
    division_type: 'Town',
    codename: 'thi_xa_phu_my',
    province_code: 77,
  },
  {
    name: 'Con Dao District',
    code: 755,
    division_type: 'District',
    codename: 'huyen_con_dao',
    province_code: 77,
  },
  {
    name: 'District 1',
    code: 760,
    division_type: 'District',
    codename: 'quan_1',
    province_code: 79,
  },
  {
    name: 'District 12',
    code: 761,
    division_type: 'District',
    codename: 'quan_12',
    province_code: 79,
  },
  {
    name: 'Go Vap District',
    code: 764,
    division_type: 'District',
    codename: 'quan_go_vap',
    province_code: 79,
  },
  {
    name: 'Binh Thanh District',
    code: 765,
    division_type: 'District',
    codename: 'quan_binh_thanh',
    province_code: 79,
  },
  {
    name: 'Tan Binh District',
    code: 766,
    division_type: 'District',
    codename: 'quan_tan_binh',
    province_code: 79,
  },
  {
    name: 'Tan Phu District',
    code: 767,
    division_type: 'District',
    codename: 'quan_tan_phu',
    province_code: 79,
  },
  {
    name: 'Phu Nhuan District',
    code: 768,
    division_type: 'District',
    codename: 'quan_phu_nhuan',
    province_code: 79,
  },
  {
    name: 'Thu Duc City',
    code: 769,
    division_type: 'City',
    codename: 'thanh_pho_thu_duc',
    province_code: 79,
  },
  {
    name: 'District 3',
    code: 770,
    division_type: 'District',
    codename: 'quan_3',
    province_code: 79,
  },
  {
    name: 'District 10',
    code: 771,
    division_type: 'District',
    codename: 'quan_10',
    province_code: 79,
  },
  {
    name: 'District 11',
    code: 772,
    division_type: 'District',
    codename: 'quan_11',
    province_code: 79,
  },
  {
    name: 'District 4',
    code: 773,
    division_type: 'District',
    codename: 'quan_4',
    province_code: 79,
  },
  {
    name: 'District 5',
    code: 774,
    division_type: 'District',
    codename: 'quan_5',
    province_code: 79,
  },
  {
    name: 'District 6',
    code: 775,
    division_type: 'District',
    codename: 'quan_6',
    province_code: 79,
  },
  {
    name: 'District 8',
    code: 776,
    division_type: 'District',
    codename: 'quan_8',
    province_code: 79,
  },
  {
    name: 'Binh Tan District',
    code: 777,
    division_type: 'District',
    codename: 'quan_binh_tan',
    province_code: 79,
  },
  {
    name: 'District 7',
    code: 778,
    division_type: 'District',
    codename: 'quan_7',
    province_code: 79,
  },
  {
    name: 'Cu Chi District',
    code: 783,
    division_type: 'District',
    codename: 'huyen_cu_chi',
    province_code: 79,
  },
  {
    name: 'Hoc Mon District',
    code: 784,
    division_type: 'District',
    codename: 'huyen_hoc_mon',
    province_code: 79,
  },
  {
    name: 'Binh Chanh District',
    code: 785,
    division_type: 'District',
    codename: 'huyen_binh_chanh',
    province_code: 79,
  },
  {
    name: 'Nha Be District',
    code: 786,
    division_type: 'District',
    codename: 'huyen_nha_be',
    province_code: 79,
  },
  {
    name: 'Can Gio District',
    code: 787,
    division_type: 'District',
    codename: 'huyen_can_gio',
    province_code: 79,
  },
  {
    name: 'Tan An City',
    code: 794,
    division_type: 'City',
    codename: 'thanh_pho_tan_an',
    province_code: 80,
  },
  {
    name: 'Kien Tuong Town',
    code: 795,
    division_type: 'Town',
    codename: 'thi_xa_kien_tuong',
    province_code: 80,
  },
  {
    name: 'Tan Hung District',
    code: 796,
    division_type: 'District',
    codename: 'huyen_tan_hung',
    province_code: 80,
  },
  {
    name: 'Vinh Hung District',
    code: 797,
    division_type: 'District',
    codename: 'huyen_vinh_hung',
    province_code: 80,
  },
  {
    name: 'Moc Hoa District',
    code: 798,
    division_type: 'District',
    codename: 'huyen_moc_hoa',
    province_code: 80,
  },
  {
    name: 'Tan Thanh District',
    code: 799,
    division_type: 'District',
    codename: 'huyen_tan_thanh',
    province_code: 80,
  },
  {
    name: 'Thanh Hoa District',
    code: 800,
    division_type: 'District',
    codename: 'huyen_thanh_hoa',
    province_code: 80,
  },
  {
    name: 'Duc Hue District',
    code: 801,
    division_type: 'District',
    codename: 'huyen_duc_hue',
    province_code: 80,
  },
  {
    name: 'Duc Hoa District',
    code: 802,
    division_type: 'District',
    codename: 'huyen_duc_hoa',
    province_code: 80,
  },
  {
    name: 'Ben Luc District',
    code: 803,
    division_type: 'District',
    codename: 'huyen_ben_luc',
    province_code: 80,
  },
  {
    name: 'Thu Thua District',
    code: 804,
    division_type: 'District',
    codename: 'huyen_thu_thua',
    province_code: 80,
  },
  {
    name: 'Tan Tru District',
    code: 805,
    division_type: 'District',
    codename: 'huyen_tan_tru',
    province_code: 80,
  },
  {
    name: 'Can Duoc District',
    code: 806,
    division_type: 'District',
    codename: 'huyen_can_duoc',
    province_code: 80,
  },
  {
    name: 'Can Giuoc District',
    code: 807,
    division_type: 'District',
    codename: 'huyen_can_giuoc',
    province_code: 80,
  },
  {
    name: 'Chau Thanh District',
    code: 808,
    division_type: 'District',
    codename: 'huyen_chau_thanh',
    province_code: 80,
  },
  {
    name: 'My Tho City',
    code: 815,
    division_type: 'City',
    codename: 'thanh_pho_my_tho',
    province_code: 82,
  },
  {
    name: 'Go Cong Town',
    code: 816,
    division_type: 'Town',
    codename: 'thi_xa_go_cong',
    province_code: 82,
  },
  {
    name: 'Cai Lay Town',
    code: 817,
    division_type: 'Town',
    codename: 'thi_xa_cai_lay',
    province_code: 82,
  },
  {
    name: 'Tan Phuoc District',
    code: 818,
    division_type: 'District',
    codename: 'huyen_tan_phuoc',
    province_code: 82,
  },
  {
    name: 'Cai Be District',
    code: 819,
    division_type: 'District',
    codename: 'huyen_cai_be',
    province_code: 82,
  },
  {
    name: 'Cai Lay District',
    code: 820,
    division_type: 'District',
    codename: 'huyen_cai_lay',
    province_code: 82,
  },
  {
    name: 'Chau Thanh District',
    code: 821,
    division_type: 'District',
    codename: 'huyen_chau_thanh',
    province_code: 82,
  },
  {
    name: 'Cho Gao District',
    code: 822,
    division_type: 'District',
    codename: 'huyen_cho_gao',
    province_code: 82,
  },
  {
    name: 'Go Cong Tay District',
    code: 823,
    division_type: 'District',
    codename: 'huyen_go_cong_tay',
    province_code: 82,
  },
  {
    name: 'Go Cong Dong District',
    code: 824,
    division_type: 'District',
    codename: 'huyen_go_cong_dong',
    province_code: 82,
  },
  {
    name: 'Tan Phu Dong District',
    code: 825,
    division_type: 'District',
    codename: 'huyen_tan_phu_dong',
    province_code: 82,
  },
  {
    name: 'Ben Tre City',
    code: 829,
    division_type: 'City',
    codename: 'thanh_pho_ben_tre',
    province_code: 83,
  },
  {
    name: 'Chau Thanh District',
    code: 831,
    division_type: 'District',
    codename: 'huyen_chau_thanh',
    province_code: 83,
  },
  {
    name: 'Cho Lach District',
    code: 832,
    division_type: 'District',
    codename: 'huyen_cho_lach',
    province_code: 83,
  },
  {
    name: 'Mo Cay Nam District',
    code: 833,
    division_type: 'District',
    codename: 'huyen_mo_cay_nam',
    province_code: 83,
  },
  {
    name: 'Giong Trom District',
    code: 834,
    division_type: 'District',
    codename: 'huyen_giong_trom',
    province_code: 83,
  },
  {
    name: 'Binh Dai District',
    code: 835,
    division_type: 'District',
    codename: 'huyen_binh_dai',
    province_code: 83,
  },
  {
    name: 'Ba Tri District',
    code: 836,
    division_type: 'District',
    codename: 'huyen_ba_tri',
    province_code: 83,
  },
  {
    name: 'Thanh Phu District',
    code: 837,
    division_type: 'District',
    codename: 'huyen_thanh_phu',
    province_code: 83,
  },
  {
    name: 'Mo Cay Bac District',
    code: 838,
    division_type: 'District',
    codename: 'huyen_mo_cay_bac',
    province_code: 83,
  },
  {
    name: 'Tra Vinh City',
    code: 842,
    division_type: 'City',
    codename: 'thanh_pho_tra_vinh',
    province_code: 84,
  },
  {
    name: 'Cang Long District',
    code: 844,
    division_type: 'District',
    codename: 'huyen_cang_long',
    province_code: 84,
  },
  {
    name: 'Cau Ke District',
    code: 845,
    division_type: 'District',
    codename: 'huyen_cau_ke',
    province_code: 84,
  },
  {
    name: 'Tieu Can District',
    code: 846,
    division_type: 'District',
    codename: 'huyen_tieu_can',
    province_code: 84,
  },
  {
    name: 'Chau Thanh District',
    code: 847,
    division_type: 'District',
    codename: 'huyen_chau_thanh',
    province_code: 84,
  },
  {
    name: 'Cau Ngang District',
    code: 848,
    division_type: 'District',
    codename: 'huyen_cau_ngang',
    province_code: 84,
  },
  {
    name: 'Tra Cu District',
    code: 849,
    division_type: 'District',
    codename: 'huyen_tra_cu',
    province_code: 84,
  },
  {
    name: 'Duyen Hai District',
    code: 850,
    division_type: 'District',
    codename: 'huyen_duyen_hai',
    province_code: 84,
  },
  {
    name: 'Duyen Hai Town',
    code: 851,
    division_type: 'Town',
    codename: 'thi_xa_duyen_hai',
    province_code: 84,
  },
  {
    name: 'Vinh Long City',
    code: 855,
    division_type: 'City',
    codename: 'thanh_pho_vinh_long',
    province_code: 86,
  },
  {
    name: 'Long Ho District',
    code: 857,
    division_type: 'District',
    codename: 'huyen_long_ho',
    province_code: 86,
  },
  {
    name: 'Mang Thit District',
    code: 858,
    division_type: 'District',
    codename: 'huyen_mang_thit',
    province_code: 86,
  },
  {
    name: 'Vung Liem District',
    code: 859,
    division_type: 'District',
    codename: 'huyen_vung_liem',
    province_code: 86,
  },
  {
    name: 'Tam Binh District',
    code: 860,
    division_type: 'District',
    codename: 'huyen_tam_binh',
    province_code: 86,
  },
  {
    name: 'Binh Minh Town',
    code: 861,
    division_type: 'Town',
    codename: 'thi_xa_binh_minh',
    province_code: 86,
  },
  {
    name: 'Tra On District',
    code: 862,
    division_type: 'District',
    codename: 'huyen_tra_on',
    province_code: 86,
  },
  {
    name: 'Binh Tan District',
    code: 863,
    division_type: 'District',
    codename: 'huyen_binh_tan',
    province_code: 86,
  },
  {
    name: 'Cao Lanh City',
    code: 866,
    division_type: 'City',
    codename: 'thanh_pho_cao_lanh',
    province_code: 87,
  },
  {
    name: 'Sa Dec City',
    code: 867,
    division_type: 'City',
    codename: 'thanh_pho_sa_dec',
    province_code: 87,
  },
  {
    name: 'Hong Ngu City',
    code: 868,
    division_type: 'City',
    codename: 'thanh_pho_hong_ngu',
    province_code: 87,
  },
  {
    name: 'Tan Hong District',
    code: 869,
    division_type: 'District',
    codename: 'huyen_tan_hong',
    province_code: 87,
  },
  {
    name: 'Hong Ngu District',
    code: 870,
    division_type: 'District',
    codename: 'huyen_hong_ngu',
    province_code: 87,
  },
  {
    name: 'Tam Nong District',
    code: 871,
    division_type: 'District',
    codename: 'huyen_tam_nong',
    province_code: 87,
  },
  {
    name: 'Thap Muoi District',
    code: 872,
    division_type: 'District',
    codename: 'huyen_thap_muoi',
    province_code: 87,
  },
  {
    name: 'Cao Lanh District',
    code: 873,
    division_type: 'District',
    codename: 'huyen_cao_lanh',
    province_code: 87,
  },
  {
    name: 'Thanh Binh District',
    code: 874,
    division_type: 'District',
    codename: 'huyen_thanh_binh',
    province_code: 87,
  },
  {
    name: 'Lap Vo District',
    code: 875,
    division_type: 'District',
    codename: 'huyen_lap_vo',
    province_code: 87,
  },
  {
    name: 'Lai Vung District',
    code: 876,
    division_type: 'District',
    codename: 'huyen_lai_vung',
    province_code: 87,
  },
  {
    name: 'Chau Thanh District',
    code: 877,
    division_type: 'District',
    codename: 'huyen_chau_thanh',
    province_code: 87,
  },
  {
    name: 'Long Xuyen City',
    code: 883,
    division_type: 'City',
    codename: 'thanh_pho_long_xuyen',
    province_code: 89,
  },
  {
    name: 'Chau Doc City',
    code: 884,
    division_type: 'City',
    codename: 'thanh_pho_chau_doc',
    province_code: 89,
  },
  {
    name: 'An Phu District',
    code: 886,
    division_type: 'District',
    codename: 'huyen_an_phu',
    province_code: 89,
  },
  {
    name: 'Tan Chau Town',
    code: 887,
    division_type: 'Town',
    codename: 'thi_xa_tan_chau',
    province_code: 89,
  },
  {
    name: 'Phu Tan District',
    code: 888,
    division_type: 'District',
    codename: 'huyen_phu_tan',
    province_code: 89,
  },
  {
    name: 'Chau Phu District',
    code: 889,
    division_type: 'District',
    codename: 'huyen_chau_phu',
    province_code: 89,
  },
  {
    name: 'Tinh Bien Town',
    code: 890,
    division_type: 'Town',
    codename: 'thi_xa_tinh_bien',
    province_code: 89,
  },
  {
    name: 'Tri Ton District',
    code: 891,
    division_type: 'District',
    codename: 'huyen_tri_ton',
    province_code: 89,
  },
  {
    name: 'Chau Thanh District',
    code: 892,
    division_type: 'District',
    codename: 'huyen_chau_thanh',
    province_code: 89,
  },
  {
    name: 'Cho Moi District',
    code: 893,
    division_type: 'District',
    codename: 'huyen_cho_moi',
    province_code: 89,
  },
  {
    name: 'Thoai Son District',
    code: 894,
    division_type: 'District',
    codename: 'huyen_thoai_son',
    province_code: 89,
  },
  {
    name: 'Rach Gia City',
    code: 899,
    division_type: 'City',
    codename: 'thanh_pho_rach_gia',
    province_code: 91,
  },
  {
    name: 'Ha Tien City',
    code: 900,
    division_type: 'City',
    codename: 'thanh_pho_ha_tien',
    province_code: 91,
  },
  {
    name: 'Kien Luong District',
    code: 902,
    division_type: 'District',
    codename: 'huyen_kien_luong',
    province_code: 91,
  },
  {
    name: 'Hon Dat District',
    code: 903,
    division_type: 'District',
    codename: 'huyen_hon_dat',
    province_code: 91,
  },
  {
    name: 'Tan Hiep District',
    code: 904,
    division_type: 'District',
    codename: 'huyen_tan_hiep',
    province_code: 91,
  },
  {
    name: 'Chau Thanh District',
    code: 905,
    division_type: 'District',
    codename: 'huyen_chau_thanh',
    province_code: 91,
  },
  {
    name: 'Giong Rieng District',
    code: 906,
    division_type: 'District',
    codename: 'huyen_giong_rieng',
    province_code: 91,
  },
  {
    name: 'Go Quao District',
    code: 907,
    division_type: 'District',
    codename: 'huyen_go_quao',
    province_code: 91,
  },
  {
    name: 'An Bien District',
    code: 908,
    division_type: 'District',
    codename: 'huyen_an_bien',
    province_code: 91,
  },
  {
    name: 'An Minh District',
    code: 909,
    division_type: 'District',
    codename: 'huyen_an_minh',
    province_code: 91,
  },
  {
    name: 'Vinh Thuan District',
    code: 910,
    division_type: 'District',
    codename: 'huyen_vinh_thuan',
    province_code: 91,
  },
  {
    name: 'Phu Quoc City',
    code: 911,
    division_type: 'City',
    codename: 'thanh_pho_phu_quoc',
    province_code: 91,
  },
  {
    name: 'Kien Hai District',
    code: 912,
    division_type: 'District',
    codename: 'huyen_kien_hai',
    province_code: 91,
  },
  {
    name: 'U Minh Thuong District',
    code: 913,
    division_type: 'District',
    codename: 'huyen_u_minh_thuong',
    province_code: 91,
  },
  {
    name: 'Giang Thanh District',
    code: 914,
    division_type: 'District',
    codename: 'huyen_giang_thanh',
    province_code: 91,
  },
  {
    name: 'Ninh Kieu District',
    code: 916,
    division_type: 'District',
    codename: 'quan_ninh_kieu',
    province_code: 92,
  },
  {
    name: 'O Mon District',
    code: 917,
    division_type: 'District',
    codename: 'quan_o_mon',
    province_code: 92,
  },
  {
    name: 'Binh Thuy District',
    code: 918,
    division_type: 'District',
    codename: 'quan_binh_thuy',
    province_code: 92,
  },
  {
    name: 'Cai Rang District',
    code: 919,
    division_type: 'District',
    codename: 'quan_cai_rang',
    province_code: 92,
  },
  {
    name: 'Thot Not District',
    code: 923,
    division_type: 'District',
    codename: 'quan_thot_not',
    province_code: 92,
  },
  {
    name: 'Vinh Thanh District',
    code: 924,
    division_type: 'District',
    codename: 'huyen_vinh_thanh',
    province_code: 92,
  },
  {
    name: 'Co Do District',
    code: 925,
    division_type: 'District',
    codename: 'huyen_co_do',
    province_code: 92,
  },
  {
    name: 'Phong Dien District',
    code: 926,
    division_type: 'District',
    codename: 'huyen_phong_dien',
    province_code: 92,
  },
  {
    name: 'Thoi Lai District',
    code: 927,
    division_type: 'District',
    codename: 'huyen_thoi_lai',
    province_code: 92,
  },
  {
    name: 'Vi Thanh City',
    code: 930,
    division_type: 'City',
    codename: 'thanh_pho_vi_thanh',
    province_code: 93,
  },
  {
    name: 'Nga Bay City',
    code: 931,
    division_type: 'City',
    codename: 'thanh_pho_nga_bay',
    province_code: 93,
  },
  {
    name: 'Chau Thanh A District',
    code: 932,
    division_type: 'District',
    codename: 'huyen_chau_thanh_a',
    province_code: 93,
  },
  {
    name: 'Chau Thanh District',
    code: 933,
    division_type: 'District',
    codename: 'huyen_chau_thanh',
    province_code: 93,
  },
  {
    name: 'Phung Hiep District',
    code: 934,
    division_type: 'District',
    codename: 'huyen_phung_hiep',
    province_code: 93,
  },
  {
    name: 'Vi Thuy District',
    code: 935,
    division_type: 'District',
    codename: 'huyen_vi_thuy',
    province_code: 93,
  },
  {
    name: 'Long My District',
    code: 936,
    division_type: 'District',
    codename: 'huyen_long_my',
    province_code: 93,
  },
  {
    name: 'Long My Town',
    code: 937,
    division_type: 'Town',
    codename: 'thi_xa_long_my',
    province_code: 93,
  },
  {
    name: 'Soc Trang City',
    code: 941,
    division_type: 'City',
    codename: 'thanh_pho_soc_trang',
    province_code: 94,
  },
  {
    name: 'Chau Thanh District',
    code: 942,
    division_type: 'District',
    codename: 'huyen_chau_thanh',
    province_code: 94,
  },
  {
    name: 'Ke Sach District',
    code: 943,
    division_type: 'District',
    codename: 'huyen_ke_sach',
    province_code: 94,
  },
  {
    name: 'My Tu District',
    code: 944,
    division_type: 'District',
    codename: 'huyen_my_tu',
    province_code: 94,
  },
  {
    name: 'Cu Lao Dung District',
    code: 945,
    division_type: 'District',
    codename: 'huyen_cu_lao_dung',
    province_code: 94,
  },
  {
    name: 'Long Phu District',
    code: 946,
    division_type: 'District',
    codename: 'huyen_long_phu',
    province_code: 94,
  },
  {
    name: 'My Xuyen District',
    code: 947,
    division_type: 'District',
    codename: 'huyen_my_xuyen',
    province_code: 94,
  },
  {
    name: 'Nga Nam Town',
    code: 948,
    division_type: 'Town',
    codename: 'thi_xa_nga_nam',
    province_code: 94,
  },
  {
    name: 'Thanh Tri District',
    code: 949,
    division_type: 'District',
    codename: 'huyen_thanh_tri',
    province_code: 94,
  },
  {
    name: 'Vinh Chau Town',
    code: 950,
    division_type: 'Town',
    codename: 'thi_xa_vinh_chau',
    province_code: 94,
  },
  {
    name: 'Tran De District',
    code: 951,
    division_type: 'District',
    codename: 'huyen_tran_de',
    province_code: 94,
  },
  {
    name: 'Bac Lieu City',
    code: 954,
    division_type: 'City',
    codename: 'thanh_pho_bac_lieu',
    province_code: 95,
  },
  {
    name: 'Hong Dan District',
    code: 956,
    division_type: 'District',
    codename: 'huyen_hong_dan',
    province_code: 95,
  },
  {
    name: 'Phuoc Long District',
    code: 957,
    division_type: 'District',
    codename: 'huyen_phuoc_long',
    province_code: 95,
  },
  {
    name: 'Vinh Loi District',
    code: 958,
    division_type: 'District',
    codename: 'huyen_vinh_loi',
    province_code: 95,
  },
  {
    name: 'Gia Rai Town',
    code: 959,
    division_type: 'Town',
    codename: 'thi_xa_gia_rai',
    province_code: 95,
  },
  {
    name: 'Dong Hai District',
    code: 960,
    division_type: 'District',
    codename: 'huyen_dong_hai',
    province_code: 95,
  },
  {
    name: 'Hoa Binh District',
    code: 961,
    division_type: 'District',
    codename: 'huyen_hoa_binh',
    province_code: 95,
  },
  {
    name: 'Ca Mau City',
    code: 964,
    division_type: 'City',
    codename: 'thanh_pho_ca_mau',
    province_code: 96,
  },
  {
    name: 'U Minh District',
    code: 966,
    division_type: 'District',
    codename: 'huyen_u_minh',
    province_code: 96,
  },
  {
    name: 'Thoi Binh District',
    code: 967,
    division_type: 'District',
    codename: 'huyen_thoi_binh',
    province_code: 96,
  },
  {
    name: 'Tran Van Thoi District',
    code: 968,
    division_type: 'District',
    codename: 'huyen_tran_van_thoi',
    province_code: 96,
  },
  {
    name: 'Cai Noc District',
    code: 969,
    division_type: 'District',
    codename: 'huyen_cai_nuoc',
    province_code: 96,
  },
  {
    name: 'Dam Doi District',
    code: 970,
    division_type: 'District',
    codename: 'huyen_dam_doi',
    province_code: 96,
  },
  {
    name: 'Nam Can District',
    code: 971,
    division_type: 'District',
    codename: 'huyen_nam_can',
    province_code: 96,
  },
  {
    name: 'Phu Tan District',
    code: 972,
    division_type: 'District',
    codename: 'huyen_phu_tan',
    province_code: 96,
  },
  {
    name: 'Ngoc Hien District',
    code: 973,
    division_type: 'District',
    codename: 'huyen_ngoc_hien',
    province_code: 96,
  },
];

const convertItems = [...items].map(({ name, code, province_code }) => ({
  name,
  code,
  cityCode: province_code,
}));

const districts_en: District[] = [...convertItems].map((item, idx) => ({
  id: `DISTRICT_${idx}`,
  name: item.name,
  code: item.code,
  cityCode: item.cityCode,
  langCode: ELang.EN,
  createdAt: new Date(),
  updatedAt: new Date(),
}));

export default districts_en;
