import { Product } from '@prisma/client';
import { ELang } from '../../../src/common/enum/base';
import { EInventoryStatus, EProductStatus, EProductUnit } from '../../../src/modules/product/product.enum';

const items = [
  // Subcategory 1
  { name: 'Yellow Pumpkin', totalPrice: 49000, subCategoryId: 'SUBCATE_EN_1' },
  { name: 'Green Pumpkin', totalPrice: 25000, subCategoryId: 'SUBCATE_EN_1' },
  { name: 'Young Pumpkin', totalPrice: 25000, subCategoryId: 'SUBCATE_EN_1' },
  { name: 'Bottle Gourd', totalPrice: 15000, subCategoryId: 'SUBCATE_EN_1' },
  { name: 'Red Round Pumpkin', totalPrice: 13000, subCategoryId: 'SUBCATE_EN_1' },
  { name: 'Red Calabash Pumpkin', totalPrice: 14000, subCategoryId: 'SUBCATE_EN_1' },
  { name: 'Japanese Red Pumpkin', totalPrice: 29000, subCategoryId: 'SUBCATE_EN_1' },
  { name: 'Pumpkin Flower', totalPrice: 59000, subCategoryId: 'SUBCATE_EN_1' },
  { name: 'Chinese White Cabbage', totalPrice: 73000, subCategoryId: 'SUBCATE_EN_1' },
  { name: 'Da Lat White Cabbage', totalPrice: 85000, subCategoryId: 'SUBCATE_EN_1' },
  { name: 'Baby Bok Choy', totalPrice: 65000, subCategoryId: 'SUBCATE_EN_1' },
  { name: 'Chinese Green Cabbage', totalPrice: 65000, subCategoryId: 'SUBCATE_EN_1' },
  { name: 'Da Lat Green Cabbage', totalPrice: 55000, subCategoryId: 'SUBCATE_EN_1' },
  { name: 'Chrysanthemum Greens', totalPrice: 85000, subCategoryId: 'SUBCATE_EN_1' },
  { name: 'Chocolate Mint', totalPrice: 33000, subCategoryId: 'SUBCATE_EN_1' },
  { name: 'Fresh White Radish', totalPrice: 21000, subCategoryId: 'SUBCATE_EN_1' },
  { name: 'Calabash Gourd', totalPrice: 18000, subCategoryId: 'SUBCATE_EN_1' },
  { name: 'Sliced Banana Corn', totalPrice: 45000, subCategoryId: 'SUBCATE_EN_1' },
  { name: 'Heart-Shaped Cabbage', totalPrice: 27000, subCategoryId: 'SUBCATE_EN_1' },
  { name: 'White Cabbage', totalPrice: 145000, subCategoryId: 'SUBCATE_EN_1' },
  { name: 'Purple Cabbage', totalPrice: 33000, subCategoryId: 'SUBCATE_EN_1' },
  { name: 'American Corn', totalPrice: 21000, subCategoryId: 'SUBCATE_EN_1' },
  { name: 'Baby Corn', totalPrice: 23000, subCategoryId: 'SUBCATE_EN_1' },
  { name: 'Beef Tomato', totalPrice: 39000, subCategoryId: 'SUBCATE_EN_1' },
  { name: 'Yellow Cherry Tomato', totalPrice: 85000, subCategoryId: 'SUBCATE_EN_1' },
  { name: 'Chocolate Cherry Tomato', totalPrice: 65000, subCategoryId: 'SUBCATE_EN_1' },
  { name: 'Medium Red Cherry Tomato', totalPrice: 45000, subCategoryId: 'SUBCATE_EN_1' },
  { name: 'Large Rita Tomato', totalPrice: 30000, subCategoryId: 'SUBCATE_EN_1' },
  { name: 'Baby Carrot', totalPrice: 99000, subCategoryId: 'SUBCATE_EN_1' },
  { name: 'Chinese Carrot', totalPrice: 18000, subCategoryId: 'SUBCATE_EN_1' },
  { name: 'Da Lat Carrot', totalPrice: 21000, subCategoryId: 'SUBCATE_EN_1' },
  { name: 'Eggplant', totalPrice: 16000, subCategoryId: 'SUBCATE_EN_1' },
  { name: 'Chinese Broccoli', totalPrice: 33000, subCategoryId: 'SUBCATE_EN_1' },
  { name: 'Green Mustard Greens', totalPrice: 29000, subCategoryId: 'SUBCATE_EN_1' },
  { name: 'Rainbow Chard', totalPrice: 79000, subCategoryId: 'SUBCATE_EN_1' },
  { name: 'Dandelion Greens', totalPrice: 39000, subCategoryId: 'SUBCATE_EN_1' },
  { name: 'Sweet Mustard Greens', totalPrice: 24000, subCategoryId: 'SUBCATE_EN_1' },
  { name: 'Hong Kong Sweet Mustard Greens', totalPrice: 33000, subCategoryId: 'SUBCATE_EN_1' },
  { name: 'Chinese Flowering Cabbage', totalPrice: 23000, subCategoryId: 'SUBCATE_EN_1' },
  { name: 'Spoon Mustard Greens', totalPrice: 23000, subCategoryId: 'SUBCATE_EN_1' },
  // Subcategory 2
  { name: 'Frozen Corn from the United States VSafefood', totalPrice: 59000, subCategoryId: 'SUBCATE_EN_2' },
  { name: 'Pickled Mustard Greens', totalPrice: 31000, subCategoryId: 'SUBCATE_EN_2' },
  { name: 'Sliced Red Ginger', totalPrice: 122000, subCategoryId: 'SUBCATE_EN_2' },
  { name: 'Frozen Shoe String French Fries 7/7 Mydibel', totalPrice: 79000, subCategoryId: 'SUBCATE_EN_2' },
  { name: 'Frozen Waffle Cut Sweet Potatoes CRRROCK-N', totalPrice: 199000, subCategoryId: 'SUBCATE_EN_2' },
  { name: 'Straight Cut Frozen Potatoes Meito 10mm', totalPrice: 165000, subCategoryId: 'SUBCATE_EN_2' },
  { name: 'Kimchi by The Foods', totalPrice: 49000, subCategoryId: 'SUBCATE_EN_2' },
  { name: 'Kimchi by The Foods', totalPrice: 27000, subCategoryId: 'SUBCATE_EN_2' },
  { name: 'Sour Soup Cooking Tamarind', totalPrice: 19000, subCategoryId: 'SUBCATE_EN_2' },
  { name: 'Sour Bamboo Shoots', totalPrice: 27000, subCategoryId: 'SUBCATE_EN_2' },
  { name: 'Bamboo Leaves', totalPrice: 27000, subCategoryId: 'SUBCATE_EN_2' },
  { name: 'Sweet Bamboo Shoots', totalPrice: 27000, subCategoryId: 'SUBCATE_EN_2' },
  { name: 'Bamboo Sprouts', totalPrice: 44000, subCategoryId: 'SUBCATE_EN_2' },
  { name: 'Mixed Frozen Vegetables by VSafefood', totalPrice: 62000, subCategoryId: 'SUBCATE_EN_2' },
  { name: 'Lemongrass Paste', totalPrice: 21000, subCategoryId: 'SUBCATE_EN_2' },
  { name: 'Frozen Artichokes by VSafefood', totalPrice: 82000, subCategoryId: 'SUBCATE_EN_2' },
  { name: 'Fried Tofu', totalPrice: 5000, subCategoryId: 'SUBCATE_EN_2' },
  { name: 'Aburaage Tofu Skin Original Flavor', totalPrice: 31000, subCategoryId: 'SUBCATE_EN_2' },
  { name: 'Fresh Tofu Skin', totalPrice: 13000, subCategoryId: 'SUBCATE_EN_2' },
  { name: 'TA Flavored Tofu Skin', totalPrice: 13000, subCategoryId: 'SUBCATE_EN_2' },
  { name: 'White Tofu Skin', totalPrice: 5000, subCategoryId: 'SUBCATE_EN_2' },
  { name: 'Frozen Artichokes', totalPrice: 93000, subCategoryId: 'SUBCATE_EN_2' },
  // Subcategory 3
  { name: 'Mushroom Hot Pot', totalPrice: 29000, subCategoryId: 'SUBCATE_EN_3' },
  { name: 'White Oyster Mushroom', totalPrice: 39000, subCategoryId: 'SUBCATE_EN_3' },
  { name: 'Grey Oyster Mushroom', totalPrice: 64000, subCategoryId: 'SUBCATE_EN_3' },
  { name: 'Enoki Mushroom', totalPrice: 15000, subCategoryId: 'SUBCATE_EN_3' },
  { name: 'Golden Needle Mushroom', totalPrice: 14000, subCategoryId: 'SUBCATE_EN_3' },
  { name: 'Shiitake Mushroom', totalPrice: 14000, subCategoryId: 'SUBCATE_EN_3' },
  { name: 'Dried Cat Mushroom', totalPrice: 139000, subCategoryId: 'SUBCATE_EN_3' },
  { name: 'Butter Mushroom', totalPrice: 46000, subCategoryId: 'SUBCATE_EN_3' },
  { name: 'Brown Vietnamese Butter Mushroom', totalPrice: 48000, subCategoryId: 'SUBCATE_EN_3' },
  { name: 'Brown Enoki Mushroom', totalPrice: 14000, subCategoryId: 'SUBCATE_EN_3' },
  { name: 'White Enoki Mushroom', totalPrice: 14000, subCategoryId: 'SUBCATE_EN_3' },
  { name: 'Straw Mushroom', totalPrice: 135000, subCategoryId: 'SUBCATE_EN_3' },
  { name: 'White Snow Mushroom', totalPrice: 355000, subCategoryId: 'SUBCATE_EN_3' },
  { name: 'Dried Dong Quai Mushroom', totalPrice: 299000, subCategoryId: 'SUBCATE_EN_3' },
  { name: 'Dried Dong Quai Mushroom (Dried Morel Mushroom)', totalPrice: 39000, subCategoryId: 'SUBCATE_EN_3' },
  { name: 'Fresh Dong Quai Mushroom', totalPrice: 34000, subCategoryId: 'SUBCATE_EN_3' },
  { name: 'Chicken Drumstick Mushroom', totalPrice: 65000, subCategoryId: 'SUBCATE_EN_3' },
  // Subcategory 4
  { name: 'Booth Avocado', totalPrice: 74000, subCategoryId: 'SUBCATE_EN_4' },
  { name: 'Green Skin Pomelo', totalPrice: 45000, subCategoryId: 'SUBCATE_EN_4' },
  { name: 'Nam Roi Pomelo', totalPrice: 39000, subCategoryId: 'SUBCATE_EN_4' },
  { name: 'Sweet Orange', totalPrice: 17000, subCategoryId: 'SUBCATE_EN_4' },
  { name: 'Australian Late Gold Orange', totalPrice: 89000, subCategoryId: 'SUBCATE_EN_4' },
  { name: 'Sweet Orange', totalPrice: 16000, subCategoryId: 'SUBCATE_EN_4' },
  { name: 'Seeded Lime', totalPrice: 39000, subCategoryId: 'SUBCATE_EN_4' },
  { name: 'Purple Passion Fruit', totalPrice: 24000, subCategoryId: 'SUBCATE_EN_4' },
  { name: 'Seedless Lime', totalPrice: 29000, subCategoryId: 'SUBCATE_EN_4' },
  { name: 'Seedless Lime Type 2', totalPrice: 27000, subCategoryId: 'SUBCATE_EN_4' },
  { name: 'Cantonese Lime', totalPrice: 85000, subCategoryId: 'SUBCATE_EN_4' },
  { name: 'Yellow Lime', totalPrice: 79000, subCategoryId: 'SUBCATE_EN_4' },
  { name: 'South African Yellow Lime', totalPrice: 89000, subCategoryId: 'SUBCATE_EN_4' },
  { name: 'Bitter Melon', totalPrice: 19000, subCategoryId: 'SUBCATE_EN_4' },
  { name: 'Bumpy Banana', totalPrice: 49000, subCategoryId: 'SUBCATE_EN_4' },
  { name: 'Aged Banana', totalPrice: 19000, subCategoryId: 'SUBCATE_EN_4' },
  { name: 'Laba Banana', totalPrice: 21000, subCategoryId: 'SUBCATE_EN_4' },
  { name: 'Porcelain Banana', totalPrice: 19000, subCategoryId: 'SUBCATE_EN_4' },
  { name: 'Thai Coconut', totalPrice: 15000, subCategoryId: 'SUBCATE_EN_4' },
  { name: 'Korean Strawberry', totalPrice: 199000, subCategoryId: 'SUBCATE_EN_4' },
  { name: 'Frozen Japanese Strawberries', totalPrice: 189000, subCategoryId: 'SUBCATE_EN_4' },
  { name: 'Frozen Fresh Strawberries Chao Da Lat', totalPrice: 85000, subCategoryId: 'SUBCATE_EN_4' },
  { name: 'Frozen Strawberries by V.Safefood', totalPrice: 169000, subCategoryId: 'SUBCATE_EN_4' },
  { name: 'Seedless Watermelon', totalPrice: 19000, subCategoryId: 'SUBCATE_EN_4' },
  { name: 'Yellow Flesh Watermelon', totalPrice: 19000, subCategoryId: 'SUBCATE_EN_4' },
  { name: 'Watermelon', totalPrice: 17000, subCategoryId: 'SUBCATE_EN_4' },
  { name: 'TL3 Netted Melon Flesh Yellow', totalPrice: 45000, subCategoryId: 'SUBCATE_EN_4' },
  { name: 'Sour Sop', totalPrice: 59000, subCategoryId: 'SUBCATE_EN_4' },
  { name: 'Frozen Red Sticky Rice Basket by V.Safefood', totalPrice: 249000, subCategoryId: 'SUBCATE_EN_4' },
  { name: 'Sugared Orange', totalPrice: 53000, subCategoryId: 'SUBCATE_EN_4' },
  { name: 'Red Dragon Fruit Flesh', totalPrice: 33000, subCategoryId: 'SUBCATE_EN_4' },
  { name: 'White Dragon Fruit', totalPrice: 33000, subCategoryId: 'SUBCATE_EN_4' },
  { name: 'Fragrant Fruit', totalPrice: 18000, subCategoryId: 'SUBCATE_EN_4' },
  { name: 'Fragrant Fruit Type 2', totalPrice: 16000, subCategoryId: 'SUBCATE_EN_4' },
  // Subcategory 5
  { name: 'Frozen Ba Huan Chicken Feet', totalPrice: 59000, subCategoryId: 'SUBCATE_EN_5' },
  { name: 'Fresh CP Chicken Wings', totalPrice: 97000, subCategoryId: 'SUBCATE_EN_5' },
  { name: 'Frozen Ba Huan Chicken Wings', totalPrice: 85000, subCategoryId: 'SUBCATE_EN_5' },
  { name: 'Frozen CP Chicken Liver', totalPrice: 33000, subCategoryId: 'SUBCATE_EN_5' },
  { name: 'Frozen CP Chicken Thighs', totalPrice: 65000, subCategoryId: 'SUBCATE_EN_5' },
  { name: 'Frozen CP Chicken Gizzard', totalPrice: 49000, subCategoryId: 'SUBCATE_EN_5' },
  { name: 'Frozen CP Chicken Neck', totalPrice: 25000, subCategoryId: 'SUBCATE_EN_5' },
  { name: 'Frozen CP Chicken Cartilage', totalPrice: 119000, subCategoryId: 'SUBCATE_EN_5' },
  { name: 'Frozen CP Chicken Heart', totalPrice: 53000, subCategoryId: 'SUBCATE_EN_5' },
  { name: 'Frozen CP Chicken Bones', totalPrice: 29000, subCategoryId: 'SUBCATE_EN_5' },
  { name: 'Fresh CP Chicken Thighs', totalPrice: 77000, subCategoryId: 'SUBCATE_EN_5' },
  { name: 'Frozen Ba Huan Chicken Thighs', totalPrice: 72000, subCategoryId: 'SUBCATE_EN_5' },
  { name: 'Frozen CP Chicken Thighs', totalPrice: 78000, subCategoryId: 'SUBCATE_EN_5' },
  { name: 'Fresh CP Deboned Chicken Thighs', totalPrice: 88000, subCategoryId: 'SUBCATE_EN_5' },
  { name: 'Frozen CP Deboned Chicken Thighs', totalPrice: 89000, subCategoryId: 'SUBCATE_EN_5' },
  { name: 'Frozen CP Chicken Drumsticks', totalPrice: 99000, subCategoryId: 'SUBCATE_EN_5' },
  { name: 'Fresh CP Skinless Chicken Thighs', totalPrice: 85000, subCategoryId: 'SUBCATE_EN_5' },
  { name: 'Frozen Ba Huan Skinless Chicken Thighs', totalPrice: 78000, subCategoryId: 'SUBCATE_EN_5' },
  { name: 'Frozen CP Skinless Chicken Thighs', totalPrice: 86000, subCategoryId: 'SUBCATE_EN_5' },
  { name: 'Frozen CP Chicken Cartilage Thighs', totalPrice: 164000, subCategoryId: 'SUBCATE_EN_5' },
  // Subcategory 6
  { name: 'Frozen 2mm Sliced NH Foods Pork Belly', totalPrice: 249000, subCategoryId: 'SUBCATE_EN_6' },
  { name: 'Smoked NH Foods Pork Belly', totalPrice: 199000, subCategoryId: 'SUBCATE_EN_6' },
  { name: 'Frozen XL Le Gourmet Smoked Pork Belly', totalPrice: 229000, subCategoryId: 'SUBCATE_EN_6' },
  { name: 'Frozen CP Sliced Pork Collar', totalPrice: 125000, subCategoryId: 'SUBCATE_EN_6' },
  { name: 'Frozen Pork Giò Sống by CP', totalPrice: 159000, subCategoryId: 'SUBCATE_EN_6' },
  { name: 'Frozen NH Foods Pork Sirloin', totalPrice: 145000, subCategoryId: 'SUBCATE_EN_6' },
  { name: 'Frozen CP Pork Shoulder', totalPrice: 89000, subCategoryId: 'SUBCATE_EN_6' },
  { name: 'Frozen CP Pork Thigh', totalPrice: 89000, subCategoryId: 'SUBCATE_EN_6' },
  { name: 'Frozen CP Ground Pork', totalPrice: 95000, subCategoryId: 'SUBCATE_EN_6' },
  { name: 'Frozen CP Pork Bones', totalPrice: 77000, subCategoryId: 'SUBCATE_EN_6' },
  // Subcategory 7
  { name: 'Frozen US Beef Belly Slices', totalPrice: 135000, subCategoryId: 'SUBCATE_EN_7' },
  { name: 'Frozen MRT Beef Belly Slices', totalPrice: 129000, subCategoryId: 'SUBCATE_EN_7' },
  { name: 'Frozen MRT Shaking Beef', totalPrice: 219000, subCategoryId: 'SUBCATE_EN_7' },
  { name: 'Frozen MRT Ground Beef', totalPrice: 195000, subCategoryId: 'SUBCATE_EN_7' },
  { name: 'Frozen MRT Imported Sirloin', totalPrice: 179000, subCategoryId: 'SUBCATE_EN_7' },
  { name: 'Frozen Australian Ground Beef', totalPrice: 195000, subCategoryId: 'SUBCATE_EN_7' },
  // Subcategory 8
  { name: 'Ba Huan Salted Duck Egg Yolk', totalPrice: 265000, subCategoryId: 'SUBCATE_EN_8' },
  { name: 'Ba Huan Quail Eggs', totalPrice: 26000, subCategoryId: 'SUBCATE_EN_8' },
  { name: 'Ba Huan Size L Chicken Eggs', totalPrice: 30000, subCategoryId: 'SUBCATE_EN_8' },
  { name: 'Ba Huan Size M Chicken Eggs', totalPrice: 29000, subCategoryId: 'SUBCATE_EN_8' },
  { name: 'CP Size L Chicken Eggs', totalPrice: 30000, subCategoryId: 'SUBCATE_EN_8' },
  { name: 'CP Size XL Chicken Eggs', totalPrice: 31000, subCategoryId: 'SUBCATE_EN_8' },
  { name: 'GFoods 55g Chicken Eggs', totalPrice: 27000, subCategoryId: 'SUBCATE_EN_8' },
  { name: 'GFoods 60g Chicken Eggs', totalPrice: 29000, subCategoryId: 'SUBCATE_EN_8' },
  { name: 'Ba Huan Duck Eggs', totalPrice: 65000, subCategoryId: 'SUBCATE_EN_8' },
  { name: 'Ba Huan Salted Duck Eggs', totalPrice: 23000, subCategoryId: 'SUBCATE_EN_8' },
  { name: 'Ba Huan Duck Eggs', totalPrice: 40000, subCategoryId: 'SUBCATE_EN_8' },
  // Subcategory 9
  { name: 'XL Le Gourmet Square Shoulder Sausage', totalPrice: 159000, subCategoryId: 'SUBCATE_EN_9' },
  { name: 'Le Gourmet Cocktail Sausage', totalPrice: 82000, subCategoryId: 'SUBCATE_EN_9' },
  { name: 'NH Foods Standard Smoked Sausage', totalPrice: 57000, subCategoryId: 'SUBCATE_EN_9' },
  { name: 'NH Foods Saigon Smoked Sausage', totalPrice: 76000, subCategoryId: 'SUBCATE_EN_9' },
  { name: 'Le Gourmet German 10cm Sausage', totalPrice: 72000, subCategoryId: 'SUBCATE_EN_9' },
  // Subcategory 10
  { name: 'Dasani Water 1.5L', totalPrice: 39000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_EN_10' },
  { name: 'Alba Sparkling Mineral Water (Glass Bottle)', totalPrice: 449000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_EN_10' },
  { name: 'Alba Still Mineral Water (Glass Bottle)', totalPrice: 409000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_EN_10' },
  { name: 'La Vie Mineral Water 500ml', totalPrice: 79000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_EN_10' },
  { name: 'Aquafina Carbonated Soda 320ml', totalPrice: 139000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_EN_10' },
  { name: 'Schweppes Carbonated Soda', totalPrice: 135000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_EN_10' },
  { name: 'Alba Sparkling Mineral Water (Plastic Bottle)', totalPrice: 139000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_EN_10' },
  { name: 'Alba Still Mineral Water (Plastic Bottle)', totalPrice: 114000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_EN_10' },
  { name: 'Aquafina Purified Water 500ml', totalPrice: 99000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_EN_10' },
  { name: 'SATORI Purified Water 500ml', totalPrice: 78000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_EN_10' },
  { name: 'La Vie Mineral Water 500ml x 30 Bottles', totalPrice: 79000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_EN_10' },
  { name: 'Singha Carbonated Soda 325ml', totalPrice: 205000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_EN_10' },
  { name: 'Singha Carbonated Soda 325ml', totalPrice: 939000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_EN_10' },
  // Subcategory 11
  { name: 'Coca-Cola 320ml', totalPrice: 199000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_EN_11' },
  { name: 'Coca-Cola Light 320ml', totalPrice: 195000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_EN_11' },
  { name: 'Coca-Cola Zero 320ml', totalPrice: 198000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_EN_11' },
  { name: 'Fanta Orange 320ml', totalPrice: 165000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_EN_11' },
  { name: 'Revive Isotonic Drink 500ml', totalPrice: 189000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_EN_11' },
  { name: 'Revive Lemon Salt Isotonic Drink', totalPrice: 179000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_EN_11' },
  { name: '7UP Carbonated Drink 320ml', totalPrice: 192000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_EN_11' },
  { name: 'Pepsi Carbonated Drink 320ml', totalPrice: 195000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_EN_11' },
  { name: 'Schweppes Tonic Water 320ml', totalPrice: 155000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_EN_11' },
  { name: 'Carabao Energy Drink 250ml', totalPrice: 179000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_EN_11' },
  { name: 'RedBull Energy Drink 250ml', totalPrice: 225000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_EN_11' },
  { name: 'Sting Strawberry Energy Drink 320ml', totalPrice: 205000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_EN_11' },
  { name: 'Twister Orange Juice 320ml', totalPrice: 199000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_EN_11' },
  { name: 'Schweppes Dry Ginger Ale 320ml', totalPrice: 195000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_EN_11' },
  { name: 'Sprite 320ml', totalPrice: 178000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_EN_11' },
  // Subcategory 12
  { name: 'Morning Rice Morning Rice Water 1.5L', totalPrice: 49000, unit: EProductUnit.BOTTLE, subCategoryId: 'SUBCATE_EN_12' },
  { name: 'VFresh Peach Nectar 1L', totalPrice: 35000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_EN_12' },
  { name: 'VFresh 100% Orange Juice 1L', totalPrice: 41000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_EN_12' },
  { name: 'VFresh 100% Apple Juice 1L', totalPrice: 39000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_EN_12' },
  { name: 'VFresh Pomegranate Nectar 1L', totalPrice: 41000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_EN_12' },
  { name: 'Cocofresh Fresh Coconut Water 1L', totalPrice: 35000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_EN_12' },
  { name: 'Malee Mixed Orange and Grapefruit Juice 1L', totalPrice: 63000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_EN_12' },
  { name: 'Prima 100% Tomato Juice 1L', totalPrice: 47000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_EN_12' },
  { name: 'Malee Pineapple Juice 1L', totalPrice: 63000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_EN_12' },
  { name: 'Prima 100% Mixed Fruit Juice 1L', totalPrice: 47000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_EN_12' },
  { name: 'Malee Mixed Pomegranate and Mixed Fruit Juice 1L', totalPrice: 63000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_EN_12' },
  { name: 'Prima 16% Blueberry Juice 1L', totalPrice: 52000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_EN_12' },
  { name: 'Prima 50% Peach Nectar Juice 1L', totalPrice: 47000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_EN_12' },
  { name: 'Malee Grape Juice 1L', totalPrice: 63000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_EN_12' },
  { name: 'Malee Apple Juice 1L', totalPrice: 63000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_EN_12' },
  { name: 'Malee Lychee Juice 1L', totalPrice: 63000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_EN_12' },
  { name: 'Prima 100% Mixed Fruit Juice 1L', totalPrice: 529000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_EN_12' },
  { name: 'Cocofresh Fresh Coconut Water 1L', totalPrice: 399000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_EN_12' },
  { name: 'Morning Rice Morning Rice Water 1.5L', totalPrice: 529000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_EN_12' },
  { name: 'VFresh Peach Nectar 1L', totalPrice: 399000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_EN_12' },
  { name: 'VFresh 100% Orange Juice 1L', totalPrice: 479000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_EN_12' },
  { name: 'VFresh 100% Apple Juice 1L', totalPrice: 449000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_EN_12' },
  { name: 'VFresh Pomegranate Nectar 1L', totalPrice: 469000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_EN_12' },
  { name: 'Prima 100% Tomato Juice 1L', totalPrice: 529000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_EN_12' },
  { name: 'Prima 100% Pineapple Juice 1L', totalPrice: 529000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_EN_12' },
  { name: 'Prima 16% Blueberry Juice 1L', totalPrice: 599000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_EN_12' },
  { name: 'Prima 50% Peach Nectar Juice 1L', totalPrice: 529000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_EN_12' },
  // Subcategory 13
  { name: 'Trung Nguyen 1 Coffee 500g', totalPrice: 79000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_EN_13' },
  { name: 'Trung Nguyen S Coffee 500g', totalPrice: 69000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_EN_13' },
  { name: 'Lacaph Traditional Espresso Blend Whole Bean 1kg', totalPrice: 245000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_EN_13' },
  { name: 'Lacaph Traditional Espresso Blend Ground 1kg', totalPrice: 245000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_EN_13' },
  { name: 'Lacaph Traditional Filter Blend Whole Bean 1kg', totalPrice: 259000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_EN_13' },
  { name: 'Lacaph Traditional Filter Blend Ground 1kg', totalPrice: 259000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_EN_13' },
  { name: 'Lacaph Traditional Phin Blend Whole Bean 1kg', totalPrice: 215000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_EN_13' },
  { name: 'Lacaph Traditional Phin Blend Ground 1kg', totalPrice: 215000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_EN_13' },
  { name: 'Trung Nguyen 1 Creative Coffee 500g', totalPrice: 99000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_EN_13' },
  { name: 'Trung Nguyen S Life Coffee (Brown) 500g', totalPrice: 99000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_EN_13' },
  // Subcategory 14
  { name: 'KAWAMI Genmaicha Tea Powder 100g', totalPrice: 159000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_EN_14' },
  { name: 'KAWAMI Houjicha Tea Powder 100g', totalPrice: 159000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_EN_14' },
  { name: 'Jasmine Scented Matcha Tea Powder 1kg', totalPrice: 759000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_EN_14' },
  { name: 'KAWAMI Matcha Green Tea Powder 100g', totalPrice: 159000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_EN_14' },
  { name: 'Dilmah Earl Grey Tea 1.5g', totalPrice: 45000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_EN_14' },
  { name: 'Dilmah Peppermint Tea 1.5g', totalPrice: 45000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_EN_14' },
  { name: 'Dilmah Lemon Tea 1.5g', totalPrice: 44000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_EN_14' },
  { name: 'Dilmah Strawberry Tea 1.5g', totalPrice: 45000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_EN_14' },
  { name: 'Dilmah Ginger and Honey Tea 1.5g', totalPrice: 45000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_EN_14' },
  { name: 'Dilmah Chamomile Tea 1.5g', totalPrice: 75000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_EN_14' },
  { name: 'Dilmah Jasmine Tea 1.5g', totalPrice: 75000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_EN_14' },
  { name: 'Dilmah Mixed Berry Tea 1.5g', totalPrice: 44000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_EN_14' },
  { name: 'Dilmah Peppermint Herbal Tea 1.5g', totalPrice: 72000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_EN_14' },
  { name: 'Dilmah Apple Tea 1.5g', totalPrice: 44000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_EN_14' },
  { name: 'Dilmah Lychee Tea 1.5g', totalPrice: 72000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_EN_14' },
  { name: 'Dilmah Oolong Tea 1.5g', totalPrice: 55000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_EN_14' },
  { name: 'Dilmah English Breakfast Tea 1.5g', totalPrice: 72000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_EN_14' },
  { name: 'Dilmah Peach Tea 1.5g', totalPrice: 55000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_EN_14' },
  { name: 'LongBeach Thai Green Tea', totalPrice: 89000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_EN_14' },
  { name: 'LongBeach Thai Red Tea', totalPrice: 59000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_EN_14' },
  { name: 'Fuzetea Peach and Chia Seeds Tea 350ml', totalPrice: 149000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_EN_14' },
  { name: 'Fuzetea Peach and Chia Seeds Tea 450ml', totalPrice: 189000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_EN_14' },
  // Subcategory 15
  { name: 'Rice Flour Banh Canh', totalPrice: 21000, subCategoryId: 'SUBCATE_EN_15' },
  { name: 'Clear Flour Banh Canh', totalPrice: 17000, subCategoryId: 'SUBCATE_EN_15' },
  { name: 'Small Fresh Pho Noodles', totalPrice: 16000, subCategoryId: 'SUBCATE_EN_15' },
  { name: 'Safoco Rice Vermicelli', totalPrice: 33000, subCategoryId: 'SUBCATE_EN_15' },
  { name: 'Thick Vermicelli (Bun Bo Hue)', totalPrice: 15000, subCategoryId: 'SUBCATE_EN_15' },
  { name: 'Fresh Rice Vermicelli', totalPrice: 15000, subCategoryId: 'SUBCATE_EN_15' },
  { name: 'Firm Hu Tieu Noodles', totalPrice: 29000, subCategoryId: 'SUBCATE_EN_15' },
  { name: 'Soft Hu Tieu Noodles', totalPrice: 19000, subCategoryId: 'SUBCATE_EN_15' },
  { name: 'Pietro Coricelli Linguine Pasta', totalPrice: 39000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_EN_15' },
  { name: 'Yamamori Soba Noodles', totalPrice: 51000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_EN_15' },
  { name: 'Golden Farm Spaghetti', totalPrice: 29000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_EN_15' },
  { name: 'Pietro Coricelli Spaghetti Pasta', totalPrice: 39000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_EN_15' },
  { name: 'Meizan Premium Small Egg Noodles', totalPrice: 29000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_EN_15' },
  { name: 'Safoco Small Egg Noodles', totalPrice: 29000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_EN_15' },
  { name: 'Safoco Premium Egg Noodles', totalPrice: 25000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_EN_15' },
  { name: 'Yamamori Udon Noodles', totalPrice: 39000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_EN_15' },
  { name: 'Safoco Premium Stir-fry Noodles', totalPrice: 35000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_EN_15' },
  { name: 'Pietro Coricelli Fusilli Pasta', totalPrice: 42000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_EN_15' },
  { name: 'Safoco Large Tubular Noodles', totalPrice: 25000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_EN_15' },
  { name: 'Vietsan Brown Rice Pho', totalPrice: 18000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_EN_15' },
  { name: 'Safoco Rice Vermicelli 500g', totalPrice: 309000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_EN_15' },
  { name: 'Pietro Coricelli Spaghetti Pasta 500g', totalPrice: 869000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_EN_15' },
  { name: 'Safoco Small Egg Noodles 500g', totalPrice: 559000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_EN_15' },
  { name: 'Safoco Premium Egg Noodles 400g', totalPrice: 349000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_EN_15' },
  { name: 'Safoco Large Tubular Noodles 400g', totalPrice: 605000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_EN_15' },
  // Subcategory 16
  { name: 'Tài Ký Banh Xeo Flour 400g', totalPrice: 18000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_EN_16' },
  { name: 'Meizan Corn Flour 1kg', totalPrice: 32000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_EN_16' },
  { name: 'Takoky Corn Flour 1kg', totalPrice: 39000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_EN_16' },
  { name: 'Taky Corn Flour 150g', totalPrice: 11000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_EN_16' },
  { name: 'Meizan Crispy Frying Flour 1kg', totalPrice: 42000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_EN_16' },
  { name: 'Panko Crispy Frying Flour 500g', totalPrice: 19000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_EN_16' },
  { name: 'Tài Ký Crispy Frying Flour 1kg', totalPrice: 47000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_EN_16' },
  { name: 'Panko Crispy Coating Flour 1kg', totalPrice: 55000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_EN_16' },
  { name: 'Takoky Crispy Coating Flour 1kg', totalPrice: 61000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_EN_16' },
  { name: 'Bakers Choice All-Purpose Flour 1kg No. 13', totalPrice: 27000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_EN_16' },
  { name: 'Bakers Choice All-Purpose Flour 1kg No. 8', totalPrice: 27000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_EN_16' },
  { name: 'Bakers Choice All-Purpose Flour 1kg No. 11', totalPrice: 26000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_EN_16' },
  { name: 'Tao Do All-Purpose Flour 1kg (Flour No. 8)', totalPrice: 24000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_EN_16' },
  { name: 'Tài Ký Tapioca Starch 1kg', totalPrice: 34000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_EN_16' },
  { name: 'Tài Ký Tapioca Starch 400g', totalPrice: 15000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_EN_16' },
  { name: 'Meizan All-Purpose Flour 1kg', totalPrice: 29000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_EN_16' },
  { name: 'Tài Ký Glutinous Rice Starch 400g', totalPrice: 21000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_EN_16' },
  { name: 'Panko Corn Starch 150g', totalPrice: 7000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_EN_16' },
  { name: 'EU Food Potato Starch 400g', totalPrice: 39000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_EN_16' },
  // Subcategory 17
  { name: 'Ngoc Troi Bach Duong Rice 5.5kg', totalPrice: 119000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_EN_17' },
  { name: 'Ngoc Troi Thien Long Rice 5kg', totalPrice: 115000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_EN_17' },
  { name: 'Ngoc Troi Tien Nu Rice 5.5kg', totalPrice: 145000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_EN_17' },
  { name: 'Neptune Yellow Label Rice 5kg', totalPrice: 119000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_EN_17' },
  { name: 'Fuji Japanese Rice 5 kg', totalPrice: 191000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_EN_17' },
  { name: 'Dragon Blood Brown Rice 2kg', totalPrice: 59000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_EN_17' },
  // Subcategory 18
  { name: 'Golden Farm Peanut Butter Crunch 510g', totalPrice: 85000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_EN_18' },
  { name: 'Golden Farm Smooth Peanut Butter 340g', totalPrice: 63000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_EN_18' },
  { name: 'Golden Farm Smooth Peanut Butter 510g', totalPrice: 85000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_EN_18' },
  { name: 'Jif Smooth Peanut Butter 454g', totalPrice: 119000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_EN_18' },
  { name: 'Del Monte Corn in a Can 420g', totalPrice: 36000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_EN_18' },
  { name: 'Annalisa Peeled Whole Tomatoes 800g', totalPrice: 78000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_EN_18' },
  { name: 'Annalisa Pizza Sauce Cut Tomato 400g', totalPrice: 39000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_EN_18' },
  { name: 'Castello Peeled Whole Tomatoes 400g', totalPrice: 33000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_EN_18' },
  { name: 'Casa Rinaldi Peeled Whole Tomatoes 2.55kg', totalPrice: 215000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_EN_18' },
  { name: 'Annalisa Round Tomatoes Pomodorini 400g', totalPrice: 49000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_EN_18' },
  { name: 'Annalisa Concentrated Tomato Paste 400g', totalPrice: 79000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_EN_18' },
  { name: '555 Oil-Soaked Mackerel 155g', totalPrice: 18000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_EN_18' },
  { name: 'Century Tuna Soya Oil-Soaked 184g', totalPrice: 41000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_EN_18' },
  { name: 'Century Tuna Sliced Soya Oil-Soaked 170g', totalPrice: 39000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_EN_18' },
  { name: 'Century Tuna Sliced Soya Oil-Soaked 170g', totalPrice: 53000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_EN_18' },
  { name: 'Xim Mom Cooks Coconut Milk 400ml', totalPrice: 28000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_EN_18' },
  { name: 'Tulip Pork Luncheon Meat 200g', totalPrice: 51000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_EN_18' },
  { name: 'Tulip Pork Luncheon Meat 340g', totalPrice: 79000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_EN_18' },
  { name: 'Hormel Spam Smoked Ham 340g', totalPrice: 119000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_EN_18' },
  { name: 'Hormel Spam Less Sodium 340g', totalPrice: 105000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_EN_18' },
  { name: 'Tulip Chicken Cocktail Sausages 405g', totalPrice: 75000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_EN_18' },
  // Subcategory 19
  { name: 'Peeled Sesame Seeds Vietsan 150g', totalPrice: 19000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_EN_19' },
  { name: 'Black Sesame Seeds Vietsan 150g', totalPrice: 18000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_EN_19' },
  { name: 'Dried Apricots Atlas 1kg', totalPrice: 399000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_EN_19' },
  { name: 'Dried Apple Slices', totalPrice: 69000, unit: EProductUnit.KG, subCategoryId: 'SUBCATE_EN_19' },
  { name: 'Red Fuji Apples (Medium Size)', totalPrice: 75000, unit: EProductUnit.KG, subCategoryId: 'SUBCATE_EN_19' },
  { name: 'Vietsan Peanuts 500g', totalPrice: 39000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_EN_19' },
  { name: 'Vietsan Green Beans 500g', totalPrice: 27000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_EN_19' },
  { name: 'Vietsan Black Beans 500g', totalPrice: 28000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_EN_19' },
  { name: 'Vietsan Red Beans 500g', totalPrice: 35000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_EN_19' },
  // Subcategory 20
  { name: 'O!Sajang Cheese Flavored Seasoning Powder 250g', totalPrice: 53000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_EN_20' },
  { name: 'Lee Kum Kee Vegetarian Oyster Sauce 510g', totalPrice: 52000, unit: EProductUnit.BOTTLE, subCategoryId: 'SUBCATE_EN_20' },
  { name: 'Lee Kum Kee Sesame Oil 207ml', totalPrice: 76000, unit: EProductUnit.BOTTLE, subCategoryId: 'SUBCATE_EN_20' },
  { name: 'Lee Kum Kee Sesame Oil 750ml', totalPrice: 249000, unit: EProductUnit.BOTTLE, subCategoryId: 'SUBCATE_EN_20' },
  { name: 'Lee Kum Kee Chili Oil 207ml', totalPrice: 56000, unit: EProductUnit.BOTTLE, subCategoryId: 'SUBCATE_EN_20' },
  { name: 'Nosafood Whole Cloves 500g', totalPrice: 229000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_EN_20' },
  { name: 'Knorr Meat and Bone Broth Seasoning 5kg', totalPrice: 279000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_EN_20' },
  { name: 'Nosafood Clove Seeds 110g', totalPrice: 79000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_EN_20' },
  { name: 'Nosafood Colored Cashews 500g', totalPrice: 69000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_EN_20' },
  { name: 'Nosafood Mint Leaves 90g', totalPrice: 65000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_EN_20' },
  { name: 'Nosafood Basil Leaves 50g', totalPrice: 35000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_EN_20' },
  { name: 'Bac Lieu Coarse Salt 500g', totalPrice: 4000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_EN_20' },
  { name: 'Sosal Group Natural Sea Salt 1kg', totalPrice: 7000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_EN_20' },
  { name: 'EWALD Gelatine Leaves 1kg', totalPrice: 799000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_EN_20' },
  { name: 'Nosafood Thyme Leaves 110g', totalPrice: 99000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_EN_20' },
  { name: 'Nosafood Parsley Leaves 15g', totalPrice: 35000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_EN_20' },
  { name: 'Nosafood Cinnamon Leaves 140g', totalPrice: 79000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_EN_20' },
  { name: 'Knorr Pork Broth Base 1.5kg', totalPrice: 369000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_EN_20' },
  // Subcategory 21
  { name: 'Cholimex Soy Sauce 350ml', totalPrice: 21000, unit: EProductUnit.BOTTLE, subCategoryId: 'SUBCATE_EN_21' },
  { name: 'Maggi Soy Sauce 1.2kg', totalPrice: 75000, unit: EProductUnit.BOTTLE, subCategoryId: 'SUBCATE_EN_21' },
  { name: 'Hon Mirin Umami Seasoning 880ml', totalPrice: 72000, unit: EProductUnit.BOTTLE, subCategoryId: 'SUBCATE_EN_21' },
  { name: 'Ryorishu Umami Seasoning 880ml', totalPrice: 72000, unit: EProductUnit.BOTTLE, subCategoryId: 'SUBCATE_EN_21' },
  { name: 'Crystal Yellow Mustard 454g', totalPrice: 94000, unit: EProductUnit.BOTTLE, subCategoryId: 'SUBCATE_EN_21' },
  { name: 'Nam Ngư Fish Sauce 750ml', totalPrice: 49000, unit: EProductUnit.BOTTLE, subCategoryId: 'SUBCATE_EN_21' },
  { name: 'Nam Ngư Fish Sauce Super Saver 4.8L', totalPrice: 74000, unit: EProductUnit.BOTTLE, subCategoryId: 'SUBCATE_EN_21' },
  { name: 'Nam Ngư Fish Sauce Second Grade 900ml', totalPrice: 24000, unit: EProductUnit.BOTTLE, subCategoryId: 'SUBCATE_EN_21' },
  { name: 'Huong Viet Soy Sauce 500ml', totalPrice: 7000, unit: EProductUnit.BOTTLE, subCategoryId: 'SUBCATE_EN_21' },
  { name: 'Maggi Concentrated Soy Sauce 700ml', totalPrice: 37000, unit: EProductUnit.BOTTLE, subCategoryId: 'SUBCATE_EN_21' },
  { name: 'Tam Thai Tu Soy Sauce 500ml', totalPrice: 8000, unit: EProductUnit.BOTTLE, subCategoryId: 'SUBCATE_EN_21' },
  { name: 'Yamasa Soy Sauce 1L', totalPrice: 89000, unit: EProductUnit.BOTTLE, subCategoryId: 'SUBCATE_EN_21' },
  { name: 'Maggi Mild Soy Sauce 700ml', totalPrice: 30000, unit: EProductUnit.BOTTLE, subCategoryId: 'SUBCATE_EN_21' },
  { name: 'Sugo Al Basilico Basil Sauce Annalisa 350g', totalPrice: 81000, unit: EProductUnit.BOTTLE, subCategoryId: 'SUBCATE_EN_21' },
  { name: 'Crystal Steak Sauce 284g', totalPrice: 89000, unit: EProductUnit.BOTTLE, subCategoryId: 'SUBCATE_EN_21' },
  { name: 'Crystal Worcestershire Sauce 295ml', totalPrice: 95000, unit: EProductUnit.BOTTLE, subCategoryId: 'SUBCATE_EN_21' },
  { name: 'Cholimex Tomato Sauce 2.1 kg', totalPrice: 68000, unit: EProductUnit.BOTTLE, subCategoryId: 'SUBCATE_EN_21' },
  { name: 'Cholimex Tomato Sauce 830g', totalPrice: 32000, unit: EProductUnit.BOTTLE, subCategoryId: 'SUBCATE_EN_21' },
  { name: 'Lee Kum Kee Chili Sauce 226g', totalPrice: 52000, unit: EProductUnit.BOTTLE, subCategoryId: 'SUBCATE_EN_21' },
  { name: 'Cholimex Black Bean Sauce 230g', totalPrice: 11000, unit: EProductUnit.BOTTLE, subCategoryId: 'SUBCATE_EN_21' },
  { name: 'Cholimex Chili Sauce 2.1kg', totalPrice: 68000, unit: EProductUnit.BOTTLE, subCategoryId: 'SUBCATE_EN_21' },
  { name: 'Cholimex Chili Sauce 830g', totalPrice: 31000, unit: EProductUnit.BOTTLE, subCategoryId: 'SUBCATE_EN_21' },
  { name: 'Cholimex Sriracha Chili Sauce 520g', totalPrice: 24000, unit: EProductUnit.BOTTLE, subCategoryId: 'SUBCATE_EN_21' },
  { name: 'Golden Farm Mustard Sauce 250g', totalPrice: 36000, unit: EProductUnit.BOTTLE, subCategoryId: 'SUBCATE_EN_21' },
  { name: 'Cholimex Soy Sauce 350g', totalPrice: 479000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_EN_21' },
  { name: 'Maggi Soy Sauce 1.2kg', totalPrice: 569000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_EN_21' },
  { name: 'Japanese Flavor Mayonnaise 1kg', totalPrice: 1069000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_EN_21' },
  { name: 'Nam Ngư Fish Sauce 750ml', totalPrice: 829000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_EN_21' },
  { name: 'Nam Ngư Fish Sauce Super Saver 4.8L', totalPrice: 279000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_EN_21' },
  { name: 'Nam Ngư Fish Sauce Second Grade (15*900ml)', totalPrice: 349000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_EN_21' },
  // Subcategory 22
  { name: 'Cai Lan Cooking Oil 25kg', totalPrice: 759000, unit: EProductUnit.CAN, subCategoryId: 'SUBCATE_EN_22' },
  { name: 'Pietro Coricelli Extra Virgin Olive Oil 3L', totalPrice: 649000, unit: EProductUnit.CAN, subCategoryId: 'SUBCATE_EN_22' },
  { name: 'Olita Tuong An Refined Vegetable Oil 25kg', totalPrice: 789000, unit: EProductUnit.CAN, subCategoryId: 'SUBCATE_EN_22' },
  { name: 'Tansanh Refined Vegetable Oil 25kg', totalPrice: 779000, unit: EProductUnit.CAN, subCategoryId: 'SUBCATE_EN_22' },
  { name: 'Nakydaco Cooking Oil 25kg', totalPrice: 819000, unit: EProductUnit.CAN, subCategoryId: 'SUBCATE_EN_22' },
  { name: 'Tuong An Cooking Oil 30L', totalPrice: 889000, unit: EProductUnit.CAN, subCategoryId: 'SUBCATE_EN_22' },
  { name: 'Tuong An Cooking Oil 5L', totalPrice: 219000, unit: EProductUnit.BOTTLE, subCategoryId: 'SUBCATE_EN_22' },
  { name: 'Simply Lut Gao Rice Bran Oil 2L', totalPrice: 150000, unit: EProductUnit.BOTTLE, subCategoryId: 'SUBCATE_EN_22' },
  { name: 'Simply Huong Duong Sunflower Oil 2L', totalPrice: 155000, unit: EProductUnit.BOTTLE, subCategoryId: 'SUBCATE_EN_22' },
  { name: 'Nakydaco Sesame Oil 250ml', totalPrice: 62000, unit: EProductUnit.BOTTLE, subCategoryId: 'SUBCATE_EN_22' },
  { name: 'Pietro Coricelli Extra Virgin Olive Oil 500ml', totalPrice: 135000, unit: EProductUnit.BOTTLE, subCategoryId: 'SUBCATE_EN_22' },
  { name: 'Olita Tuong An Refined Vegetable Oil 5L', totalPrice: 191000, unit: EProductUnit.BOTTLE, subCategoryId: 'SUBCATE_EN_22' },
  { name: 'Cai Lan Cooking Oil 5L', totalPrice: 159000, unit: EProductUnit.BOTTLE, subCategoryId: 'SUBCATE_EN_22' },
  { name: 'Tuong An Cooking Oil 5L', totalPrice: 219000, unit: EProductUnit.BOTTLE, subCategoryId: 'SUBCATE_EN_22' },
  { name: 'Simply Dau Nanh Soybean Oil 5L', totalPrice: 325000, unit: EProductUnit.BOTTLE, subCategoryId: 'SUBCATE_EN_22' },
  { name: 'Simply Lut Gao Rice Bran Oil 2L', totalPrice: 875000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_EN_22' },
  { name: 'Simply Huong Duong Sunflower Oil 2L', totalPrice: 869000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_EN_22' },
  { name: 'Olita Tuong An Refined Vegetable Oil 5L', totalPrice: 749000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_EN_22' },
  { name: 'Cai Lan Cooking Oil 1L', totalPrice: 395000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_EN_22' },
  { name: 'Cai Lan Cooking Oil 5L', totalPrice: 599000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_EN_22' },
  { name: 'Tuong An Cooking Oil 5L', totalPrice: 849000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_EN_22' },
  { name: 'Simply Dau Nanh Soybean Oil 5L', totalPrice: 1255000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_EN_22' },
  // Subcategory 23
  { name: 'Hatsune Gao Chung Rice Vinegar 20L', totalPrice: 799000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_EN_23' },
  { name: 'Lisa Rice Vinegar 4.9L', totalPrice: 135000, unit: EProductUnit.BOTTLE, subCategoryId: 'SUBCATE_EN_23' },
  { name: 'Lisa Rice Vinegar 400ml', totalPrice: 16000, unit: EProductUnit.BOTTLE, subCategoryId: 'SUBCATE_EN_23' },
  { name: 'Chatel French Red Grape Vinegar 750ml', totalPrice: 70000, unit: EProductUnit.BOTTLE, subCategoryId: 'SUBCATE_EN_23' },
  { name: 'Coroli White Vinegar 1L', totalPrice: 37000, unit: EProductUnit.BOTTLE, subCategoryId: 'SUBCATE_EN_23' },
  { name: 'Paladin Apple Vinegar 500ml', totalPrice: 43000, unit: EProductUnit.BOTTLE, subCategoryId: 'SUBCATE_EN_23' },
  { name: 'Pietro Coricelli Fragrant White Grape Vinegar 1L', totalPrice: 189000, unit: EProductUnit.BOTTLE, subCategoryId: 'SUBCATE_EN_23' },
  { name: 'Lisa Rice Vinegar 400ml', totalPrice: 295000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_EN_23' },
  // Subcategory 24
  { name: 'Knorr Lemon Powder 400g', totalPrice: 125000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_EN_24' },
  { name: 'Ajinomoto Fine Granules MSG 1kg', totalPrice: 65000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_EN_24' },
  { name: 'Ajinomoto Coarse Granules MSG 1kg', totalPrice: 74000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_EN_24' },
  { name: 'Wasabi Powder 1kg', totalPrice: 205000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_EN_24' },
  { name: 'Ajinomoto Coarse Granules MSG 400g', totalPrice: 34000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_EN_24' },
  { name: 'Chili Powder 1kg', totalPrice: 179000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_EN_24' },
  { name: 'Knorr Bone Marrow and Beef Essence 3kg', totalPrice: 169000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_EN_24' },
  { name: 'Maggi Mushroom Seasoning 2kg', totalPrice: 199000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_EN_24' },
  { name: 'Banh Bien Hoa Baking Powder 1kg', totalPrice: 42000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_EN_24' },
  { name: 'Knorr Chicken Powder 1kg', totalPrice: 139000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_EN_24' },
  { name: 'Knorr Demi-Glace Brown Sauce Powder 1kg', totalPrice: 335000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_EN_24' },
  { name: 'Knorr Beef Broth Soup Base 1.5kg', totalPrice: 400000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_EN_24' },
  { name: 'Panko Bread Crumbs 1kg', totalPrice: 419000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_EN_24' },
  { name: 'Knorr Bone Marrow and Beef Essence 3kg', totalPrice: 639000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_EN_24' },
  { name: 'Maggi Mushroom Seasoning 2kg', totalPrice: 1139000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_EN_24' },
  { name: 'Maggi Chicken Powder 1kg', totalPrice: 1099000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_EN_24' },
  // Subcategory 25
  { name: 'Coffee Flower Honey 500ml', totalPrice: 77000, unit: EProductUnit.BOTTLE, subCategoryId: 'SUBCATE_EN_25' },
  { name: 'Phuong Di Coffee Flower Honey 1L', totalPrice: 155000, unit: EProductUnit.BOTTLE, subCategoryId: 'SUBCATE_EN_25' },
  { name: 'BeHoney Forest Honey 1.5kg', totalPrice: 185000, unit: EProductUnit.BOTTLE, subCategoryId: 'SUBCATE_EN_25' },
  { name: 'Natural Honey 500ml', totalPrice: 99000, unit: EProductUnit.BOTTLE, subCategoryId: 'SUBCATE_EN_25' },
  { name: 'Phuong Di Natural Honey 1L', totalPrice: 175000, unit: EProductUnit.BOTTLE, subCategoryId: 'SUBCATE_EN_25' },
  { name: 'Sesan Multifloral Forest Honey 500ml', totalPrice: 155000, unit: EProductUnit.BOTTLE, subCategoryId: 'SUBCATE_EN_25' },
  // Subcategory 26
  { name: 'Andros Top Up Mulberry Jelly 1kg', totalPrice: 83000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_EN_26' },
  { name: 'Marou Provisions Cocoa Powder 1kg', totalPrice: 689000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_EN_26' },
  { name: 'Andros Chunky Apricot Jam Bag 1kg', totalPrice: 209000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_EN_26' },
  { name: 'Andros Chunky Red Pomelo Yuzu Jam Bag 1kg', totalPrice: 189000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_EN_26' },
  { name: 'Andros Chunky Strawberry Jam Bag 1kg', totalPrice: 185000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_EN_26' },
  { name: 'Andros Chunky Purple Sweet Potato Jam Bag 1kg', totalPrice: 146000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_EN_26' },
  { name: 'Andros Chunky Kiwi Jam Bag 1kg', totalPrice: 199000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_EN_26' },
  { name: 'Andros Chunky Pear, Chamomile Jam Bag 1kg', totalPrice: 195000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_EN_26' },
  { name: 'Andros Chunky Pear, Apple, Cinnamon Jam Bag 1kg', totalPrice: 169000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_EN_26' },
  { name: 'Andros Chunky Apricot, Persimmon, Chia Seed Jam Bag 1kg', totalPrice: 175000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_EN_26' },
  { name: 'Andros Chunky Pomelo Flower Jam Bag 1kg', totalPrice: 185000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_EN_26' },
  { name: 'Andros Chunky Mulberry and Hibiscus Jam Bag 1kg', totalPrice: 199000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_EN_26' },
  { name: 'Andros Chunky Blueberry Jam Bag 1kg', totalPrice: 225000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_EN_26' },
  { name: 'Andros Chunky Rose Petal Mulberry Jam Bag 1kg', totalPrice: 200000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_EN_26' },
  { name: 'Andros Chunky Mango Jam Bag 1kg', totalPrice: 169000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_EN_26' },
  { name: 'Andros Chunky Apricot Jam Bag 1kg', totalPrice: 175000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_EN_26' },
  { name: 'LongBeach Strawberry Jam 900ml', totalPrice: 159000, unit: EProductUnit.BOTTLE, subCategoryId: 'SUBCATE_EN_26' },
  { name: 'LongBeach Young Coconut Jam 900ml', totalPrice: 159000, unit: EProductUnit.BOTTLE, subCategoryId: 'SUBCATE_EN_26' },
  { name: 'LongBeach Cloud Jam 900ml', totalPrice: 159000, unit: EProductUnit.BOTTLE, subCategoryId: 'SUBCATE_EN_26' },
  { name: 'LongBeach Mulberry Jam 900ml', totalPrice: 159000, unit: EProductUnit.BOTTLE, subCategoryId: 'SUBCATE_EN_26' },
  { name: 'LongBeach Apricot Jam 900ml', totalPrice: 159000, unit: EProductUnit.BOTTLE, subCategoryId: 'SUBCATE_EN_26' },
  { name: 'Osterberg Pineapple Mango Smoothie 1000ml', totalPrice: 124000, unit: EProductUnit.BOTTLE, subCategoryId: 'SUBCATE_EN_26' },
  { name: 'Osterberg Orange Mango Smoothie 1000ml', totalPrice: 125000, unit: EProductUnit.BOTTLE, subCategoryId: 'SUBCATE_EN_26' },
  { name: 'Osterberg Strawberry Smoothie 1000ml', totalPrice: 105000, unit: EProductUnit.BOTTLE, subCategoryId: 'SUBCATE_EN_26' },
  { name: 'Osterberg Kiwi Smoothie 1000ml', totalPrice: 122000, unit: EProductUnit.BOTTLE, subCategoryId: 'SUBCATE_EN_26' },
  { name: 'Osterberg Blueberry Smoothie 1000ml', totalPrice: 149000, unit: EProductUnit.BOTTLE, subCategoryId: 'SUBCATE_EN_26' },
  { name: 'Osterberg Mulberry Smoothie 1000ml', totalPrice: 149000, unit: EProductUnit.BOTTLE, subCategoryId: 'SUBCATE_EN_26' },
  { name: 'Osterberg Mango Smoothie 1000ml', totalPrice: 139000, unit: EProductUnit.BOTTLE, subCategoryId: 'SUBCATE_EN_26' },
  { name: 'Osterberg Apricot Smoothie 1000ml', totalPrice: 109000, unit: EProductUnit.BOTTLE, subCategoryId: 'SUBCATE_EN_26' },
  { name: 'LongBeach Cherry Syrup 740ml', totalPrice: 95000, unit: EProductUnit.BOTTLE, subCategoryId: 'SUBCATE_EN_26' },
  { name: 'Torani Classic Salted Caramel Syrup 750ml', totalPrice: 189000, unit: EProductUnit.BOTTLE, subCategoryId: 'SUBCATE_EN_26' },
  { name: 'LongBeach Original Caramel Syrup 740ml', totalPrice: 124000, unit: EProductUnit.BOTTLE, subCategoryId: 'SUBCATE_EN_26' },
  { name: 'Hersheys Chocolate Syrup 680g', totalPrice: 115000, unit: EProductUnit.BOTTLE, subCategoryId: 'SUBCATE_EN_26' },
  { name: 'Hersheys Strawberry Syrup 623g', totalPrice: 115000, unit: EProductUnit.BOTTLE, subCategoryId: 'SUBCATE_EN_26' },
  { name: 'LongBeach Strawberry Syrup 740ml', totalPrice: 95000, unit: EProductUnit.BOTTLE, subCategoryId: 'SUBCATE_EN_26' },
  { name: 'LongBeach Cantaloupe Syrup 740ml', totalPrice: 95000, unit: EProductUnit.BOTTLE, subCategoryId: 'SUBCATE_EN_26' },
  { name: 'LongBeach Young Coconut Syrup 740ml', totalPrice: 124000, unit: EProductUnit.BOTTLE, subCategoryId: 'SUBCATE_EN_26' },
  // Subcategory 27
  { name: 'Smoked Salmon Slices Amigo 100g', totalPrice: 81000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_EN_27' },
  { name: 'Smoked Salmon Slices Amigo 500g', totalPrice: 355000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_EN_27' },
  // Subcategory 28
  { name: 'Frozen Tiger Shrimp Size 26 - 30 Viet Tin 1kg', totalPrice: 279000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_EN_28' },
  { name: 'Frozen Tiger Shrimp Size 46 - 50 Viet Tin 1kg', totalPrice: 215000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_EN_28' },
  { name: 'Frozen Non-Peeled Shrimp Size 31 - 40 Viet Tin 1kg', totalPrice: 299000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_EN_28' },
  { name: 'Frozen Non-Peeled Shrimp Size 91 - 120 Viet Tin 1kg', totalPrice: 199000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_EN_28' },
  { name: 'Frozen Peeled Shrimp Size 26 - 30 Viet Tin 1kg', totalPrice: 239000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_EN_28' },
  { name: 'Frozen Peeled Shrimp Size 46 - 50 Viet Tin 1kg', totalPrice: 189000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_EN_28' },
  { name: 'Breaded Shrimp 180g', totalPrice: 53000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_EN_28' },
  // Subcategory 29
  { name: 'Frozen Squid Tube Size 2 - 4 Viet Tin 1kg', totalPrice: 299000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_EN_29' },
  { name: 'Frozen Squid Egg Size 12 - 15 Viet Tin 1kg', totalPrice: 189000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_EN_29' },
  // Subcategory 30
  { name: 'Frozen Scallop Shell Size 60 - 80 Viet Tin 1kg', totalPrice: 179000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_EN_30' },
  // Subcategory 31
  { name: 'Frozen Fish Balls CP 500g', totalPrice: 34000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_EN_31' },
  // Subcategory 32
  { name: 'Barista Milk Pasteurized Milk 1.8L', totalPrice: 69000, unit: EProductUnit.BOTTLE, subCategoryId: 'SUBCATE_EN_32' },
  { name: 'Fresh Whole Pasteurized Milk PUILAY 1L', totalPrice: 33000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_EN_32' },
  { name: 'Dalat Milk Pasteurized Milk 950ml - No Sugar', totalPrice: 37000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_EN_32' },
  { name: 'Anchor Pasteurized Milk 1L', totalPrice: 45000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_EN_32' },
  { name: 'TH True Milk UHT Pasteurized Milk (No Sugar) 1L', totalPrice: 36000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_EN_32' },
  { name: 'Vinamilk 100% No Sugar Pasteurized Milk 1L', totalPrice: 33000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_EN_32' },
  { name: 'SuperSoy Soy Milk with Sugar 1L', totalPrice: 25000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_EN_32' },
  { name: 'SuperSoy Sugar-Free Soy Milk 1L', totalPrice: 25000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_EN_32' },
  { name: 'Perfect Condensed Milk 1270g', totalPrice: 61000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_EN_32' },
  { name: 'Southern Star Sweetened Condensed Milk 1284g', totalPrice: 52000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_EN_32' },
  { name: 'Lucky Star Condensed Milk Vinamilk 1284g', totalPrice: 47000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_EN_32' },
  { name: 'Condensed Milk Southern Star 1284g', totalPrice: 63000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_EN_32' },
  { name: 'Fresh Whole Pasteurized Milk PUILAY 1L', totalPrice: 189000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_EN_32' },
  { name: 'Anchor Pasteurized Milk 1L x 12 Cartons', totalPrice: 509000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_EN_32' },
  { name: 'TH True Milk UHT Pasteurized Milk (No Sugar) 1L', totalPrice: 419000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_EN_32' },
  { name: 'Vinamilk 100% No Sugar Pasteurized Milk 1L', totalPrice: 385000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_EN_32' },
  { name: 'SuperSoy Soy Milk with Sugar 1L', totalPrice: 285000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_EN_32' },
  { name: 'SuperSoy Sugar-Free Soy Milk 1L', totalPrice: 285000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_EN_32' },
  { name: 'Perfect Condensed Milk 1270g', totalPrice: 709000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_EN_32' },
  { name: 'Condensed Milk Southern Star 1284g', totalPrice: 739000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_EN_32' },
  { name: 'Lucky Star Condensed Milk Vinamilk 1284g', totalPrice: 599000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_EN_32' },
  { name: 'Condensed Milk Lucky Star Southern Ocean 1284g', totalPrice: 549000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_EN_32' },
  // Subcategory 33
  { name: 'ICEHOT Universal Mix Base 907g', totalPrice: 87000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_EN_33' },
  { name: 'ICEHOT Plant-Based Fat Cream 454g', totalPrice: 32000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_EN_33' },
  { name: 'Anchor UHT EXTRA Whipping Cream 1L', totalPrice: 149000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_EN_33' },
  { name: 'Versatie Multipurpose UHT Whipping Cream 1L', totalPrice: 159000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_EN_33' },
  { name: 'ICEHOT Convenient Mix Topping Cream 907g', totalPrice: 74000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_EN_33' },
  { name: 'Richs 35% Milkfat Decorating Cream 1L', totalPrice: 149000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_EN_33' },
  { name: 'Tatua 36% Milkfat Cream 1L', totalPrice: 155000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_EN_33' },
  { name: 'Tatua 38% Milkfat Cream 1L', totalPrice: 157000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_EN_33' },
  { name: 'ICEHOT Plant-Based Fat Cream 454g', totalPrice: 739000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_EN_33' },
  { name: 'Anchor UHT Pasteurized Whipping Cream 1L', totalPrice: 1839000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_EN_33' },
  // Subcategory 34
  { name: 'Anchor Butter 5kg', totalPrice: 1299000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_EN_34' },
  { name: 'Anchor Slice Butter 1kg', totalPrice: 325000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_EN_34' },
  { name: 'Tường An Plant-Based Butter 800g', totalPrice: 48000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_EN_34' },
  { name: 'Anchor Butter 7g', totalPrice: 1049000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_EN_34' },
  { name: 'Tường An Plant-Based Butter 20kg', totalPrice: 775000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_EN_34' },
  { name: 'Anchor Butter 7g x 100 Pieces', totalPrice: 389000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_EN_34' },
  { name: 'Salty Anchor Butter 200g', totalPrice: 99000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_EN_34' },
  // Subcategory 35
  { name: 'Cheddar Cheese Slices Anchor 200g', totalPrice: 61000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_EN_35' },
  { name: 'Cheddar Cheese Slices Chesdale 250g', totalPrice: 75000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_EN_35' },
  { name: 'Laughing Cow Burger Cheese Slices 200g', totalPrice: 68000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_EN_35' },
  { name: 'Colorful Cheese Slices 1040g', totalPrice: 285000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_EN_35' },
  { name: 'Tatua Mascarpone Cheese 500g', totalPrice: 145000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_EN_35' },
  { name: 'Bottega Zelachi Mozzarella Cheese Shredded 1kg', totalPrice: 199000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_EN_35' },
  { name: 'Mozzarella Cheese Shredded 2kg', totalPrice: 439000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_EN_35' },
  { name: 'Bottega Zelachi Block Mozzarella Cheese 1kg', totalPrice: 209000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_EN_35' },
  { name: 'Laughing Cow Traditional Flavor 16M 224g', totalPrice: 74000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_EN_35' },
  // Subcategory 36
  { name: 'Dalat Milk Sugar-Free Yogurt 1kg', totalPrice: 67000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_EN_36' },
  { name: 'Dalat Milk Sugar-Free Yogurt 500g', totalPrice: 36000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_EN_36' },
  { name: 'Vinamilk Sweetened Yogurt 100g', totalPrice: 24000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_EN_36' },
  { name: 'Vinamilk Sugar-Free Yogurt 100g', totalPrice: 24000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_EN_36' },
  { name: 'Vinamilk Sweetened Yogurt 100g', totalPrice: 269000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_EN_36' },
  { name: 'Vinamilk Sugar-Free Yogurt 100g', totalPrice: 269000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_EN_36' },
  // Subcategory 37
  { name: 'Beer 333 330ml', totalPrice: 287000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_EN_37' },
  { name: 'Corona Beer Glass Bottle 300ml', totalPrice: 609000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_EN_37' },
  { name: 'Heineken Beer Silver Can High 330ml', totalPrice: 469000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_EN_37' },
  { name: 'Heineken Beer Can High 330ml', totalPrice: 455000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_EN_37' },
  { name: 'Saigon Lager Beer Can 330ml', totalPrice: 269000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_EN_37' },
  { name: 'Saigon Special Beer Can 330ml', totalPrice: 355000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_EN_37' },
  { name: 'Sapporo Beer 330ml', totalPrice: 405000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_EN_37' },
  { name: 'Tiger Beer Silver Can 330ml', totalPrice: 415000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_EN_37' },
  { name: 'Tiger Beer Can 330ml', totalPrice: 359000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_EN_37' },
  { name: 'Asahi SUPER DRY Beer 350ml', totalPrice: 1219000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_EN_37' },
  { name: 'Coronita Extra Glass Bottle 207ml', totalPrice: 449000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_EN_37' },
  { name: 'Kirin Beer 350ml', totalPrice: 1329000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_EN_37' },
  // Subcategory 38
  { name: 'Komomo Premium Plum Wine 750ml', totalPrice: 399000, unit: EProductUnit.BOTTLE, subCategoryId: 'SUBCATE_EN_38' },
  { name: 'Komomo Single Year Plum Wine 750ml', totalPrice: 249000, unit: EProductUnit.BOTTLE, subCategoryId: 'SUBCATE_EN_38' },
  { name: 'Komomo Special Plum Wine 750ml', totalPrice: 329000, unit: EProductUnit.BOTTLE, subCategoryId: 'SUBCATE_EN_38' },
];

const products_en: Product[] = [...items].map((item, idx) => ({
  id: `P_EN_${idx + 1}`,
  name: item.name,
  inventory: 10000,
  costPrice: 0,
  profit: 0,
  totalPrice: item.totalPrice,
  subCategoryId: item.subCategoryId,
  unit: item.unit ?? EProductUnit.KG,
  status: EProductStatus.ACTIVE,
  inventoryStatus: EInventoryStatus.IN_STOCK,
  langCode: ELang.EN,
  createdAt: new Date(),
  updatedAt: new Date(),
}));

export default products_en;
