const envKeys = {
  ACCESS_TOKEN: 'ACCESS_TOKEN_SECRET',
  REFRESH_TOKEN: 'REFRESH_TOKEN_SECRET',
  APP_EMAIL: 'APP_EMAIL',
  APP_EMAIL_PASS: 'APP_EMAIL_PASS',
  GOOGLE_ID: 'GOOGLE_CLIENT_ID',
  GOOGLE_SECRET: 'GOOGLE_CLIENT_SECRET',
  CLOUDINARY_KEY: 'CLOUDINARY_KEY',
  CLOUDINARY_NAME: 'CLOUDINARY_NAME',
  CLOUDINARY_SECRET: 'CLOUDINARY_SECRET',
  GOOGLE_CALLBACK_URL: 'GOOGLE_CALLBACK_URL',
  HOME_PAGE_URL: 'HOME_PAGE_URL',
} as const;

export default envKeys;
