import { Product } from '@prisma/client';
import { ELang } from '../../../src/common/enum/base';
import { EInventoryStatus, EProductStatus, EProductUnit } from '../../../src/modules/product/product.enum';

const items = [
  // Subcategory 1
  { name: 'Bí Ngòi Vàng', totalPrice: 49000, subCategoryId: 'SUBCATE_VN_1' },
  { name: 'Bí Ngòi Xanh', totalPrice: 25000, subCategoryId: 'SUBCATE_VN_1' },
  { name: 'Bí Nụ', totalPrice: 25000, subCategoryId: 'SUBCATE_VN_1' },
  { name: 'Bí Đao', totalPrice: 15000, subCategoryId: 'SUBCATE_VN_1' },
  { name: 'Bí Đỏ Bánh Xe', totalPrice: 13000, subCategoryId: 'SUBCATE_VN_1' },
  { name: 'Bí Đỏ Hồ Lô', totalPrice: 14000, subCategoryId: 'SUBCATE_VN_1' },
  { name: 'Bí Đỏ Nhật', totalPrice: 29000, subCategoryId: 'SUBCATE_VN_1' },
  { name: 'Bông Bí', totalPrice: 59000, subCategoryId: 'SUBCATE_VN_1' },
  { name: 'Bông Cải Trắng TQ', totalPrice: 73000, subCategoryId: 'SUBCATE_VN_1' },
  { name: 'Bông Cải Trắng Đà Lạt', totalPrice: 85000, subCategoryId: 'SUBCATE_VN_1' },
  { name: 'Bông Cải Xanh Baby', totalPrice: 65000, subCategoryId: 'SUBCATE_VN_1' },
  { name: 'Bông Cải Xanh TQ', totalPrice: 65000, subCategoryId: 'SUBCATE_VN_1' },
  { name: 'Bông Cải Xanh Đà Lạt', totalPrice: 55000, subCategoryId: 'SUBCATE_VN_1' },
  { name: 'Bông Hẹ', totalPrice: 85000, subCategoryId: 'SUBCATE_VN_1' },
  { name: 'Bạc Hà Socola', totalPrice: 33000, subCategoryId: 'SUBCATE_VN_1' },
  { name: 'Bạch Quả Tươi', totalPrice: 21000, subCategoryId: 'SUBCATE_VN_1' },
  { name: 'Bầu', totalPrice: 18000, subCategoryId: 'SUBCATE_VN_1' },
  { name: 'Bắp Chuối Bào', totalPrice: 45000, subCategoryId: 'SUBCATE_VN_1' },
  { name: 'Bắp Cải Trái Tim', totalPrice: 27000, subCategoryId: 'SUBCATE_VN_1' },
  { name: 'Bắp Cải Trắng', totalPrice: 145000, subCategoryId: 'SUBCATE_VN_1' },
  { name: 'Bắp Cải Tím', totalPrice: 33000, subCategoryId: 'SUBCATE_VN_1' },
  { name: 'Bắp Mỹ', totalPrice: 21000, subCategoryId: 'SUBCATE_VN_1' },
  { name: 'Bắp Non', totalPrice: 23000, subCategoryId: 'SUBCATE_VN_1' },
  { name: 'Cà Chua Beef', totalPrice: 39000, subCategoryId: 'SUBCATE_VN_1' },
  { name: 'Cà Chua Bi Cherry Vàng', totalPrice: 85000, subCategoryId: 'SUBCATE_VN_1' },
  { name: 'Cà Chua Bi Chocolate', totalPrice: 65000, subCategoryId: 'SUBCATE_VN_1' },
  { name: 'Cà Chua Bi Đỏ Cỡ Vừa', totalPrice: 45000, subCategoryId: 'SUBCATE_VN_1' },
  { name: 'Cà Chua Thường Rita Loại Lớn ', totalPrice: 30000, subCategoryId: 'SUBCATE_VN_1' },
  { name: 'Cà Rốt Baby', totalPrice: 99000, subCategoryId: 'SUBCATE_VN_1' },
  { name: 'Cà Rốt TQ', totalPrice: 18000, subCategoryId: 'SUBCATE_VN_1' },
  { name: 'Cà Rốt Đà Lạt ', totalPrice: 21000, subCategoryId: 'SUBCATE_VN_1' },
  { name: 'Cà Tím', totalPrice: 16000, subCategoryId: 'SUBCATE_VN_1' },
  { name: 'Cải Bó Xôi', totalPrice: 33000, subCategoryId: 'SUBCATE_VN_1' },
  { name: 'Cải Bẹ Xanh', totalPrice: 29000, subCategoryId: 'SUBCATE_VN_1' },
  { name: 'Cải Cầu Vồng', totalPrice: 79000, subCategoryId: 'SUBCATE_VN_1' },
  { name: 'Cải Dún', totalPrice: 39000, subCategoryId: 'SUBCATE_VN_1' },
  { name: 'Cải Ngọt', totalPrice: 24000, subCategoryId: 'SUBCATE_VN_1' },
  { name: 'Cải Ngọt Hồng Kông', totalPrice: 33000, subCategoryId: 'SUBCATE_VN_1' },
  { name: 'Cải Sậy', totalPrice: 23000, subCategoryId: 'SUBCATE_VN_1' },
  { name: 'Cải Thìa', totalPrice: 23000, subCategoryId: 'SUBCATE_VN_1' },
  // Subcategory 2
  { name: 'Bắp Mỹ Đông Lạnh VSafefood', totalPrice: 59000, subCategoryId: 'SUBCATE_VN_2' },
  { name: 'Dưa Cải Chua', totalPrice: 31000, subCategoryId: 'SUBCATE_VN_2' },
  { name: 'Gừng Hồng Cắt Lát', totalPrice: 122000, subCategoryId: 'SUBCATE_VN_2' },
  {
    name: 'Khoai Tây Đông Lạnh Cắt Dài Shoe String 7/7 Mydibel',
    totalPrice: 79000,
    subCategoryId: 'SUBCATE_VN_2',
  },
  { name: 'Khoai Tây Đông Lạnh Cắt Múi Cau CRRROCK-N', totalPrice: 199000, subCategoryId: 'SUBCATE_VN_2' },
  { name: 'Khoai tây cắt thẳng Meito 10mm', totalPrice: 165000, subCategoryId: 'SUBCATE_VN_2' },
  { name: 'Kim Chi The Foods', totalPrice: 49000, subCategoryId: 'SUBCATE_VN_2' },
  { name: 'Kim Chi The Foods', totalPrice: 27000, subCategoryId: 'SUBCATE_VN_2' },
  { name: 'Me Chua Nấu Canh', totalPrice: 19000, subCategoryId: 'SUBCATE_VN_2' },
  { name: 'Măng Chua', totalPrice: 27000, subCategoryId: 'SUBCATE_VN_2' },
  { name: 'Măng Lá', totalPrice: 27000, subCategoryId: 'SUBCATE_VN_2' },
  { name: 'Măng Ngọt', totalPrice: 27000, subCategoryId: 'SUBCATE_VN_2' },
  { name: 'Măng Trúc', totalPrice: 44000, subCategoryId: 'SUBCATE_VN_2' },
  { name: 'Rau Hỗn Hợp Đông Lạnh VSafefood', totalPrice: 62000, subCategoryId: 'SUBCATE_VN_2' },
  { name: 'Sả Băm', totalPrice: 21000, subCategoryId: 'SUBCATE_VN_2' },
  { name: 'Đậu Hà Lan Đông Lạnh VSafefood', totalPrice: 82000, subCategoryId: 'SUBCATE_VN_2' },
  { name: 'Đậu Hũ Chiên', totalPrice: 5000, subCategoryId: 'SUBCATE_VN_2' },
  { name: 'Đậu Hũ Da Aburaage Vị Nguyên', totalPrice: 31000, subCategoryId: 'SUBCATE_VN_2' },
  { name: 'Đậu Hũ Non Vị Nguyên', totalPrice: 13000, subCategoryId: 'SUBCATE_VN_2' },
  { name: 'Đậu Hũ TA Vị Nguyên', totalPrice: 13000, subCategoryId: 'SUBCATE_VN_2' },
  { name: 'Đậu Hũ Trắng', totalPrice: 5000, subCategoryId: 'SUBCATE_VN_2' },
  { name: 'Đậu Hà Lan Đông', totalPrice: 93000, subCategoryId: 'SUBCATE_VN_2' },
  // Subcategory 3
  { name: 'Lẩu Nấm', totalPrice: 29000, subCategoryId: 'SUBCATE_VN_3' },
  { name: 'Nấm Bào Ngư Trắng', totalPrice: 39000, subCategoryId: 'SUBCATE_VN_3' },
  { name: 'Nấm Bào Ngư Xám', totalPrice: 64000, subCategoryId: 'SUBCATE_VN_3' },
  { name: 'Nấm Bạch Tuyết', totalPrice: 15000, subCategoryId: 'SUBCATE_VN_3' },
  { name: 'Nấm Hoàng Kim', totalPrice: 14000, subCategoryId: 'SUBCATE_VN_3' },
  { name: 'Nấm Kim Châm', totalPrice: 14000, subCategoryId: 'SUBCATE_VN_3' },
  { name: 'Nấm Mèo Khô', totalPrice: 139000, subCategoryId: 'SUBCATE_VN_3' },
  { name: 'Nấm Mỡ', totalPrice: 46000, subCategoryId: 'SUBCATE_VN_3' },
  { name: 'Nấm Mỡ Nâu VN', totalPrice: 48000, subCategoryId: 'SUBCATE_VN_3' },
  { name: 'Nấm Ngọc Châm Nâu', totalPrice: 14000, subCategoryId: 'SUBCATE_VN_3' },
  { name: 'Nấm Ngọc Châm Trắng', totalPrice: 14000, subCategoryId: 'SUBCATE_VN_3' },
  { name: 'Nấm Rơm', totalPrice: 135000, subCategoryId: 'SUBCATE_VN_3' },
  { name: 'Nấm Tuyết Trắng', totalPrice: 355000, subCategoryId: 'SUBCATE_VN_3' },
  { name: 'Nấm Đông Cô Khô', totalPrice: 299000, subCategoryId: 'SUBCATE_VN_3' },
  { name: 'Nấm Đông Cô Khô (Nấm Hương Khô)', totalPrice: 39000, subCategoryId: 'SUBCATE_VN_3' },
  { name: 'Nấm Đông Cô Tươi', totalPrice: 34000, subCategoryId: 'SUBCATE_VN_3' },
  { name: 'Nấm Đùi Gà', totalPrice: 65000, subCategoryId: 'SUBCATE_VN_3' },
  // Subcategory 4
  { name: 'Bơ Booth', totalPrice: 74000, subCategoryId: 'SUBCATE_VN_4' },
  { name: 'Bưởi Da Xanh', totalPrice: 45000, subCategoryId: 'SUBCATE_VN_4' },
  { name: 'Bưởi Năm Roi', totalPrice: 39000, subCategoryId: 'SUBCATE_VN_4' },
  { name: 'Cam Sành', totalPrice: 17000, subCategoryId: 'SUBCATE_VN_4' },
  { name: 'Cam Vàng Late Úc', totalPrice: 89000, subCategoryId: 'SUBCATE_VN_4' },
  { name: 'Cam sành', totalPrice: 16000, subCategoryId: 'SUBCATE_VN_4' },
  { name: 'Chanh Có Hạt', totalPrice: 39000, subCategoryId: 'SUBCATE_VN_4' },
  { name: 'Chanh Dây Tím', totalPrice: 24000, subCategoryId: 'SUBCATE_VN_4' },
  { name: 'Chanh Không Hạt', totalPrice: 29000, subCategoryId: 'SUBCATE_VN_4' },
  { name: 'Chanh Không Hạt Loại 2', totalPrice: 27000, subCategoryId: 'SUBCATE_VN_4' },
  { name: 'Chanh Quảng Đông', totalPrice: 85000, subCategoryId: 'SUBCATE_VN_4' },
  { name: 'Chanh Vàng', totalPrice: 79000, subCategoryId: 'SUBCATE_VN_4' },
  { name: 'Chanh Vàng Giống Nam Phi', totalPrice: 89000, subCategoryId: 'SUBCATE_VN_4' },
  { name: 'Chuối Cau', totalPrice: 19000, subCategoryId: 'SUBCATE_VN_4' },
  { name: 'Chuối Chát', totalPrice: 49000, subCategoryId: 'SUBCATE_VN_4' },
  { name: 'Chuối Già Hương', totalPrice: 19000, subCategoryId: 'SUBCATE_VN_4' },
  { name: 'Chuối Laba', totalPrice: 21000, subCategoryId: 'SUBCATE_VN_4' },
  { name: 'Chuối Sứ', totalPrice: 19000, subCategoryId: 'SUBCATE_VN_4' },
  { name: 'Cóc Thái', totalPrice: 15000, subCategoryId: 'SUBCATE_VN_4' },
  { name: 'Dâu Tây Giống Hàn Quốc', totalPrice: 199000, subCategoryId: 'SUBCATE_VN_4' },
  { name: 'Dâu Tây Nhật Đông Lạnh', totalPrice: 189000, subCategoryId: 'SUBCATE_VN_4' },
  { name: 'Dâu Tây Tươi Đông Lạnh Chào Đà Lạt', totalPrice: 85000, subCategoryId: 'SUBCATE_VN_4' },
  { name: 'Dâu Tây V.Safefood Đông Lạnh', totalPrice: 169000, subCategoryId: 'SUBCATE_VN_4' },
  { name: 'Dưa Hấu Không Hạt', totalPrice: 19000, subCategoryId: 'SUBCATE_VN_4' },
  { name: 'Dưa Hấu Ruột Vàng', totalPrice: 19000, subCategoryId: 'SUBCATE_VN_4' },
  { name: 'Dưa Hấu', totalPrice: 17000, subCategoryId: 'SUBCATE_VN_4' },
  { name: 'Dưa LướI TL3 Ruột Vàng', totalPrice: 45000, subCategoryId: 'SUBCATE_VN_4' },
  { name: 'Khế Chua', totalPrice: 59000, subCategoryId: 'SUBCATE_VN_4' },
  { name: 'Mâm Xôi Đỏ V.Safefood Đông Lạnh', totalPrice: 249000, subCategoryId: 'SUBCATE_VN_4' },
  { name: 'Quýt Đường', totalPrice: 53000, subCategoryId: 'SUBCATE_VN_4' },
  { name: 'Thanh Long Ruột Đỏ', totalPrice: 33000, subCategoryId: 'SUBCATE_VN_4' },
  { name: 'Thanh Long Trắng', totalPrice: 33000, subCategoryId: 'SUBCATE_VN_4' },
  { name: 'Thơm Nguyên Trái', totalPrice: 18000, subCategoryId: 'SUBCATE_VN_4' },
  { name: 'Thơm Nguyên Trái Loại 2', totalPrice: 16000, subCategoryId: 'SUBCATE_VN_4' },
  // Subcategory 5
  { name: 'Chân Gà Đông lạnh Ba Huân', totalPrice: 59000, subCategoryId: 'SUBCATE_VN_5' },
  { name: 'Cánh Gà Tươi CP', totalPrice: 97000, subCategoryId: 'SUBCATE_VN_5' },
  { name: 'Cánh Gà Đông Lạnh Ba Huân', totalPrice: 85000, subCategoryId: 'SUBCATE_VN_5' },
  { name: 'Gan Gà Đông Lạnh CP', totalPrice: 33000, subCategoryId: 'SUBCATE_VN_5' },
  { name: 'Má Đùi Gà Đông Lạnh CP', totalPrice: 65000, subCategoryId: 'SUBCATE_VN_5' },
  { name: 'Mề Gà Đông Lạnh CP', totalPrice: 49000, subCategoryId: 'SUBCATE_VN_5' },
  { name: 'Phao Câu Gà Đông Lạnh CP', totalPrice: 25000, subCategoryId: 'SUBCATE_VN_5' },
  { name: 'Sụn Chip Gà Đông Lạnh CP', totalPrice: 119000, subCategoryId: 'SUBCATE_VN_5' },
  { name: 'Tim Gà Đông Lạnh CP', totalPrice: 53000, subCategoryId: 'SUBCATE_VN_5' },
  { name: 'Xương Gà Đông Lạnh CP', totalPrice: 29000, subCategoryId: 'SUBCATE_VN_5' },
  { name: 'Đùi Gà Góc Tư Tươi CP', totalPrice: 77000, subCategoryId: 'SUBCATE_VN_5' },
  { name: 'Đùi Gà Góc Tư Đông Lạnh Ba Huân', totalPrice: 72000, subCategoryId: 'SUBCATE_VN_5' },
  { name: 'Đùi Gà Góc Tư Đông Lạnh CP', totalPrice: 78000, subCategoryId: 'SUBCATE_VN_5' },
  { name: 'Đùi Gà Rút Xương Tươi CP', totalPrice: 88000, subCategoryId: 'SUBCATE_VN_5' },
  { name: 'Đùi Gà Rút Xương Đông Lạnh CP', totalPrice: 89000, subCategoryId: 'SUBCATE_VN_5' },
  { name: 'Đùi Tỏi Gà Đông Lạnh CP', totalPrice: 99000, subCategoryId: 'SUBCATE_VN_5' },
  { name: 'Ức Gà Phi Lê Không Da Tươi CP', totalPrice: 85000, subCategoryId: 'SUBCATE_VN_5' },
  { name: 'Ức Gà Phi Lê Không Da Đông Lạnh Ba Huân', totalPrice: 78000, subCategoryId: 'SUBCATE_VN_5' },
  { name: 'Ức Gà Phi Lê Không Da Đông Lạnh CP', totalPrice: 86000, subCategoryId: 'SUBCATE_VN_5' },
  { name: 'Sụn Đùi Gà Đông Lạnh CP', totalPrice: 164000, subCategoryId: 'SUBCATE_VN_5' },
  // Subcategory 6
  { name: 'Ba Rọi Heo Cắt Lát Đông Lạnh 2mm NH Foods', totalPrice: 249000, subCategoryId: 'SUBCATE_VN_6' },
  { name: 'Ba Rọi Xông Khói NH Foods', totalPrice: 199000, subCategoryId: 'SUBCATE_VN_6' },
  { name: 'Ba Rọi Xông Khói Đông Lạnh XL Le Gourmet', totalPrice: 229000, subCategoryId: 'SUBCATE_VN_6' },
  { name: 'Cốt Lết Cắt Lát Đông Lạnh CP', totalPrice: 125000, subCategoryId: 'SUBCATE_VN_6' },
  { name: 'Giò Sống Heo Đông Lạnh', totalPrice: 159000, subCategoryId: 'SUBCATE_VN_6' },
  { name: 'Nạc Dăm Đông Lạnh NH Foods', totalPrice: 145000, subCategoryId: 'SUBCATE_VN_6' },
  { name: 'Nạc Vai Đông Lạnh CP', totalPrice: 89000, subCategoryId: 'SUBCATE_VN_6' },
  { name: 'Nạc Đùi Heo Đông Lạnh CP', totalPrice: 89000, subCategoryId: 'SUBCATE_VN_6' },
  { name: 'Thịt Heo Xay Đông Lạnh CP', totalPrice: 95000, subCategoryId: 'SUBCATE_VN_6' },
  { name: 'Xương Ống Heo Đông Lạnh CP', totalPrice: 77000, subCategoryId: 'SUBCATE_VN_6' },
  // Subcategory 7
  { name: 'Ba Chỉ Bò Mỹ Đông Lạnh', totalPrice: 135000, subCategoryId: 'SUBCATE_VN_7' },
  { name: 'Ba Chỉ Bò Đông Lạnh MRT', totalPrice: 129000, subCategoryId: 'SUBCATE_VN_7' },
  { name: 'Bò Lúc Lắc Đông Lạnh MRT', totalPrice: 219000, subCategoryId: 'SUBCATE_VN_7' },
  { name: 'Bò Xay Đông Lạnh MRT', totalPrice: 195000, subCategoryId: 'SUBCATE_VN_7' },
  { name: 'Phi Lê Thăn Ngoại Đông Lạnh MRT', totalPrice: 179000, subCategoryId: 'SUBCATE_VN_7' },
  { name: 'Thịt Bò Úc Xay Đông Lạnh', totalPrice: 195000, subCategoryId: 'SUBCATE_VN_7' },
  // Subcategory 8
  { name: 'Lòng Đỏ Trứng Muối Ba Huân', totalPrice: 265000, subCategoryId: 'SUBCATE_VN_8' },
  { name: 'Trứng Cút Ba Huân', totalPrice: 26000, subCategoryId: 'SUBCATE_VN_8' },
  { name: 'Trứng Gà Ba Huân size L', totalPrice: 30000, subCategoryId: 'SUBCATE_VN_8' },
  { name: 'Trứng Gà Ba Huân size M', totalPrice: 29000, subCategoryId: 'SUBCATE_VN_8' },
  { name: 'Trứng Gà CP (Size L)', totalPrice: 30000, subCategoryId: 'SUBCATE_VN_8' },
  { name: 'Trứng Gà CP (Size XL)', totalPrice: 31000, subCategoryId: 'SUBCATE_VN_8' },
  { name: 'Trứng Gà GFoods 55g', totalPrice: 27000, subCategoryId: 'SUBCATE_VN_8' },
  { name: 'Trứng Gà GFoods 60g', totalPrice: 29000, subCategoryId: 'SUBCATE_VN_8' },
  { name: 'Trứng Vịt Bắc Thảo Ba Huân', totalPrice: 65000, subCategoryId: 'SUBCATE_VN_8' },
  { name: 'Trứng Vịt Muối Ba Huân', totalPrice: 23000, subCategoryId: 'SUBCATE_VN_8' },
  { name: 'Trứng vịt Ba Huân', totalPrice: 40000, subCategoryId: 'SUBCATE_VN_8' },
  // Subcategory 9
  { name: 'Dăm Bông Vai Vuông XL Le Gourmet', totalPrice: 159000, subCategoryId: 'SUBCATE_VN_9' },
  { name: 'Xúc Xích Cocktail Le Gourmet', totalPrice: 82000, subCategoryId: 'SUBCATE_VN_9' },
  { name: 'Xúc Xích Standard Xông Khói NH Foods', totalPrice: 57000, subCategoryId: 'SUBCATE_VN_9' },
  { name: 'Xúc Xích Sài Gòn Xông Khói NH Foods', totalPrice: 76000, subCategoryId: 'SUBCATE_VN_9' },
  { name: 'Xúc Xích Đức 10cm Le Gourmet', totalPrice: 72000, subCategoryId: 'SUBCATE_VN_9' },
  // Subcategory 10
  { name: 'Dasani Water 1.5L', totalPrice: 39000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_VN_10' },
  { name: 'Nước Khoáng Alba Có Ga (Chai Thuỷ Tinh)', totalPrice: 449000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_VN_10' },
  { name: 'Nước Khoáng Alba Không Ga (Chai Thuỷ Tinh)', totalPrice: 409000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_VN_10' },
  { name: 'Nước Khoáng La Vie 500ml', totalPrice: 79000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_VN_10' },
  { name: 'Nước Soda Có Gas Aquafina 320ml', totalPrice: 139000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_VN_10' },
  { name: 'Nước Soda Có Gas Schweppes', totalPrice: 135000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_VN_10' },
  { name: 'Nước Suối Alba Có Ga (Chai Nhựa)', totalPrice: 139000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_VN_10' },
  { name: 'Nước Suối Alba Không Ga (Chai Nhựa)', totalPrice: 114000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_VN_10' },
  { name: 'Nước Tinh Khiết Aquafina 500ml', totalPrice: 99000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_VN_10' },
  { name: 'Nước Tinh Khiết SATORI 500ml', totalPrice: 78000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_VN_10' },
  { name: 'Nước Khoáng La Vie 500ml x 30 Chai', totalPrice: 79000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_VN_10' },
  { name: 'Nước Soda Có Gas Singha 325ml', totalPrice: 205000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_VN_10' },
  { name: 'Nước Soda Có Gas Singha 325ml', totalPrice: 939000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_VN_10' },
  // Subcategory 11
  { name: 'Coca-Cola 320ml', totalPrice: 199000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_VN_11' },
  { name: 'Coca-Cola Light 320ml', totalPrice: 195000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_VN_11' },
  { name: 'Coca-Cola Zero 320ml', totalPrice: 198000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_VN_11' },
  { name: 'Fanta Orange 320ml', totalPrice: 165000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_VN_11' },
  { name: 'Nước Bù Khoáng Revive 500ml', totalPrice: 189000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_VN_11' },
  { name: 'Nước Bù Khoáng Revive Chanh Muối', totalPrice: 179000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_VN_11' },
  { name: 'Nước Giải Khát 7UP 320ml', totalPrice: 192000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_VN_11' },
  { name: 'Nước Giải Khát Pepsi 320ml', totalPrice: 195000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_VN_11' },
  { name: 'Nước Giải Khát Schweppes Tonic 320ml', totalPrice: 155000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_VN_11' },
  { name: 'Nước Tăng Lực Carabao 250ml', totalPrice: 179000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_VN_11' },
  { name: 'Nước Tăng Lực RedBull 250ml', totalPrice: 225000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_VN_11' },
  { name: 'Nước Tăng Lực Sting Dâu Lon 320ml', totalPrice: 205000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_VN_11' },
  { name: 'Nước Ép Cam Twister 320ml', totalPrice: 199000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_VN_11' },
  { name: 'Schweppes Dry Ginger Ale 320ml', totalPrice: 195000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_VN_11' },
  { name: 'Sprite 320ml', totalPrice: 178000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_VN_11' },
  // Subcategory 12
  { name: 'Nước Gạo Buổi Sáng Morning Rice 1.5L', totalPrice: 49000, unit: EProductUnit.BOTTLE, subCategoryId: 'SUBCATE_VN_12' },
  { name: 'Nước VFresh đào Nectar 1L', totalPrice: 35000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_VN_12' },
  { name: 'Nước Vfresh cam ép 100% 1L', totalPrice: 41000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_VN_12' },
  { name: 'Nước Vfresh táo ép 100% 1L', totalPrice: 39000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_VN_12' },
  { name: 'Nước Vfresh ổi ép Nectar 1L', totalPrice: 41000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_VN_12' },
  { name: 'Nước dừa tươi Cocofresh 1L', totalPrice: 35000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_VN_12' },
  { name: 'Nước Ép Cam Hỗn Hợp & Tép Cam Malee 1L', totalPrice: 63000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_VN_12' },
  { name: 'Nước Ép Cà Chua Prima 100% 1L', totalPrice: 47000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_VN_12' },
  { name: 'Nước Ép Dứa Malee 1L', totalPrice: 63000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_VN_12' },
  { name: 'Nước Ép Hỗn Hợp Prima 100% 1L', totalPrice: 47000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_VN_12' },
  { name: 'Nước Ép Lựu Và Trái Cây Hỗn Hợp Malee 1 L', totalPrice: 63000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_VN_12' },
  { name: 'Nước Ép Nam Việt Quất Prima 16% 1L', totalPrice: 52000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_VN_12' },
  { name: 'Nước Ép Nectar Đào Prima 50% 1L', totalPrice: 47000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_VN_12' },
  { name: 'Nước Ép Nho Malee 1L', totalPrice: 63000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_VN_12' },
  { name: 'Nước Ép Táo Malee 1L', totalPrice: 63000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_VN_12' },
  { name: 'Nước Ép Vải Malee 1L', totalPrice: 63000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_VN_12' },
  { name: 'Nước Ép Hỗn Hợp Prima 100% 1L', totalPrice: 529000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_VN_12' },
  { name: 'Nước Dừa Tươi Cocofresh 1L', totalPrice: 399000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_VN_12' },
  { name: 'Nước Gạo Buổi Sáng Morning Rice 1.5L', totalPrice: 529000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_VN_12' },
  { name: 'Nước VFresh Đào Nectar 1L', totalPrice: 399000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_VN_12' },
  { name: 'Nước Vfresh Cam Ép 100% 1L', totalPrice: 479000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_VN_12' },
  { name: 'Nước Vfresh Táo Ép 100% 1L ', totalPrice: 449000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_VN_12' },
  { name: 'Nước Vfresh Ổi Ép Nectar 1L', totalPrice: 469000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_VN_12' },
  { name: 'Nước Ép Cà Chua Prima 100% 1L', totalPrice: 529000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_VN_12' },
  { name: 'Nước Ép Dứa Prima 100% 1L', totalPrice: 529000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_VN_12' },
  { name: 'Nước Ép Nam Việt Quất Prima 16% 1L', totalPrice: 599000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_VN_12' },
  { name: 'Nước Ép Nectar Đào Prima 50% 1L', totalPrice: 529000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_VN_12' },
  // Subcategory 13
  { name: 'Cà Phê Chữ I Trung Nguyên 500g', totalPrice: 79000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_VN_13' },
  { name: 'Cà Phê Chữ S Trung Nguyên 500g', totalPrice: 69000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_VN_13' },
  { name: 'Cà Phê Hạt Rang Lacaph Traditional Espresso Blend Nguyên Hạt 1kg', totalPrice: 245000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_VN_13' },
  { name: 'Cà Phê Hạt Rang Lacaph Traditional Espresso Blend Xay Sẵn 1kg', totalPrice: 245000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_VN_13' },
  { name: 'Cà Phê Hạt Rang Lacaph Traditional Filter Blend Nguyên Hạt 1kg', totalPrice: 259000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_VN_13' },
  { name: 'Cà Phê Hạt Rang Lacaph Traditional Filter Blend Xay Sẵn 1kg', totalPrice: 259000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_VN_13' },
  { name: 'Cà Phê Hạt Rang Lacaph Traditional Phin Blend Nguyên Hạt 1kg', totalPrice: 215000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_VN_13' },
  { name: 'Cà Phê Hạt Rang Lacaph Traditional Phin Blend Xay Sẵn 1kg', totalPrice: 215000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_VN_13' },
  { name: 'Cà Phê Sáng Tạo 1 Trung Nguyên 500g', totalPrice: 99000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_VN_13' },
  { name: 'Cà Phê Sức Sống (Nâu) Trung Nguyên 500g', totalPrice: 99000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_VN_13' },
  // Subcategory 14
  { name: 'Bột Trà Genmaicha KAWAMI 100g', totalPrice: 159000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_VN_14' },
  { name: 'Bột Trà Houjicha KAWAMI 100g', totalPrice: 159000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_VN_14' },
  { name: 'Bột Trà Matcha Hương Nhài 1kg', totalPrice: 759000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_VN_14' },
  { name: 'Bột Trà Xanh Matcha KAWAMI 100g', totalPrice: 159000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_VN_14' },
  { name: 'Trà Dilmah Bá Tước 1.5g', totalPrice: 45000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_VN_14' },
  { name: 'Trà Dilmah Bạc Hà 1.5g', totalPrice: 45000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_VN_14' },
  { name: 'Trà Dilmah Chanh 1.5g', totalPrice: 44000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_VN_14' },
  { name: 'Trà Dilmah Dâu 1.5g', totalPrice: 45000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_VN_14' },
  { name: 'Trà Dilmah Gừng và Mật ong 1.5g', totalPrice: 45000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_VN_14' },
  { name: 'Trà Dilmah Hoa Cúc 1.5g', totalPrice: 75000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_VN_14' },
  { name: 'Trà Dilmah Hương Nhài 1.5g', totalPrice: 75000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_VN_14' },
  { name: 'Trà Dilmah Mâm Xôi 1.5g', totalPrice: 44000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_VN_14' },
  { name: 'Trà Dilmah Thảo Dược Bạc Hà 1.5g', totalPrice: 72000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_VN_14' },
  { name: 'Trà Dilmah Táo 1.5g', totalPrice: 44000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_VN_14' },
  { name: 'Trà Dilmah Vải 1.5g', totalPrice: 72000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_VN_14' },
  { name: 'Trà Dilmah Ô Long 1.5g', totalPrice: 55000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_VN_14' },
  { name: 'Trà Dilmah Điểm Tâm Anh Quốc 1.5g', totalPrice: 72000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_VN_14' },
  { name: 'Trà Dilmah Đào 1.5g', totalPrice: 55000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_VN_14' },
  { name: 'Trà Thái Xanh LongBeach', totalPrice: 89000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_VN_14' },
  { name: 'Trà Thái Đỏ LongBeach', totalPrice: 59000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_VN_14' },
  { name: 'Trà Đào Và Hạt Chia Fuzetea 350ml', totalPrice: 149000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_VN_14' },
  { name: 'Trà Đào Và Hạt Chia Fuzetea 450ml', totalPrice: 189000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_VN_14' },
  // Subcategory 15
  { name: 'Bánh Canh Bột Gạo', totalPrice: 21000, subCategoryId: 'SUBCATE_VN_15' },
  { name: 'Bánh Canh Bột Lọc', totalPrice: 17000, subCategoryId: 'SUBCATE_VN_15' },
  { name: 'Bánh Phở Tươi Loại Nhỏ', totalPrice: 16000, subCategoryId: 'SUBCATE_VN_15' },
  { name: 'Bún Gạo Safoco', totalPrice: 33000, subCategoryId: 'SUBCATE_VN_15' },
  { name: 'Bún Sợi To (Bún Bò Huế)', totalPrice: 15000, subCategoryId: 'SUBCATE_VN_15' },
  { name: 'Bún Tươi', totalPrice: 15000, subCategoryId: 'SUBCATE_VN_15' },
  { name: 'Hủ Tiếu Dai', totalPrice: 29000, subCategoryId: 'SUBCATE_VN_15' },
  { name: 'Hủ Tiếu Mềm', totalPrice: 19000, subCategoryId: 'SUBCATE_VN_15' },
  { name: 'Mì Linguine Pietro Coricelli', totalPrice: 39000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_VN_15' },
  { name: 'Mì Soba Yamamori', totalPrice: 51000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_VN_15' },
  { name: 'Mì Spaghetti Golden Farm', totalPrice: 29000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_VN_15' },
  { name: 'Mì Spaghetti Pietro Coricelli', totalPrice: 39000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_VN_15' },
  { name: 'Mì Trứng Sợi Nhỏ Cao Cấp Meizan', totalPrice: 29000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_VN_15' },
  { name: 'Mì Trứng Sợi Nhỏ Safoco', totalPrice: 29000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_VN_15' },
  { name: 'Mì Trứng Thượng Hạng Safoco', totalPrice: 25000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_VN_15' },
  { name: 'Mì Udon Yamamori', totalPrice: 39000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_VN_15' },
  { name: 'Mì Xào Cao Cấp Safoco', totalPrice: 35000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_VN_15' },
  { name: 'Mì Ống Fusilli Pietro Coricelli', totalPrice: 42000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_VN_15' },
  { name: 'Nui Ống Lớn Safoco', totalPrice: 25000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_VN_15' },
  { name: 'Phở Gạo Lứt Vietsan', totalPrice: 18000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_VN_15' },
  { name: 'Bún Gạo Safoco 500g', totalPrice: 309000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_VN_15' },
  { name: 'Mì Spaghetti Pietro Coricelli 500g', totalPrice: 869000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_VN_15' },
  { name: 'Mì Trứng Sợi Nhỏ Safoco 500g', totalPrice: 559000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_VN_15' },
  { name: 'Mì Trứng Thượng Hạng Safoco 400g', totalPrice: 349000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_VN_15' },
  { name: 'Nui Ống Lớn Safoco 400g', totalPrice: 605000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_VN_15' },
  // Subcategory 16
  { name: 'Bột Bánh Xèo Tài Ký 400g', totalPrice: 18000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_VN_16' },
  { name: 'Bột Bắp Meizan 1kg', totalPrice: 32000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_VN_16' },
  { name: 'Bột Bắp Takoky 1kg', totalPrice: 39000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_VN_16' },
  { name: 'Bột Bắp Taky 150g', totalPrice: 11000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_VN_16' },
  { name: 'Bột Chiên Giòn Meizan 1kg', totalPrice: 42000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_VN_16' },
  { name: 'Bột Chiên Giòn Panko 500g', totalPrice: 19000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_VN_16' },
  { name: 'Bột Chiên Giòn Tài Ký 1kg', totalPrice: 47000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_VN_16' },
  { name: 'Bột Chiên Xù Panko 1kg', totalPrice: 55000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_VN_16' },
  { name: 'Bột Chiên Xù Takoky 1kg', totalPrice: 61000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_VN_16' },
  { name: 'Bột Mì Bakers Choice 1kg Số 13', totalPrice: 27000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_VN_16' },
  { name: 'Bột Mì Bakers Choice 1kg Số 8', totalPrice: 27000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_VN_16' },
  { name: 'Bột Mì Đa Dụng Bakers Choice 1kg Số 11', totalPrice: 26000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_VN_16' },
  { name: 'Bột Mì Đa Dụng Táo Đỏ 1kg (Bột Mì Số 8)', totalPrice: 24000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_VN_16' },
  { name: 'Bột Năng Tài Ký 1kg', totalPrice: 34000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_VN_16' },
  { name: 'Bột Năng Tài Ký 400g', totalPrice: 15000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_VN_16' },
  { name: 'Bột Năng Đa Dụng Meizan 1kg', totalPrice: 29000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_VN_16' },
  { name: 'Bột Nếp Tài Ký 400g', totalPrice: 21000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_VN_16' },
  { name: 'Tinh Bột Bắp Panko 150g', totalPrice: 7000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_VN_16' },
  { name: 'Tinh Bột Khoai Tây EU Food 400g', totalPrice: 39000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_VN_16' },
  // Subcategory 17
  { name: 'Gạo Hạt Ngọc Trời Bạch Dương 5.5kg', totalPrice: 119000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_VN_17' },
  { name: 'Gạo Hạt Ngọc Trời Thiên Long 5kg', totalPrice: 115000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_VN_17' },
  { name: 'Gạo Hạt Ngọc Trời Tiên Nữ 5.5kg', totalPrice: 145000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_VN_17' },
  { name: 'Gạo Neptune Nhãn Vàng 5kg', totalPrice: 119000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_VN_17' },
  { name: 'Gạo Nhật Fuji 5 kg', totalPrice: 191000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_VN_17' },
  { name: 'Gạo lứt Huyết Rồng 2kg', totalPrice: 59000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_VN_17' },
  // Subcategory 18
  { name: 'Bơ Đậu Phộng Hạt Golden Farm 510g', totalPrice: 85000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_VN_18' },
  { name: 'Bơ Đậu Phộng Mịn Golden Farm 340g', totalPrice: 63000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_VN_18' },
  { name: 'Bơ Đậu Phộng Mịn Golden Farm 510g', totalPrice: 85000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_VN_18' },
  { name: 'Bơ Đậu Phộng Mịn Jif 454g', totalPrice: 119000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_VN_18' },
  { name: 'Bắp Đóng Hộp Del Monte 420g', totalPrice: 36000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_VN_18' },
  { name: 'Cà Chua Bóc Vỏ Nguyên Trái Pelati Annalisa 800g', totalPrice: 78000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_VN_18' },
  { name: 'Cà Chua Cắt Miếng Xốt Pizza Polpa Di Pomodoro Annalisa 400g', totalPrice: 39000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_VN_18' },
  { name: 'Cà Chua Nguyên Trái Lột Vỏ Castello 400g', totalPrice: 33000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_VN_18' },
  { name: 'Cà Chua Trái Lột Vỏ Casa Rinaldi 2.55kg', totalPrice: 215000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_VN_18' },
  { name: 'Cà Chua Trái Tròn Pomodorini Annalisa 400g', totalPrice: 49000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_VN_18' },
  { name: 'Cà Chua Xay Cô Đặc Concentrato Di Pomodoro Annalisa 400g', totalPrice: 79000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_VN_18' },
  { name: 'Cá Mòi 555 Ngâm Dầu 155g', totalPrice: 18000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_VN_18' },
  { name: 'Cá Ngừ Century Khúc Ngâm Dầu Thực Vật 184g', totalPrice: 41000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_VN_18' },
  { name: 'Cá Ngừ Century Xắt Lát Ngâm Dầu Thực Vật 170g', totalPrice: 39000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_VN_18' },
  { name: 'Cá Ngừ Century Xắt Lát Ngâm Dầu Thực Vật 170g', totalPrice: 53000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_VN_18' },
  { name: 'Nước Cốt Dừa Xim Mom Cooks 400ml', totalPrice: 28000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_VN_18' },
  { name: 'Thịt Heo Hộp Tulip Pork Luncheon Meat 200g', totalPrice: 51000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_VN_18' },
  { name: 'Thịt Heo Hộp Tulip Pork Luncheon Meat 340g', totalPrice: 79000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_VN_18' },
  { name: 'Thịt Heo Muối Xông Khói Spam Hormel 340g', totalPrice: 119000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_VN_18' },
  { name: 'Thịt Hộp Hormel Spam Less Sodium 340g', totalPrice: 105000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_VN_18' },
  { name: 'Xúc Xích Gà Cocktail Đóng Hộp Tulip 405g', totalPrice: 75000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_VN_18' },
  // Subcategory 19
  { name: 'Mè Không Vỏ Vietsan 150g', totalPrice: 19000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_VN_19' },
  { name: 'Mè Đen Vietsan 150g', totalPrice: 18000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_VN_19' },
  { name: 'Quả Sung Sấy Khô Atlas 1kg', totalPrice: 399000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_VN_19' },
  { name: 'Táo Khô (Cắt Lát)', totalPrice: 69000, unit: EProductUnit.KG, subCategoryId: 'SUBCATE_VN_19' },
  { name: 'Táo Đỏ Tân Cương (Cỡ Trung)', totalPrice: 75000, unit: EProductUnit.KG, subCategoryId: 'SUBCATE_VN_19' },
  { name: 'Đậu Phộng Vietsan 500g', totalPrice: 39000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_VN_19' },
  { name: 'Đậu Xanh Hạt Vietsan 500g', totalPrice: 27000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_VN_19' },
  { name: 'Đậu Đen Vietsan 500g', totalPrice: 28000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_VN_19' },
  { name: 'Đậu Đỏ Vietsan 500g', totalPrice: 35000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_VN_19' },
  // Subcategory 20
  { name: 'Bột Gia Vị Phô Mai O!Sajang 250g', totalPrice: 53000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_VN_20' },
  { name: 'Dầu Hào Chay Lee Kum Kee 510g', totalPrice: 52000, unit: EProductUnit.BOTTLE, subCategoryId: 'SUBCATE_VN_20' },
  { name: 'Dầu Mè Lee Kum Kee 207ml', totalPrice: 76000, unit: EProductUnit.BOTTLE, subCategoryId: 'SUBCATE_VN_20' },
  { name: 'Dầu Mè Lee Kum Kee 750ml', totalPrice: 249000, unit: EProductUnit.BOTTLE, subCategoryId: 'SUBCATE_VN_20' },
  { name: 'Dầu Ớt Lee Kum Kee 207ml', totalPrice: 56000, unit: EProductUnit.BOTTLE, subCategoryId: 'SUBCATE_VN_20' },
  { name: 'Hoa Hồi Nosafood 500g', totalPrice: 229000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_VN_20' },
  { name: 'Hạt Nêm Knorr Thịt Thăn Xương Ống Và Tủy 5kg', totalPrice: 279000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_VN_20' },
  { name: 'Hạt Đinh Hương Nosafood 110g', totalPrice: 79000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_VN_20' },
  { name: 'Hạt Điều Màu Nosafood 500g', totalPrice: 69000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_VN_20' },
  { name: 'Lá Bạc Hà Nosafood 90g', totalPrice: 65000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_VN_20' },
  { name: 'Lá Húng Quế Nosafood 50g', totalPrice: 35000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_VN_20' },
  { name: 'Muối Hạt Bạc Liêu 500g', totalPrice: 4000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_VN_20' },
  { name: 'Muối Hạt Thiên Nhiên Sosal Group 1kg', totalPrice: 7000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_VN_20' },
  { name: 'Lá Gelatine EWALD 1kg', totalPrice: 799000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_VN_20' },
  { name: 'Lá Hương Thảo Nosafood 110g', totalPrice: 99000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_VN_20' },
  { name: 'Lá Mùi Tây Nosafood 15g', totalPrice: 35000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_VN_20' },
  { name: 'Lá Xạ Hương Nosafood 140g', totalPrice: 79000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_VN_20' },
  { name: 'Súp Nền Thịt Heo Knorr 1.5kg', totalPrice: 369000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_VN_20' },
  // Subcategory 21
  { name: 'Dầu Hào Cholimex 350ml', totalPrice: 21000, unit: EProductUnit.BOTTLE, subCategoryId: 'SUBCATE_VN_21' },
  { name: 'Dầu Hào Maggi 1.2kg', totalPrice: 75000, unit: EProductUnit.BOTTLE, subCategoryId: 'SUBCATE_VN_21' },
  { name: 'Gia Vị Nấu Ăn Hon Mirin Umami 880ml', totalPrice: 72000, unit: EProductUnit.BOTTLE, subCategoryId: 'SUBCATE_VN_21' },
  { name: 'Gia Vị Nấu Ăn Ryorishu Umami 880ml', totalPrice: 72000, unit: EProductUnit.BOTTLE, subCategoryId: 'SUBCATE_VN_21' },
  { name: 'Mù Tạt Vàng Crystal 454g', totalPrice: 94000, unit: EProductUnit.BOTTLE, subCategoryId: 'SUBCATE_VN_21' },
  { name: 'Nước Mắm Nam Ngư 750ml', totalPrice: 49000, unit: EProductUnit.BOTTLE, subCategoryId: 'SUBCATE_VN_21' },
  { name: 'Nước Mắm Nam Ngư Siêu Tiết Kiệm 4.8L', totalPrice: 74000, unit: EProductUnit.BOTTLE, subCategoryId: 'SUBCATE_VN_21' },
  { name: 'Nước Mắm Nam Ngư Đệ Nhị 900ml', totalPrice: 24000, unit: EProductUnit.BOTTLE, subCategoryId: 'SUBCATE_VN_21' },
  { name: 'Nước Tương Hương Việt 500ml', totalPrice: 7000, unit: EProductUnit.BOTTLE, subCategoryId: 'SUBCATE_VN_21' },
  { name: 'Nước Tương Maggi Đậm Đặc 700ml', totalPrice: 37000, unit: EProductUnit.BOTTLE, subCategoryId: 'SUBCATE_VN_21' },
  { name: 'Nước Tương Tam Thái Tử 500ml', totalPrice: 8000, unit: EProductUnit.BOTTLE, subCategoryId: 'SUBCATE_VN_21' },
  { name: 'Nước Tương Yamasa 1L', totalPrice: 89000, unit: EProductUnit.BOTTLE, subCategoryId: 'SUBCATE_VN_21' },
  { name: 'Nước tương Maggi thanh dịu 700ml', totalPrice: 30000, unit: EProductUnit.BOTTLE, subCategoryId: 'SUBCATE_VN_21' },
  { name: 'Sốt Basil Sugo Al Basilico Annalisa 350g', totalPrice: 81000, unit: EProductUnit.BOTTLE, subCategoryId: 'SUBCATE_VN_21' },
  { name: 'Sốt Steak Crystal 284g', totalPrice: 89000, unit: EProductUnit.BOTTLE, subCategoryId: 'SUBCATE_VN_21' },
  { name: 'Sốt Worcestershire Crystal 295ml', totalPrice: 95000, unit: EProductUnit.BOTTLE, subCategoryId: 'SUBCATE_VN_21' },
  { name: 'Tương Cà Cholimex 2.1 kg', totalPrice: 68000, unit: EProductUnit.BOTTLE, subCategoryId: 'SUBCATE_VN_21' },
  { name: 'Tương Cà Cholimex 830g', totalPrice: 32000, unit: EProductUnit.BOTTLE, subCategoryId: 'SUBCATE_VN_21' },
  { name: 'Tương Hột Ớt Lee Kum Kee 226g', totalPrice: 52000, unit: EProductUnit.BOTTLE, subCategoryId: 'SUBCATE_VN_21' },
  { name: 'Tương Đen Cholimex 230g', totalPrice: 11000, unit: EProductUnit.BOTTLE, subCategoryId: 'SUBCATE_VN_21' },
  { name: 'Tương Ớt Cholimex 2.1kg', totalPrice: 68000, unit: EProductUnit.BOTTLE, subCategoryId: 'SUBCATE_VN_21' },
  { name: 'Tương Ớt Cholimex 830g', totalPrice: 31000, unit: EProductUnit.BOTTLE, subCategoryId: 'SUBCATE_VN_21' },
  { name: 'Tương ớt Sriracha Cholimex chai 520g', totalPrice: 24000, unit: EProductUnit.BOTTLE, subCategoryId: 'SUBCATE_VN_21' },
  { name: 'Xốt Mù Tạt Vàng Mỹ Golden Farm 250g', totalPrice: 36000, unit: EProductUnit.BOTTLE, subCategoryId: 'SUBCATE_VN_21' },
  { name: 'Dầu Hào Cholimex 350g', totalPrice: 479000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_VN_21' },
  { name: 'Dầu Hào Maggi 1.2kg', totalPrice: 569000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_VN_21' },
  { name: 'Mayonnaise Hương Vị Nhật 1kg', totalPrice: 1069000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_VN_21' },
  { name: 'Nước Mắm Nam Ngư 750ml', totalPrice: 829000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_VN_21' },
  { name: 'Nước Mắm Nam Ngư Siêu Tiết Kiệm 4.8L', totalPrice: 279000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_VN_21' },
  { name: 'Nước Mắm Nam Ngư Đệ Nhị (15*900ml)', totalPrice: 349000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_VN_21' },
  // Subcategory 22
  { name: 'Dầu Cái Lân 25kg', totalPrice: 759000, unit: EProductUnit.CAN, subCategoryId: 'SUBCATE_VN_22' },
  { name: 'Dầu Oliu Extra Virgin Pietro Coricelli 3L', totalPrice: 649000, unit: EProductUnit.CAN, subCategoryId: 'SUBCATE_VN_22' },
  { name: 'Dầu Thực Vật Tinh Luyện Olita Tường An 25kg', totalPrice: 789000, unit: EProductUnit.CAN, subCategoryId: 'SUBCATE_VN_22' },
  { name: 'Dầu Thực Vật Tinh Luyện Tân Sanh 25kg', totalPrice: 779000, unit: EProductUnit.CAN, subCategoryId: 'SUBCATE_VN_22' },
  { name: 'Dầu Ăn Nakydaco 25kg', totalPrice: 819000, unit: EProductUnit.CAN, subCategoryId: 'SUBCATE_VN_22' },
  { name: 'Dầu Ăn Tường An 30L', totalPrice: 889000, unit: EProductUnit.CAN, subCategoryId: 'SUBCATE_VN_22' },
  { name: 'Dầu Ăn Tường An 5L', totalPrice: 219000, unit: EProductUnit.BOTTLE, subCategoryId: 'SUBCATE_VN_22' },
  { name: 'Dầu Gạo Lứt Simply 2L', totalPrice: 150000, unit: EProductUnit.BOTTLE, subCategoryId: 'SUBCATE_VN_22' },
  { name: 'Dầu Hướng Dương Simply 2L', totalPrice: 155000, unit: EProductUnit.BOTTLE, subCategoryId: 'SUBCATE_VN_22' },
  { name: 'Dầu Mè Nakydaco 250ml', totalPrice: 62000, unit: EProductUnit.BOTTLE, subCategoryId: 'SUBCATE_VN_22' },
  { name: 'Dầu Oliu Extra Virgin Pietro Coricelli 500ml', totalPrice: 135000, unit: EProductUnit.BOTTLE, subCategoryId: 'SUBCATE_VN_22' },
  { name: 'Dầu Thực Vật Tinh Luyện Olita Tường An 5L', totalPrice: 191000, unit: EProductUnit.BOTTLE, subCategoryId: 'SUBCATE_VN_22' },
  { name: 'Dầu Ăn Cái Lân 5L', totalPrice: 159000, unit: EProductUnit.BOTTLE, subCategoryId: 'SUBCATE_VN_22' },
  { name: 'Dầu Ăn Tường An 5L', totalPrice: 219000, unit: EProductUnit.BOTTLE, subCategoryId: 'SUBCATE_VN_22' },
  { name: 'Dầu Đậu Nành Simply 5L', totalPrice: 325000, unit: EProductUnit.BOTTLE, subCategoryId: 'SUBCATE_VN_22' },
  { name: 'Dầu Gạo Lứt Simply 2L', totalPrice: 875000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_VN_22' },
  { name: 'Dầu Hướng Dương Simply 2L', totalPrice: 869000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_VN_22' },
  { name: 'Dầu Thực Vật Tinh Luyện Olita Tường An 5L', totalPrice: 749000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_VN_22' },
  { name: 'Dầu Ăn Cái Lân 1L', totalPrice: 395000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_VN_22' },
  { name: 'Dầu Ăn Cái Lân 5L', totalPrice: 599000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_VN_22' },
  { name: 'Dầu Ăn Tường An 5L', totalPrice: 849000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_VN_22' },
  { name: 'Dầu Đậu Nành Simply 5L', totalPrice: 1255000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_VN_22' },
  // Subcategory 23
  { name: 'Giấm Chưng Hương Gạo Hatsune 20L', totalPrice: 799000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_VN_23' },
  { name: 'Giấm Gạo Lisa 4.9L', totalPrice: 135000, unit: EProductUnit.BOTTLE, subCategoryId: 'SUBCATE_VN_23' },
  { name: 'Giấm Gạo Lisa 400ml', totalPrice: 16000, unit: EProductUnit.BOTTLE, subCategoryId: 'SUBCATE_VN_23' },
  { name: 'Giấm Nho Đỏ Chatel Pháp 750ml', totalPrice: 70000, unit: EProductUnit.BOTTLE, subCategoryId: 'SUBCATE_VN_23' },
  { name: 'Giấm Trắng Coroli 1L', totalPrice: 37000, unit: EProductUnit.BOTTLE, subCategoryId: 'SUBCATE_VN_23' },
  { name: 'Giấm Táo Paladin 500ml', totalPrice: 43000, unit: EProductUnit.BOTTLE, subCategoryId: 'SUBCATE_VN_23' },
  { name: 'Giấm Nho Thơm Pietro Coricelli 1L', totalPrice: 189000, unit: EProductUnit.BOTTLE, subCategoryId: 'SUBCATE_VN_23' },
  { name: 'Giấm Gạo Lisa 400ml', totalPrice: 295000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_VN_23' },
  // Subcategory 24
  { name: 'Bột Chanh Knorr 400g', totalPrice: 125000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_VN_24' },
  { name: 'Bột Ngọt Ajinomoto Hạt Nhỏ 1kg', totalPrice: 65000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_VN_24' },
  { name: 'Bột Ngọt Ajinomoto Hạt lớn 1kg', totalPrice: 74000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_VN_24' },
  { name: 'Bột Wasabi 1kg', totalPrice: 205000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_VN_24' },
  { name: 'Bột ngọt Ajinomoto hạt lớn 400g', totalPrice: 34000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_VN_24' },
  { name: 'Bột Ớt 1kg', totalPrice: 179000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_VN_24' },
  { name: 'Hạt Nêm Knorr Thịt Thăn Xương Ống 3kg', totalPrice: 169000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_VN_24' },
  { name: 'Hạt Nêm Maggi Nấm Hương 2kg', totalPrice: 199000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_VN_24' },
  { name: 'Đường Bột Làm Bánh Biên Hòa 1kg', totalPrice: 42000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_VN_24' },
  { name: 'Bột Thịt Gà Knorr 1kg', totalPrice: 139000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_VN_24' },
  { name: 'Bột Xốt Nâu Demiglace Knorr 1kg', totalPrice: 335000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_VN_24' },
  { name: 'Súp Nền Thịt Bò Knorr 1.5kg', totalPrice: 400000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_VN_24' },
  { name: 'Bột Chiên Xù Panko 1kg', totalPrice: 419000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_VN_24' },
  { name: 'Hạt Nêm Knorr Thịt Thăn Xương Ống 3kg', totalPrice: 639000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_VN_24' },
  { name: 'Hạt Nêm Maggi Nấm Hương 2kg', totalPrice: 1139000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_VN_24' },
  { name: 'Bột Thịt Gà Maggi 1kg', totalPrice: 1099000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_VN_24' },
  // Subcategory 25
  { name: 'Mật Ong Hoa Cà Phê 500ml', totalPrice: 77000, unit: EProductUnit.BOTTLE, subCategoryId: 'SUBCATE_VN_25' },
  { name: 'Mật Ong Hoa Cà Phê Phương Di 1L', totalPrice: 155000, unit: EProductUnit.BOTTLE, subCategoryId: 'SUBCATE_VN_25' },
  { name: 'Mật Ong Rừng BeHoney 1.5kg', totalPrice: 185000, unit: EProductUnit.BOTTLE, subCategoryId: 'SUBCATE_VN_25' },
  { name: 'Mật Ong Thiên Nhiên 500ml', totalPrice: 99000, unit: EProductUnit.BOTTLE, subCategoryId: 'SUBCATE_VN_25' },
  { name: 'Mật Ong Thiên Nhiên Phương Di 1L', totalPrice: 175000, unit: EProductUnit.BOTTLE, subCategoryId: 'SUBCATE_VN_25' },
  { name: 'Mật Ong Đa Hoa Rừng Sesan 500ml', totalPrice: 155000, unit: EProductUnit.BOTTLE, subCategoryId: 'SUBCATE_VN_25' },
  // Subcategory 26
  { name: 'Andros Top Up Thạch Vải 1kg', totalPrice: 83000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_VN_26' },
  { name: 'Bột Cacao Tin Provisions Marou 1kg', totalPrice: 689000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_VN_26' },
  { name: 'Mứt Andros Chunky Anh Đào Túi 1kg', totalPrice: 209000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_VN_26' },
  { name: 'Mứt Andros Chunky Bưởi Đỏ Yuzu Túi 1kg', totalPrice: 189000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_VN_26' },
  { name: 'Mứt Andros Chunky Dâu Túi 1kg', totalPrice: 185000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_VN_26' },
  { name: 'Mứt Andros Chunky Khoai Lang Tím Túi 1kg', totalPrice: 146000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_VN_26' },
  { name: 'Mứt Andros Chunky Kiwi Túi 1kg', totalPrice: 199000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_VN_26' },
  { name: 'Mứt Andros Chunky Lê, Hoa Cúc Túi 1kg', totalPrice: 195000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_VN_26' },
  { name: 'Mứt Andros Chunky Lê, Táo Và Quế Túi 1kg', totalPrice: 169000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_VN_26' },
  { name: 'Mứt Andros Chunky Mơ, Sơ Ri Và Hạt Chia Túi 1kg', totalPrice: 175000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_VN_26' },
  { name: 'Mứt Andros Chunky Phúc Bồn Tử Túi 1kg', totalPrice: 185000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_VN_26' },
  { name: 'Mứt Andros Chunky Trái Mọng Và Hoa Atiso Đỏ Túi 1kg', totalPrice: 199000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_VN_26' },
  { name: 'Mứt Andros Chunky Việt Quất Túi 1kg', totalPrice: 225000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_VN_26' },
  { name: 'Mứt Andros Chunky Vải Hoa Hồng Túi 1kg', totalPrice: 200000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_VN_26' },
  { name: 'Mứt Andros Chunky Xoài Túi 1kg', totalPrice: 169000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_VN_26' },
  { name: 'Mứt Andros Chunky Đào Túi 1kg', totalPrice: 175000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_VN_26' },
  { name: 'Mứt Andros Chunky Ổi Hồng Túi 1kg', totalPrice: 175000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_VN_26' },
  { name: 'Mứt Dâu LongBeach 900ml', totalPrice: 159000, unit: EProductUnit.BOTTLE, subCategoryId: 'SUBCATE_VN_26' },
  { name: 'Mứt Dừa Non LongBeach 900ml', totalPrice: 159000, unit: EProductUnit.BOTTLE, subCategoryId: 'SUBCATE_VN_26' },
  { name: 'Mứt Trái Mây LongBeach 900ml', totalPrice: 159000, unit: EProductUnit.BOTTLE, subCategoryId: 'SUBCATE_VN_26' },
  { name: 'Mứt Vải LongBeach 900ml', totalPrice: 159000, unit: EProductUnit.BOTTLE, subCategoryId: 'SUBCATE_VN_26' },
  { name: 'Mứt Đào LongBeach 900ml', totalPrice: 159000, unit: EProductUnit.BOTTLE, subCategoryId: 'SUBCATE_VN_26' },
  { name: 'Osterberg Sinh Tố Dứa Xoài 1000ml', totalPrice: 124000, unit: EProductUnit.BOTTLE, subCategoryId: 'SUBCATE_VN_26' },
  { name: 'Sinh Tố Cam/ Xoài Osterberg 1000ml', totalPrice: 125000, unit: EProductUnit.BOTTLE, subCategoryId: 'SUBCATE_VN_26' },
  { name: 'Sinh Tố Dâu Osterberg 1000ml', totalPrice: 105000, unit: EProductUnit.BOTTLE, subCategoryId: 'SUBCATE_VN_26' },
  { name: 'Sinh Tố Kiwi Osterberg 1000ml', totalPrice: 122000, unit: EProductUnit.BOTTLE, subCategoryId: 'SUBCATE_VN_26' },
  { name: 'Sinh Tố Việt Quất Osterberg 1000ml', totalPrice: 149000, unit: EProductUnit.BOTTLE, subCategoryId: 'SUBCATE_VN_26' },
  { name: 'Sinh Tố Vải Osterberg 1000ml', totalPrice: 149000, unit: EProductUnit.BOTTLE, subCategoryId: 'SUBCATE_VN_26' },
  { name: 'Sinh Tố Xoài Osterberg 1000ml', totalPrice: 139000, unit: EProductUnit.BOTTLE, subCategoryId: 'SUBCATE_VN_26' },
  { name: 'Sinh Tố Đào Osterberg 1000ml', totalPrice: 109000, unit: EProductUnit.BOTTLE, subCategoryId: 'SUBCATE_VN_26' },
  { name: 'Siro Anh Đào LongBeach 740ml', totalPrice: 95000, unit: EProductUnit.BOTTLE, subCategoryId: 'SUBCATE_VN_26' },
  { name: 'Siro Caramel Muối Torani Classic 750ml', totalPrice: 189000, unit: EProductUnit.BOTTLE, subCategoryId: 'SUBCATE_VN_26' },
  { name: 'Siro Caramel Nguyên Vị LongBeach 740ml', totalPrice: 124000, unit: EProductUnit.BOTTLE, subCategoryId: 'SUBCATE_VN_26' },
  { name: 'Siro Chocolate Hersheys 680g', totalPrice: 115000, unit: EProductUnit.BOTTLE, subCategoryId: 'SUBCATE_VN_26' },
  { name: 'Siro Dâu Hersheys 623g', totalPrice: 115000, unit: EProductUnit.BOTTLE, subCategoryId: 'SUBCATE_VN_26' },
  { name: 'Siro Dâu LongBeach 740ml', totalPrice: 95000, unit: EProductUnit.BOTTLE, subCategoryId: 'SUBCATE_VN_26' },
  { name: 'Siro Dưa Lưới LongBeach 740ml', totalPrice: 95000, unit: EProductUnit.BOTTLE, subCategoryId: 'SUBCATE_VN_26' },
  { name: 'Siro Dừa Non LongBeach 740ml', totalPrice: 124000, unit: EProductUnit.BOTTLE, subCategoryId: 'SUBCATE_VN_26' },
  // Subcategory 27
  { name: 'Cá Hồi Xông Khói Cắt Lát Amigo 100g', totalPrice: 81000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_VN_27' },
  { name: 'Cá Hồi Xông Khói Cắt Lát Amigo 500g', totalPrice: 355000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_VN_27' },
  // Subcategory 28
  { name: 'Tôm Sú Đông Lạnh Size 26 - 30 Việt Tín 1kg', totalPrice: 279000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_VN_28' },
  { name: 'Tôm Sú Đông Lạnh Size 46 - 50 Việt Tín 1kg', totalPrice: 215000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_VN_28' },
  { name: 'Tôm Thẻ Nõn Đông Lạnh Size 31 - 40 Việt Tín 1kg', totalPrice: 299000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_VN_28' },
  { name: 'Tôm Thẻ Nõn Đông Lạnh Size 91 - 120 Việt Tín 1kg', totalPrice: 199000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_VN_28' },
  { name: 'Tôm Thẻ Đông Lạnh Size 26 - 30 Việt Tín 1kg', totalPrice: 239000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_VN_28' },
  { name: 'Tôm Thẻ Đông Lạnh Size 46 - 50 Việt Tín 1kg', totalPrice: 189000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_VN_28' },
  { name: 'Tôm Tẩm Bột 180g', totalPrice: 53000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_VN_28' },
  // Subcategory 29
  { name: 'Mực Nang Đông Lạnh Size 2 - 4 Việt Tín 1kg', totalPrice: 299000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_VN_29' },
  { name: 'Mực Trứng Đông Lạnh Size 12 - 15 Việt Tín 1kg', totalPrice: 189000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_VN_29' },
  // Subcategory 30
  { name: 'Còi Sò Điệp Đông Lạnh Size 60 - 80 Việt Tín 1kg', totalPrice: 179000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_VN_30' },
  // Subcategory 31
  { name: 'Cá Viên Đông Lạnh CP 500g', totalPrice: 34000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_VN_31' },
  // Subcategory 32
  { name: 'Sữa Tươi Thanh Trùng Barista Milk 1.8L', totalPrice: 69000, unit: EProductUnit.BOTTLE, subCategoryId: 'SUBCATE_VN_32' },
  { name: 'Sữa Tươi Nguyên Kem Tiệt Trùng PUILAY 1L', totalPrice: 33000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_VN_32' },
  { name: 'Sữa Tươi Thanh Trùng Dalat Milk 950ml - Không Đường', totalPrice: 37000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_VN_32' },
  { name: 'Sữa Tươi Tiệt Trùng Anchor 1L', totalPrice: 45000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_VN_32' },
  { name: 'Sữa Tươi Tiệt Trùng Nguyên Chất TH True Milk (Không Đường) 1L', totalPrice: 36000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_VN_32' },
  { name: 'Sữa Tươi Tiệt Trùng Vinamilk 100% Không Đường 1L', totalPrice: 33000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_VN_32' },
  { name: 'Sữa Đậu Nành SuperSoy Có Đường 1L', totalPrice: 25000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_VN_32' },
  { name: 'Sữa Đậu Nành SuperSoy Không Đường 1L', totalPrice: 25000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_VN_32' },
  { name: 'Sữa Đặc Hoàn Hảo 1270g', totalPrice: 61000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_VN_32' },
  { name: 'Sữa Đặc Ngôi Sao Phương Nam Xanh Biển 1284g', totalPrice: 52000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_VN_32' },
  { name: 'Sữa Đặc Tài Lộc Vinamilk 1284g', totalPrice: 47000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_VN_32' },
  { name: 'Sữa đặc Ngôi Sao Phương Nam 1284g', totalPrice: 63000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_VN_32' },
  { name: 'Sữa Tươi Nguyên Kem Tiệt Trùng PUILAY 1L', totalPrice: 189000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_VN_32' },
  { name: 'Sữa Tươi Tiệt Trùng Anchor 1L x 12 Hộp', totalPrice: 509000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_VN_32' },
  { name: 'Sữa Tươi Tiệt Trùng Nguyên Chất TH True Milk (Không Đường) 1L', totalPrice: 419000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_VN_32' },
  { name: 'Sữa Tươi Tiệt Trùng Vinamilk 100% Không Đường 1L', totalPrice: 385000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_VN_32' },
  { name: 'Sữa Đậu Nành SuperSoy Có Đường 1L', totalPrice: 285000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_VN_32' },
  { name: 'Sữa Đậu Nành SuperSoy Không Đường 1L', totalPrice: 285000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_VN_32' },
  { name: 'Sữa Đặc Hoàn Hảo 1270g', totalPrice: 709000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_VN_32' },
  { name: 'Sữa Đặc Ngôi Sao Phương Nam 1284g', totalPrice: 739000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_VN_32' },
  { name: 'Sữa Đặc Ngôi Sao Phương Nam Xanh Biển 1284g', totalPrice: 599000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_VN_32' },
  { name: 'Sữa Đặc Tài Lộc Vinamilk 1284g', totalPrice: 549000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_VN_32' },
  // Subcategory 33
  { name: 'Kem Base Pha Chế Đa Dụng ICEHOT 907g', totalPrice: 87000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_VN_33' },
  { name: 'Kem Béo Thực Vật ICEHOT 454g', totalPrice: 32000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_VN_33' },
  { name: 'Kem Nấu Anchor UHT EXTRA 1L', totalPrice: 149000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_VN_33' },
  { name: 'Kem Nấu Đa Năng Versatie 1L', totalPrice: 159000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_VN_33' },
  { name: 'Kem Topping Pha Chế Tiện Dụng ICEHOT 907g', totalPrice: 74000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_VN_33' },
  { name: 'Kem Trang Trí 35% Chất Béo Từ Sữa Richs 1L', totalPrice: 149000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_VN_33' },
  { name: 'Kem Sữa Tatua 36% 1L', totalPrice: 155000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_VN_33' },
  { name: 'Kem Sữa Tatua 38% 1L', totalPrice: 157000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_VN_33' },
  { name: 'Kem Béo Thực Vật ICEHOT 454g', totalPrice: 739000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_VN_33' },
  { name: 'Kem Sữa Tươi Tiệt Trùng Anchor 1L', totalPrice: 1839000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_VN_33' },
  // Subcategory 34
  { name: 'Bơ Lạt Anchor 5kg', totalPrice: 1299000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_VN_34' },
  { name: 'Bơ Lạt Tấm Anchor 1kg', totalPrice: 325000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_VN_34' },
  { name: 'Bơ Thực Vật Tường An 800g', totalPrice: 48000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_VN_34' },
  { name: 'Bơ Lạt Anchor 7g', totalPrice: 1049000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_VN_34' },
  { name: 'Bơ Thực Vật Tường An 20kg', totalPrice: 775000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_VN_34' },
  { name: 'Bơ Lạt Anchor 7g x 100 Viên', totalPrice: 389000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_VN_34' },
  { name: 'Bơ Mặn Anchor 200g', totalPrice: 99000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_VN_34' },
  // Subcategory 35
  { name: 'Phô Mai Cheddar Lát Anchor 200g', totalPrice: 61000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_VN_35' },
  { name: 'Phô Mai Cheddar Lát Chesdale 250g', totalPrice: 75000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_VN_35' },
  { name: 'Phô Mai Lát Con Bò Cười Burger 200g', totalPrice: 68000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_VN_35' },
  { name: 'Phô Mai Lát Màu 1040g', totalPrice: 285000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_VN_35' },
  { name: 'Phô Mai Mascarpone Tatua 500g', totalPrice: 145000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_VN_35' },
  { name: 'Phô Mai Mozzarella Bào Bottega Zelachi 1kg', totalPrice: 199000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_VN_35' },
  { name: 'Phô Mai Mozzarella Dạng Bào 2kg', totalPrice: 439000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_VN_35' },
  { name: 'Phô Mai Mozzarella Khối Bottega Zelachi 1kg', totalPrice: 209000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_VN_35' },
  { name: 'Phô Mai Con Bò Cười Vị Truyền Thống 16M 224g', totalPrice: 74000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_VN_35' },
  // Subcategory 36
  { name: 'Sữa Chua Không Đường Dalat Milk 1kg', totalPrice: 67000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_VN_36' },
  { name: 'Sữa Chua Không Đường Dalat Milk 500g', totalPrice: 36000, unit: EProductUnit.BOX, subCategoryId: 'SUBCATE_VN_36' },
  { name: 'Sữa Chua Ăn Vinamilk Có Đường 100g', totalPrice: 24000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_VN_36' },
  { name: 'Sữa Chua Ăn Vinamilk Không Đường 100g', totalPrice: 24000, unit: EProductUnit.PACK, subCategoryId: 'SUBCATE_VN_36' },
  { name: 'Sữa Chua Ăn Vinamilk Có Đường 100g', totalPrice: 269000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_VN_36' },
  { name: 'Sữa Chua Ăn Vinamilk Không Đường 100g', totalPrice: 269000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_VN_36' },
  // Subcategory 37
  { name: 'Bia 333 330ml', totalPrice: 287000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_VN_37' },
  { name: 'Bia Corona Chai Thuỷ Tinh 300ml', totalPrice: 609000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_VN_37' },
  { name: 'Bia Heineken Bạc Lon Cao 330ml', totalPrice: 469000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_VN_37' },
  { name: 'Bia Heineken Lon Cao 330ml', totalPrice: 455000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_VN_37' },
  { name: 'Bia Saigon Lager Lon 330ml', totalPrice: 269000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_VN_37' },
  { name: 'Bia Saigon Special Lon 330ml', totalPrice: 355000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_VN_37' },
  { name: 'Bia Sapporo 330ml', totalPrice: 405000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_VN_37' },
  { name: 'Bia Tiger Bạc Lon 330ml', totalPrice: 415000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_VN_37' },
  { name: 'Bia Tiger Lon 330ml', totalPrice: 359000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_VN_37' },
  { name: 'Bia Asahi SUPER DRY 350ml', totalPrice: 1219000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_VN_37' },
  { name: 'Bia Coronita Extra Chai Thuỷ Tinh 207ml', totalPrice: 449000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_VN_37' },
  { name: 'Bia Kirin 350ml', totalPrice: 1329000, unit: EProductUnit.BIN, subCategoryId: 'SUBCATE_VN_37' },
  // Subcategory 38
  { name: 'Rượu mơ Komomo Premium 750ml', totalPrice: 399000, unit: EProductUnit.BOTTLE, subCategoryId: 'SUBCATE_VN_38' },
  { name: 'Rượu mơ Komomo Single Year 750ml', totalPrice: 249000, unit: EProductUnit.BOTTLE, subCategoryId: 'SUBCATE_VN_38' },
  { name: 'Rượu mơ Komomo Special 750ml', totalPrice: 329000, unit: EProductUnit.BOTTLE, subCategoryId: 'SUBCATE_VN_38' },
];

const products_vn: Product[] = [...items].map((item, idx) => ({
  id: `P_VN_${idx + 1}`,
  name: item.name,
  inventory: 10000,
  costPrice: 0,
  profit: 0,
  totalPrice: item.totalPrice,
  subCategoryId: item.subCategoryId,
  unit: item.unit ?? EProductUnit.KG,
  status: EProductStatus.ACTIVE,
  inventoryStatus: EInventoryStatus.IN_STOCK,
  langCode: ELang.VN,
  createdAt: new Date(),
  updatedAt: new Date(),
}));

export default products_vn;
