import { Comment } from '@prisma/client';

const comments: Comment[] = [
  {
    id: 'COM_1',
    content: 'This is root comment',
    parentId: '',
    customerId: 'CUS_1',
    productId: 'PRO_57',
    isDelete: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'COM_2',
    content: 'This is root comment',
    parentId: '',
    customerId: 'CUS_2',
    productId: 'PRO_57',
    isDelete: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'COM_3',
    content: 'This is root comment',
    parentId: '',
    customerId: 'CUS_3',
    productId: 'PRO_57',
    isDelete: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  {
    id: 'COM_4',
    content: 'This is child comment',
    parentId: 'COM_1',
    customerId: 'CUS_3',
    productId: 'PRO_57',
    isDelete: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'COM_5',
    content: 'This is child comment',
    parentId: 'COM_1',
    customerId: 'CUS_3',
    productId: 'PRO_57',
    isDelete: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'COM_6',
    content: 'This is child comment',
    parentId: 'COM_1',
    customerId: 'CUS_3',
    productId: 'PRO_57',
    isDelete: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'COM_7',
    content: 'This is child comment',
    parentId: 'COM_1',
    customerId: 'CUS_3',
    productId: 'PRO_57',
    isDelete: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'COM_8',
    content: 'This is child comment',
    parentId: 'COM_1',
    customerId: 'CUS_3',
    productId: 'PRO_57',
    isDelete: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  {
    id: 'COM_9',
    content: 'This is child comment',
    parentId: 'COM_2',
    customerId: 'CUS_1',
    productId: 'PRO_57',
    isDelete: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'COM_10',
    content: 'This is child comment',
    parentId: 'COM_2',
    customerId: 'CUS_1',
    productId: 'PRO_57',
    isDelete: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'COM_11',
    content: 'This is child comment',
    parentId: 'COM_2',
    customerId: 'CUS_1',
    productId: 'PRO_57',
    isDelete: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'COM_12',
    content: 'This is child comment',
    parentId: 'COM_2',
    customerId: 'CUS_1',
    productId: 'PRO_57',
    isDelete: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'COM_13',
    content: 'This is child comment',
    parentId: 'COM_2',
    customerId: 'CUS_1',
    productId: 'PRO_57',
    isDelete: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  {
    id: 'COM_14',
    content: 'This is child comment',
    parentId: 'COM_3',
    customerId: 'CUS_2',
    productId: 'PRO_57',
    isDelete: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'COM_15',
    content: 'This is child comment',
    parentId: 'COM_3',
    customerId: 'CUS_2',
    productId: 'PRO_57',
    isDelete: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'COM_16',
    content: 'This is child comment',
    parentId: 'COM_3',
    customerId: 'CUS_2',
    productId: 'PRO_57',
    isDelete: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'COM_18',
    content: 'This is child comment',
    parentId: 'COM_3',
    customerId: 'CUS_2',
    productId: 'PRO_57',
    isDelete: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'COM_19',
    content: 'This is child comment',
    parentId: 'COM_3',
    customerId: 'CUS_2',
    productId: 'PRO_57',
    isDelete: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export default comments;
