import { Order } from '@prisma/client';
import {
  EOrderPaymentMethod,
  EOrderPaymentStatus,
  EOrderStatus,
  EReceivedType,
} from '../../src/modules/order/order.enum';

const currentDate = new Date();
const previousDate = new Date(currentDate);
previousDate.setDate(currentDate.getDate() - 1);
const precedingDate = new Date(currentDate);
precedingDate.setDate(currentDate.getDate() - 2);

const orders: Order[] = [
  {
    id: 'O_1',
    orderNumber: `#O_${Date.now()}`,
    status: EOrderStatus.WAITTING,
    paymentMethod: EOrderPaymentMethod.TRANSFER,
    paymentStatus: EOrderPaymentStatus.UNPAID,
    receivedType: EReceivedType.STORE,
    shipmentFee: 0,
    totalPayment: 657800,
    userId: 'US_5',
    note: 'Be careful',
    isDelete: false,
    createdAt: currentDate,
    updatedAt: currentDate,
  },
  {
    id: 'O_2',
    orderNumber: `#O_${Date.now()}`,
    status: EOrderStatus.DELIVERING,
    paymentMethod: EOrderPaymentMethod.CASH,
    paymentStatus: EOrderPaymentStatus.PAID,
    receivedType: EReceivedType.STORE,
    shipmentFee: 0,
    totalPayment: 1021900,
    userId: 'US_5',
    note: '',
    isDelete: false,
    createdAt: currentDate,
    updatedAt: currentDate,
  },
  {
    id: 'O_3',
    orderNumber: `#O_${Date.now()}`,
    status: EOrderStatus.DELIVERED,
    paymentMethod: EOrderPaymentMethod.COD,
    paymentStatus: EOrderPaymentStatus.PAID,
    receivedType: EReceivedType.DELIVERY,
    shipmentFee: 50000,
    totalPayment: 2036100,
    userId: 'US_6',
    note: '',
    isDelete: false,
    createdAt: currentDate,
    updatedAt: currentDate,
  },
  {
    id: 'O_4',
    orderNumber: `#O_${Date.now() - 1}`,
    status: EOrderStatus.DELIVERED,
    paymentMethod: EOrderPaymentMethod.COD,
    paymentStatus: EOrderPaymentStatus.PAID,
    receivedType: EReceivedType.DELIVERY,
    shipmentFee: 50000,
    totalPayment: 2036100,
    userId: 'US_7',
    note: '',
    isDelete: false,
    createdAt: previousDate,
    updatedAt: previousDate,
  },
  {
    id: 'O_5',
    orderNumber: `#O_${Date.now() - 1}`,
    status: EOrderStatus.DELIVERED,
    paymentMethod: EOrderPaymentMethod.COD,
    paymentStatus: EOrderPaymentStatus.PAID,
    receivedType: EReceivedType.DELIVERY,
    shipmentFee: 50000,
    totalPayment: 2036100,
    userId: 'US_8',
    note: '',
    isDelete: false,
    createdAt: previousDate,
    updatedAt: previousDate,
  },
  {
    id: 'O_6',
    orderNumber: `#O_${Date.now() + 1}`,
    status: EOrderStatus.DELIVERED,
    paymentMethod: EOrderPaymentMethod.COD,
    paymentStatus: EOrderPaymentStatus.PAID,
    receivedType: EReceivedType.DELIVERY,
    shipmentFee: 50000,
    totalPayment: 2036100,
    userId: 'US_9',
    note: '',
    isDelete: false,
    createdAt: precedingDate,
    updatedAt: precedingDate,
  },
  {
    id: 'O_7',
    orderNumber: `#O_${Date.now() + 1}`,
    status: EOrderStatus.DELIVERED,
    paymentMethod: EOrderPaymentMethod.COD,
    paymentStatus: EOrderPaymentStatus.PAID,
    receivedType: EReceivedType.DELIVERY,
    shipmentFee: 50000,
    totalPayment: 2036100,
    userId: 'US_10',
    note: '',
    isDelete: false,
    createdAt: precedingDate,
    updatedAt: precedingDate,
  },
];

export default orders;
