import { UserPermission } from '@prisma/client';

const userPermissions: UserPermission[] = [
  {
    id: 'US_PER_1',
    create: true,
    update: true,
    remove: true,
    isDelete: false,
    userId: 'US_1',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'US_PER_2',
    create: true,
    update: true,
    remove: false,
    isDelete: false,
    userId: 'US_2',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'US_PER_3',
    create: false,
    update: false,
    remove: false,
    isDelete: false,
    userId: 'US_3',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'US_PER_4',
    create: false,
    update: false,
    remove: false,
    isDelete: false,
    userId: 'US_4',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'US_PER_5',
    create: false,
    update: false,
    remove: false,
    isDelete: false,
    userId: 'US_5',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'US_PER_6',
    create: false,
    update: false,
    remove: false,
    isDelete: false,
    userId: 'US_6',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'US_PER_7',
    create: false,
    update: false,
    remove: false,
    isDelete: false,
    userId: 'US_7',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'US_PER_8',
    create: false,
    update: false,
    remove: false,
    isDelete: false,
    userId: 'US_8',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'US_PER_9',
    create: false,
    update: false,
    remove: false,
    isDelete: false,
    userId: 'US_9',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'US_PER_10',
    create: false,
    update: false,
    remove: false,
    isDelete: false,
    userId: 'US_10',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export default userPermissions;
