# Simulated daily request to your render project so that the service doesn't go down
name: Daily render ping

on:
  schedule:
    - cron: '*/12 * * * *'  # Runs daily at midnight UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  curl-website:
    runs-on: ubuntu-latest

    steps:
      - name: Run cURL on Website
        run: curl -I https://healthy-food-api-g4t7.onrender.com
